### ISSUE TITLE
Consider changing the name

### ISSUE THREAD

**Issue by libanp** [SamTV12345/PodFetch#10]
### Clear and concise description of the problem

This project seems to be more 'inspired by podgrab' than 'podgrab 2'. I expected there to be some shared code or contributors, but as far as I can tell this is an entirely separate project that just uses the name. Other potential users and contributors might arrive with similar expectations. Would you consider changing the name to signal the differences better?

### Suggested solution

Names are hard, er... PodNab? Gatherpod? 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by SamTV12345** [comment]
Yes you are right. I started from scratch and rebuilt the functionality of the original project which was written in Go/Vue. I didn't invest much time in the naming of the project so any suggestions are welcome. What would be the story behind PodNap or Gatherpod? Podgrab was the allusion to grabbing podcasts from the internet.

**Comment by SamTV12345** [comment]
Found a good name while browsing some ideas: Podfetch - A sleek and efficient podcast downloader.
