### ISSUE TITLE
Very large podcasts has duplicate downlods

### ISSUE THREAD

**Issue by Patriot2407** [SamTV12345/PodFetch#1018]
### Describe the bug

I have a very large podcast I am trying to archive, with thousands of episodes. Unfortunately, it is occasionally duplicating some of the episodes and I am not sure why, or if there is a way to clean it up. If it will auto clean up after it's done downloading the thousands of episodes, let me know and this can be closed.
![Screenshot_2024-11-19_15-58-08](https://github.com/user-attachments/assets/a278930e-1c8e-42af-8e5d-b9aee07fafc8)

### Reproduction

added podcast that is very large and set to download 999999 episodes

### System Info

```Shell
Using docker on unraid. I tried to run the command listed, but it errors out because apparently the command is not in /bin nor does this container apparently have a bash shell.
```

### Used Package Manager

docker

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Patriot2407** [comment]
Okay so, I resolved that issue by completely removing the podcast and deleting all the files. Now I believe the issue is due to the fact that PodFetch doesn't realize it has already downloaded the files. It shows the download to server cloud clickable and not filled in for every episode, even though it downloaded every single one, and I confirm they do work and are downloaded .mp3s

So now my issue is that for alot of my podcasts, it has downloaded the files, but doesn't show they are downloaded in the software.

**Comment by Patriot2407** [comment]
Everytime I click refresh podcast, it creates duplicate files again.

**Comment by Patriot2407** [comment]
![Screenshot_2024-11-20_07-30-36](https://github.com/user-attachments/assets/1ea1cc5c-b866-49cf-a40e-6868faf86827)
I can confirm this is the issue, and it's getting really bad and is now causing terabytes of duplicated data and wasted bandwidth by repeatedly downloading episodes already present over and over again every time it refreshes the podcast

**Comment by burgsth** [comment]
I have the same issue with one podcast feed out of three subscribed. The older the cast is the often it is downloaded.

**Comment by Patriot2407** [comment]
For anyone else having this issues, I believe a workaround is to turn off downloading of all podcasts before present day to stop it downloading those episodes over and over again. Unfortunately, it will continue on new episodes if you have the download new episodes option checked, but at least it won't keep downloading the same files every time you refresh if you turn if off. I believe this bug is happening because there is some other filetypes published by the source of the podcast, and PodFetch says it doesn't support it, so it thinks it failed even though it already successfully downloaded the .mp3

**Comment by Patriot2407** [comment]
It looks like every podcast with this issue has the following log
![Screenshot_2024-11-25_20-38-28](https://github.com/user-attachments/assets/552bad7c-7a6a-4f14-b102-4631cdb4a17d)
And PodFetch thinks it did not download the episode, but it did download the .mp3

**Comment by Patriot2407** [comment]
![Screenshot_2024-11-25_21-16-09](https://github.com/user-attachments/assets/bda3d19b-fc5f-4c6b-926a-2a4e45ca6686)
More details

**Comment by Patriot2407** [comment]
Just pulled latest version, and this issue still occurs.

System information reports I'm on the below version:
v4.7.1-d195f456 (HEAD)

**Comment by Patriot2407** [comment]
I just pulled the latest version v4.7.1-a089fcbf (HEAD) according to system info, and this issue still exists.
![Screenshot_2024-11-30_18-51-12](https://github.com/user-attachments/assets/57b10307-d623-4d18-a0f7-f76b3ac9b439)

**Comment by Patriot2407** [comment]
Still creates the duplicated folders, looks like nothing has changed. The only difference is just that now there is a panic error in the log vs just saying file format is not supported.

**Comment by SamTV12345** [comment]
> Still creates the duplicated folders, looks like nothing has changed. The only difference is just that now there is a panic error in the log vs just saying file format is not supported.

Which podcast are you downloading and how many podcast episodes do you download initially?

**Comment by Patriot2407** [comment]
I download over 60 podcasts or more. It does it on almost all of them. Some of the podcasts I only download 1 episode (my daily news ones) and some I download all. It makes no difference, anytime i refresh a podcast that says file format not supported, it always duplicates the folder because it thinks it doesn't have it downloaded yet. I have 2 separate instances of Podfetch docker. One for my short term daily news podcasts, and my long term "archived" podcasts that I'll listen to later. My "short term" instance is set to download 5 episodes initially, and my "long term" instance is set to download 99999 initially. It happens on both. Right now all my "long term" podcasts have been paused until the issue is resolved due to unnecessary disk space.

**Comment by PePeLLee** [comment]
You can test it with https://anchor.fm/s/13a6bdec/podcast/rss .
Now with standard settings it downloads one of episodes each hour:
![image](https://github.com/user-attachments/assets/b0a77989-0283-4571-9578-805c679001df)

**Comment by burgsth** [comment]
I just made a new podfetch instance and added only one podcastfeed.
After adding the feed it starts downloading and every file downloaded throws an id3v2 error. The .mp3 and .jpg file is downloaded. After one hour it starts again downloading. The container runs for about three hours and there are already treetimes downloaded podcast.

`podfetch  | 2024-12-04T10:16:06 ℹ️ - Downloading podcast episode: Deus Ex! (SF 2)
podfetch  | 2024-12-04T10:16:10 ❌ - File format not supported: Id3v2
podfetch  | 2024-12-04T10:16:10 ❌ - Error downloading podcast episode: The following error occurred: File format not supported
podfetch  | 2024-12-04T10:16:10 ℹ️ - Downloading podcast episode: Revolution! (SF 1 Classic)
podfetch  | 2024-12-04T10:16:14 ❌ - File format not supported: Id3v2
podfetch  | 2024-12-04T10:16:14 ❌ - Error downloading podcast episode: The following error occurred: File format not supported
podfetch  | 2024-12-04T10:16:14 ℹ️ - Downloading podcast episode: Baphomets Fluch (SF 1 REMAKE)
podfetch  | 2024-12-04T10:16:23 ❌ - File format not supported: Id3v2
podfetch  | 2024-12-04T10:16:23 ❌ - Error downloading podcast episode: The following error occurred: File format not supported
podfetch  | 2024-12-04T10:16:23 ℹ️ - Polling for new episodes successful
podfetch  | 2024-12-04T10:16:24 ℹ️ - Polling for new episodes
podfetch  | 2024-12-04T10:16:25 ℹ️ - Downloading podcast episode: Fable (SSF 79)
podfetch  | 2024-12-04T10:16:39 ❌ - File format not supported: Id3v2
podfetch  | 2024-12-04T10:16:40 ❌ - Error downloading podcast episode: The following error occurred: File format not supported
podfetch  | 2024-12-04T10:16:40 ℹ️ - Downloading podcast episode: Ascendancy (SF 149)
podfetch  | 2024-12-04T10:16:53 ❌ - File format not supported: Id3v2
podfetch  | 2024-12-04T10:16:53 ❌ - Error downloading podcast episode: The following error occurred: File format not supported
podfetch  | 2024-12-04T10:16:53 ℹ️ - Downloading podcast episode: Deus Ex (SF 148)
podfetch  | 2024-12-04T10:17:07 ❌ - File format not supported: Id3v2
podfetch  | 2024-12-04T10:17:08 ❌ - Error downloading podcast episode: The following error occurred: File format not supported

Downloades on 2024-12-04T10:16:14 was the first episode, and again on 2024-12-04T10:16:25 it starts getting the latest

**Comment by OldBavarian** [comment]
same here, even with newest version, e.g. with the podcast https://podcast.darknetdiaries.com
Waitin a few hours or refreshing creates a new directory (e.g. 2024-12-03_152-_ Stacc Attack-1) with the same podcast again, filling up the disk space over a few days

> 2024-12-04T21:28:01 ℹ️ - Downloading podcast episode: 152: Stacc Attack
> 2024-12-04T21:28:10 ❌ - File format not supported: Id3v2
> thread '<unnamed>' panicked at src/controllers/podcast_episode_controller.rs:188:14:
> called `Result::unwrap()` on an `Err` value: Conflict("File format not supported")
> 2024-12-04T21:28:26 ℹ️ - Refreshing podcast: Darknet Diaries
> 2024-12-04T21:28:26 ℹ️ - Downloading podcast episode: 152: Stacc Attack
> 2024-12-04T21:28:35 ❌ - File format not supported: Id3v2
> 2024-12-04T21:28:35 ❌ - Error downloading podcast episode: The following error occurred: File format not supported
> 2024-12-04T21:28:35 ℹ️ - Succesfully refreshed podcast.
> 2024-12-04T21:28:35 ℹ️ - Downloading podcast episode: 152: Stacc Attack
> 2024-12-04T21:28:43 ❌ - File format not supported: Id3v2
> 2024-12-04T21:28:43 ❌ - Error downloading podcast episode: The following error occurred: File format not supported

**Comment by morpheus302** [comment]
New user (unraid docker). 
`2024-12-09T21:54:16 ℹ️ - Downloading podcast episode: Trop de pizzas en cantine
2024-12-09T21:54:20 ❌ - File format not supported: Id3v2
2024-12-09T21:54:20 ❌ - Error downloading podcast episode: The following error occurred: File format not supported
2024-12-09T21:54:20 ℹ️ - Downloading podcast episode: Barnierthon
2024-12-09T21:54:24 ❌ - File format not supported: Id3v2
2024-12-09T21:54:24 ❌ - Error downloading podcast episode: The following error occurred: File format not supported
2024-12-09T21:54:24 ℹ️ - Downloading podcast episode: Monsieur Plutôt`

**Comment by SamTV12345** [comment]
Wait. So the podcast downloads and it downloads again because the id3 tag is buggy. It must be a recent dependency upgrade. I'll fix this tomorrow.

**Comment by Patriot2407** [comment]
Can we just ignore the tag? If we have .mp3 file and thumbnail, can't we just ignore all other files/tags and mark it downloaded in podfetch interface?

**Comment by SamTV12345** [comment]
I pushed a new version. It contains a bunch of improvements and it doesn't bubble the errors if the tagging goes wrong. I have no idea. It definetely worked flawlessly before and it was tested back then. I also went back a few versions with that particular library and it still errors. I'll need to investigate but you can again download things without an issue

**Comment by Patriot2407** [comment]
I also verified that this specific issue of duplicated downloads is fixed. It does not detect existing files, but that is fine, i guess I can delete all existing files and redownload them all, at least the server shows them as downloaded now. Thanks.
