### ISSUE TITLE
Colon replacement - incorrect details

### ISSUE THREAD

**Issue by Patriot2407** [SamTV12345/PodFetch#1019]
### Additional context

![Screenshot_2024-11-21_07-59-29](https://github.com/user-attachments/assets/9ddbb75a-7c31-47dc-8ccb-a2458980c253)
See above screenshot. I wonder if there was supposed to be an automatic update setting added, and the colon replacement detail was missed or something.
Verified this on 2 separate instances that have latest docker pull.

**Comment by Patriot2407** [comment]
Just pulled latest version, and this issue still occurs.

System information reports I'm on the below version:
v4.7.1-d195f456 (HEAD)

**Comment by SamTV12345** [comment]
Sorry I didn't match all translations. It should be fixed in the latest version

**Comment by Patriot2407** [comment]
this is now fixed
