### ISSUE TITLE
Suggestions for navigating the interface more quickly

### ISSUE THREAD

**Issue by uGeek** [SamTV12345/PodFetch#102]
### Clear and concise description of the problem

Navigate through the interface menus to listen to podcasts or subscribe, unsubscribe,... when you have many subscriptions can become complicated. Here are some personal suggestions that I have missed when using PodFetch.

### Suggested solution

 - In the podcast section, to quickly access the podcast we want to listen to, have the ability to filter by title, sort by title, and sort by latest publication.
- In the podcast section, when we access the desired podcast, have the ability to unsubscribe.
- In the Settings section, filter by podcast title to be able to unsubscribe.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by SamTV12345** [comment]
Thanks for the issue. Is the term subscribe similar to starring a podcast? What would be the difference? I agree towards filtering by these fields in the podcast view would be a lot more helpful.

**Comment by uGeek** [comment]
For example, an icon here to unsubscribe from the podcast
![image](https://user-images.githubusercontent.com/27757712/235956052-4e91c1c3-ec9b-4a21-8747-108788f844a4.png)

**Comment by uGeek** [comment]
Here there could be a box to enter the title of the podcast and filter among all, and there could also be the option to sort by the latest published podcast, alphabetical order of the title...

![image](https://user-images.githubusercontent.com/27757712/235956680-32426a33-0173-46b5-b30a-a7dab701b7b8.png)

**Comment by uGeek** [comment]
Sorry, I understood that the search I did was done by the browser and not that it sent the instruction to PodFetch. Anyway, I still think that being able to sort the podcasts in the podcast section is an ideal option. Currently it sorts them as you subscribe to podcasts and if you want to search for a specific podcast, the fastest use would be to put the title of the podcast and have PodFetch filter among all of them in a fast and light way, then you enter inside that podcast and look for the episode you want to listen to.

![image](https://user-images.githubusercontent.com/27757712/236018657-037d1ee8-9425-42af-9515-0032ed4d349b.png)

Something similar to what FlatNotes has.

**Comment by uGeek** [comment]
> What do you mean with filtering done from the service? The search term is sent to the backend and evaluated there. I just added a mobile tab so people can also use the search function on mobile. I'll add the rest of the required search functionality in an extra pr.

In the mobile version when you click on the menu options like Homepage, podcast, .... the section does not open, it is necessary to press the menu option and then press the 3 stripes on the top left to open that section. Is it not possible that when you click on a menu option it opens directly? using only one click

**Comment by SamTV12345** [comment]
Should be easy to switch.

**Comment by uGeek** [comment]
Theoretically in the Timeline section the episodes appear ordered by order of publication and from what I have been testing, only if they are marked as favorites, is that so? It is good to have that section, but in the podcast section, it would be nice to have all the podcasts ordered by publication. I comment on it because it took me days to understand that it worked like this, since practically all podcast applications, the podcast episodes come out published by order of publication. There is another problem, I have the docker and in 24h the podcasts have not been updated. I give it to the update symbol and it updates perfectly. Also, looking at the logs I see that it updates correctly. A suggestion on my part would be to also add the option that by means of a command, update the podcasts. This would allow me to run it on my server with cron every so often, in case the - POLLING_INTERVAL=60 fails

Perhaps there may be someone who does not want it to be updated and that it is updated only when the user launches the command or updates manually in the podcast section.

**Comment by SamTV12345** [comment]
Could you please try the dev tag and check if the sorting is persisted and working correctly.

**Comment by uGeek** [comment]
> Could you please try the dev tag and check if the sorting is persisted and working correctly.

It works perfect! Great job! This part of the code can also be applied to display and sort the latest episodes of all podcasts as well. Similar to timeline.


by the way, the codecs problem... it is possible to solve it

**Comment by travisterrell** [comment]
> For example, an icon here to unsubscribe from the podcast ![image](https://user-images.githubusercontent.com/27757712/235956052-4e91c1c3-ec9b-4a21-8747-108788f844a4.png)

@uGeek Apparently I'm dumb, because I cannot find an unsubscribe button anywhere in the UI or documentation. Surely you don't have to remove it from the db manually? (I know this is a closed issue, but hate to make a new one just to solve my misunderstanding.) Thanks in advance.
