### ISSUE TITLE
podcasts not downloading

### ISSUE THREAD

**Issue by Dylon0107** [SamTV12345/PodFetch#1020]
### Describe the bug

podcasts are not downloading to /mnt/user/data/media/podcasts/ neither auto nor manually.

### Reproduction

set up template, try to download podcast, check folder is empty.

### System Info

```Shell
ASUSTeK COMPUTER INC. PRIME Z790-V AX , Version Rev 1.xx

12th Gen Intel® Core™ i9-12900K @ 4900 MHz

 32 GiB DDR5

that command doesn't work on unraid so i listed specs.

unsure for the package manager as i used the unraid app.
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
The main problem is mostly that the directory permissions aren't set properly. The user in the container needs to have access to the folder mapped through the volume

**Comment by SamTV12345** [comment]
You could try again. We had an issue with the id3 tagger that produced a lot of errors and stopped downloading podcasts
