### ISSUE TITLE
Issues importing OPML files that have repeated podcasts. The import breaks.

### ISSUE THREAD

**Issue by uGeek** [SamTV12345/PodFetch#103]
### Describe the bug

There are podcasts that are on different platforms, therefore they have different feeds, but the name is the same. When I import an OPML file, the importation stops and gets stuck. If there are 200 subscriptions in the file and the numbers 7 and 8 are the same podcast with the same title but a different feed URL, it stops and doesn't continue importing the rest of the feeds.

It seems to be a problem where something breaks when creating the database and the title matches. In this case, it would be interesting to import repeated podcasts with different feeds and if there is any problem of this type, skip it and continue importing the rest of the feeds if they are not added.

### Reproduction

-

### System Info

```Shell
linux, firefox, brave
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Could you please add a sample opml that contains two entries - both have the same name but different rssfeeds.

**Comment by uGeek** [comment]
Ex:

Try importing this file and you will see that when it reaches the podcast Applelianos, since the title is duplicated, it breaks. I had a file with about 6 podcasts duplicated by title and it always broke. I have been manually deleting them to test and that was the reason.

```
<opml version="2.0">
<head>
<title>AntennaPod Subscriptions</title>
<dateCreated>03 May 23 18:32:23 +0200</dateCreated>
</head>
<body>
<outline text="#SoyCopywriter" title="#SoyCopywriter" type="rss" xmlUrl="https://soycopywriter.libsyn.com/rss" htmlUrl="https://soycopywriter.com"/>
<outline text="3.0" title="3.0" type="rss" xmlUrl="http://api.rtve.es/api/programas/59470/audios.rss" htmlUrl="https://www.rtve.es/play/audios/30/"/>
<outline text="5.0" title="5.0" type="rss" xmlUrl="http://api.rtve.es/api/programas/1872/audios.rss" htmlUrl="https://www.rtve.es/play/audios/50/"/>
<outline text="Alimento y salud" title="Alimento y salud" type="rss" xmlUrl="http://www.rtve.es/api/programas/1881/audios.rss" htmlUrl="https://www.rtve.es/play/audios/alimento-y-salud/"/>
<outline text="Apple Coding" title="Apple Coding" type="rss" xmlUrl="https://cuonda.com/apple-coding/feed" htmlUrl=""/>
<outline text="Applelianos" title="Applelianos" type="rss" xmlUrl="https://applelianos.podbean.com/feed.xml" htmlUrl="http://www.ivoox.com/podcast-applelianos_sq_f1170563_1.html"/>
<outline text="Applelianos" title="Applelianos" type="rss" xmlUrl="https://www.ivoox.com/podcast-applelianos_fg_f1170563_filtro_1.xml" htmlUrl="http://www.ivoox.com/podcast-applelianos_sq_f1170563_1.html"/>
<outline text="Aprendiendo GTD y productividad" title="Aprendiendo GTD y productividad" type="rss" xmlUrl="https://www.ivoox.com/aprendiendo-gtd-podcast_fg_f1286811_filtro_1.xml" htmlUrl="http://www.ivoox.com/podcast-aprendiendo-gtd-productividad_sq_f1286811_1.html"/>
<outline text="Órbita Laika. El podcast" title="Órbita Laika. El podcast" type="rss" xmlUrl="https://api.rtve.es/api/adapter/programas/146030/audios.rss" htmlUrl="https://www.rtve.es/play/audios/orbita-laika-el-podcast/"/>
</body>
</opml>
```
