### ISSUE TITLE
Playback fails in some formats

### ISSUE THREAD

**Issue by uGeek** [SamTV12345/PodFetch#105]
### Describe the bug

The audio player fails depending on the codec. For example, the podcast from http://www.rtve.es/api/programas/1881/audios.rss which is from RTVE, Spanish public television and radio, fails and does not play it. I have a script that converts youtube videos to mp3 audio with youtube-dl, then I convert them into a podcast with feed and it still doesn’t play them. I have to select the download option to listen to it.

### Reproduction

-

### System Info

```Shell
linux,browsers
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
The problem is on their end. They don't allow streaming of a podcast from their servers. I do a streaming request from the backend to their servers. Servers can deny this and return in that case a bad request signalizing that they don't support this. In that case you can only download it from their servers first because they can't deny that.

**Comment by SamTV12345** [comment]
I fixed that. The only big concern could be that you do a direct request from your phone to the podcast Hoster. So they know your IP address.

**Comment by uGeek** [comment]
Now to be able to reproduce it I had to do it like this, hit download and from the browser to direct playback

**Comment by SamTV12345** [comment]
Which image do you use? Arm64/Amd64?

**Comment by uGeek** [comment]
> Which image do you use? Arm64/Amd64?

ARM64 on a Raspberry Pi 4 with Manjaro

**Comment by uGeek** [comment]
![image](https://user-images.githubusercontent.com/27757712/236632537-d9605f41-77df-469c-8ea7-c83fe1ada3c7.png)

I don't know if it's the ARM64 version but I get many errors.
- When I maximize the player, the podcast episode image is not displayed. In minimized yes
- In each podcast to see the feeds generated by the podfetch, they fail

![image](https://user-images.githubusercontent.com/27757712/236632576-ee95e681-7a3d-43dc-ab3e-ea32915bd2ff.png)

**Comment by SamTV12345** [comment]
Weird. I can view this podcast. How did you add it? Via RSS or iTunes?

**Comment by uGeek** [comment]
rss, but it happens with absolutely all podcasts. No feed is generated correctly.

I just saw the update to sort by published podcast etc...(It's fantastic!!!)  but it only works on AMD64, on ARM64 it doesn't download the latest image. I am doing tests with the 2 architectures

**Comment by uGeek** [comment]
The local feed thing is an ARM64 problem, I just confirmed it. Although I am comparing the latest AMD64 image from 2 hours ago samuel19982/podfetch:latest 50.4MB to the ARM64 image 2 days ago samuel19982/podfetch:latest 46.6MB

In this latest version of docker for AMD64 it works perfect

**Comment by uGeek** [comment]
The problem of the images of the episode in the player when maximizing is not seen on ARM64 or AMD64

**Comment by SamTV12345** [comment]
Does it work now again?

**Comment by uGeek** [comment]
- Fixed the podcast image in amd64.
- The reproduction in streming, does not work depending on the codec neither in arm64 nor amd64

Normally the image is not downloaded for arm64?

**Comment by uGeek** [comment]
I have put the dev version for arm64 and the filtering works for me, but it is not updated to the latest. It would be nice if when you sort the podcast list, the last chosen order is saved

**Comment by SamTV12345** [comment]
👍🏻 Makes sense. I'll open up an issue.
