### ISSUE TITLE
Force redownload of single episodes

### ISSUE THREAD

**Issue by Patriot2407** [SamTV12345/PodFetch#1056]
### Describe the bug

The file for a couple episodes were deleted off the disk, when I try to click the delete red trash can, nothing happens and log just says the below
![Screenshot_2024-12-10_20-53-03](https://github.com/user-attachments/assets/43563d7a-30ed-4591-b258-91262cc40afc)

### Reproduction

Download episode, delete from disk, then try to delete from podfetch interface

### System Info

```Shell
Unraid docker
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Patriot2407** [comment]
The episode will not download, and there is no way to force it to download again. I really do not want to remove the podcast and re-add it all over again, is there anyway to delete single files that show as downloaded?

**Comment by SamTV12345** [comment]
I just fixed that issue. It was always checking if the file is there but throw an error if it is not. Now it just ignores that the file is not there anymore and unmarks the file as not being downloaded. Once I reworked the architecture I could think of a rescan button on top of the podcast to check if the files are still there.

**Comment by SamTV12345** [comment]
Feel free to check if the latest version that should be available in 10 minutes or so fixed your issues

**Comment by Patriot2407** [comment]
Fixed! Thank you so much for your timely response and fix!
