### ISSUE TITLE
Login fails when the password is too complex

### ISSUE THREAD

**Issue by update-freak** [SamTV12345/PodFetch#1059]
### Describe the bug

I created a docker container with the following docker compose

```
services:
podfetch:
image: samuel19982/podfetch:latest
container_name: PodFetch
user: 1026:100
ports:
- 4135:8000
volumes:
- /volume1/docker/podfetch/podcasts:/app/podcasts:rw
- /volume1/docker/podfetch/db:/app/db:rw
environment:
- POLLING_INTERVAL=300
- SERVER_URL=https://podfetch.beispiel.dynv6.net/
- DATABASE_URL=sqlite:///app/db/podcast.db
- BASIC_AUTH=true
- USERNAME=Felix
- PASSWORD=L#xmUgqw$Wi9&F@H
- GPODDER_INTEGRATION_ENABLED=true
restart: unless-stopped
```

When I try to login I got this message:
![bild](https://github.com/user-attachments/assets/46a595ef-66af-4b12-b192-0987a1a26eda)

Then I found out that e.g. this password d34gtfcw4g2fv was ok.

### Reproduction

Use as login-password L#xmUgqw$Wi9&F@H in the docker compose

### System Info

```Shell
Synology NAS DSM 7.2 with Docker
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
> L#xmUgqw$Wi9&F@H

Oh that is actually an issue with Docker compose. Docker hates $ variables. Every time your password should contain a $ you need to write two $ . So the password is actually L#xmUgqw$$Wi9&F@H in your Docker Compose

**Comment by update-freak** [comment]
Ah ok, good to know. Thanks for clarification.
Then I will close this ticket. (Maybe add a remark in the docu that other users did not have this problem)
