### ISSUE TITLE
Podcasts with long names - Star symbol is pushed out of square

### ISSUE THREAD

**Issue by quartzbear** [SamTV12345/PodFetch#115]
### Describe the bug

<img width="155" alt="Screenshot 2023-05-07 180548" src="https://user-images.githubusercontent.com/33700415/236685696-c3d58a6d-3b41-4113-b208-96191b99361f.png">

Star leaves the area of the "podcast square" when name is too long.
<img width="150" alt="Screenshot 2023-05-07 180930" src="https://user-images.githubusercontent.com/33700415/236685860-9f52d9d0-62d2-4007-b1dd-0b939f6f6b58.png">

### Reproduction

Add any podcast with a longer name, such as Freakonomics Radio

### System Info

```Shell
Home Assitant 2023.5.2, running on Lubuntu via Virtualbox.
Firefox 112.0.2  browser
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by quartzbear** [comment]
![image](https://user-images.githubusercontent.com/33700415/236687580-2c82e32d-daa7-4197-b3b4-4cec4fb00626.png)

This is on Windows. 
There seems to be other problems with the home assistant installation (no artwork, no ability to select podcasts). Those might not be related to Podfetch.

**Comment by SamTV12345** [comment]
Thanks. Just out of curiosity: Is that the home assistant plugin you are currently creating? I'll fix this ASAP.

**Comment by quartzbear** [comment]
This isn't the plugin, I didn't really start it yet. 
I installed the Podfetch Docker Image with the Portainer addon to Home Assistant.
