### ISSUE TITLE
Create a new section like the timeline, but with all the podcasts to which we are subscribed

### ISSUE THREAD

**Issue by uGeek** [SamTV12345/PodFetch#116]
### Clear and concise description of the problem

It is still difficult to access recently released episodes. Although the filter option has been added, which works great, waiting for the last selected order option to be saved, it is difficult to see the latest episodes published in the rest of the podcasts that are not favorites.

### Suggested solution

Create a new section where the podcast episodes appear in order of publication. The last podcasts would be the first. Something similar to the timeline section but with all the podcasts.

### Alternative

I miss that the timeline option does not appear more days, I understand that it has been limited so that the page does not become heavy, in this case it could generate several podcast numbers in the section and add, for example, a week with the latest published episodes, ordered by date - time of publication (as in timeline) and separated by days up to the last week (as in timeline)

### Additional context

![image](https://user-images.githubusercontent.com/27757712/236693908-a47221e6-dcf5-42b9-8d78-7f9239282b7e.png)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by SamTV12345** [comment]
Now that the other problem is fixed I can start with this one. Could you give an example of what exactly should be displayed? Maybe draw it.

**Comment by uGeek** [comment]
a minor problem that I have seen, is that when playing in streaming in the last listened section, they are not saved as the last plays, only those that have been downloaded

**Comment by uGeek** [comment]
> Now that the other problem is fixed I can start with this one. Could you give an example of what exactly should be displayed? Maybe draw it.



> Now that the other problem is fixed I can start with this one. Could you give an example of what exactly should be displayed? Maybe draw it.

In the last update I see that it starts to work

**Comment by SamTV12345** [comment]
Merged in #126 . Is there anything else I can do in this issue?

**Comment by uGeek** [comment]
With the last update of the dev version it does not work

```
2023-05-10T18:41:30 [INFO] - Settings already present
2023-05-10T18:41:30 [INFO] - Starting with the following environment variables:
2023-05-10T18:41:30 [INFO] - starting 4 workers
2023-05-10T18:41:30 [INFO] - Actix runtime found; starting in Actix runtime
2023-05-10T18:41:40 [ERROR] - stream error: Request parse error: Invalid Header provided
2023-05-10T18:41:40 [ERROR] - stream error: Request parse error: Invalid Header provided
2023-05-10T18:41:40 [ERROR] - stream error: Request parse error: Invalid Header provided
2023-05-10T18:41:40 [ERROR] - stream error: Request parse error: Invalid Header provided
2023-05-10T18:41:41 [ERROR] - stream error: Request parse error: Invalid Header provided
2023-05-10T18:41:41 [ERROR] - stream error: Request parse error: Invalid Header provided
2023-05-10T18:41:41 [ERROR] - stream error: Request parse error: Invalid Header provided
```

**Comment by SamTV12345** [comment]
What about :latest?

**Comment by uGeek** [comment]
6 days ago      samuel19982/podfetch:latest                  46.6MB

The ARM64 version, I don't know what happens that it hasn't been downloaded for days and I've tried it on 2 Raspberry and a vps.

I have deleted the old image and re-download the image from 6 days ago.

The dev version, as I have ouroboros running permanently to do the tests, it updates without problems

**Comment by uGeek** [comment]
In amd64 if updated
5 hours ago    samuel19982/podfetch:latest     49.3MB

**Comment by SamTV12345** [comment]
Weird. The latest version was published today.

**Comment by uGeek** [comment]
It's super strange, because the version of if is updated, instead the latest version, not

**Comment by uGeek** [comment]
> a minor problem that I have seen, is that when playing in streaming in the last listened section, they are not saved as the last plays, only those that have been downloaded

the dev version, they already work for me.
Streaming reproductions still do not appear in this section

**Comment by uGeek** [comment]
> ### Clear and concise description of the problem
> It is still difficult to access recently released episodes. Although the filter option has been added, which works great, waiting for the last selected order option to be saved, it is difficult to see the latest episodes published in the rest of the podcasts that are not favorites.
> 
> ### Suggested solution
> Create a new section where the podcast episodes appear in order of publication. The last podcasts would be the first. Something similar to the timeline section but with all the podcasts.
> 
> ### Alternative
> I miss that the timeline option does not appear more days, I understand that it has been limited so that the page does not become heavy, in this case it could generate several podcast numbers in the section and add, for example, a week with the latest published episodes, ordered by date - time of publication (as in timeline) and separated by days up to the last week (as in timeline)
> 
> ### Additional context
> ![image](https://user-images.githubusercontent.com/27757712/236693908-a47221e6-dcf5-42b9-8d78-7f9239282b7e.png)
> 
> ### Validations
> * [x]  Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
> * [x]  Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
> * [x]  Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

There is no section where the episodes appear ordered by publication order, right?

**Comment by SamTV12345** [comment]
I don't really understand the issue as mentioned before. There is the Timeline which shows episodes by publication order.

**Comment by uGeek** [comment]
Currently there is a section on the menu, which is Timeline and it is great. I miss that few episodes appear, I would like more to appear. In this section only the channels that are marked as favorites appear. My proposal is that there be another section in the menu, that is similar to Timeline but that the latest published episodes appear, but of all the podcasts to which we are subscribed. Same as the Timeline, but of all the podcasts.

If you don't want to overload the current page with so many episodes, you can create other pages by accessing from the bottom of the page where there is the next option or page number.

**Comment by uGeek** [comment]
> Weird. The latest version was published today.

Today, finally, the latest version for ARM64 has been downloaded

**Comment by SamTV12345** [comment]
> Currently there is a section on the menu, which is Timeline and it is great. I miss that few episodes appear, I would like more to appear. In this section only the channels that are marked as favorites appear. My proposal is that there be another section in the menu, that is similar to Timeline but that the latest published episodes appear, but of all the podcasts to which we are subscribed. Same as the Timeline, but of all the podcasts.
> 
> 
> 
> If you don't want to overload the current page with so many episodes, you can create other pages by accessing from the bottom of the page where there is the next option or page number. 
> 
> 
> 
> 
> 
> 

Now I understand what you meant.

**Comment by SamTV12345** [comment]
> > Weird. The latest version was published today.
> 
> 
> 
> Today, finally, the latest version for ARM64 has been downloaded

Nice. I made the build process more robust and could finally readd RPi 1,2,3 support.

**Comment by uGeek** [comment]
> > > Weird. The latest version was published today.
> > 
> > 
> > Today, finally, the latest version for ARM64 has been downloaded
> 
> Nice. I made the build process more robust and could finally readd RPi 1,2,3 support.

Thank you so much!
