### ISSUE TITLE
streaming playback

### ISSUE THREAD

**Issue by uGeek** [SamTV12345/PodFetch#123]
### Describe the bug

when the audios are downloaded locally they are reproduced without any kind of problem. On the other hand, when there is a direct reproduction with the server, depending on the audio format, it is not reproduced.

One of the advantages of having the server is being able to play the audios directly and not need to download them.

### Reproduction

_

### System Info

```Shell
linux,brave,firefox
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Could you give me an example of a podcast that isn't played correctly. Modern browsers normally support the gist of codecs.

**Comment by uGeek** [comment]
> Could you give me an example of a podcast that isn't played correctly. Modern browsers normally support the gist of codecs.

These are some of the podcasts that do not allow streaming, but there are many more
- https://feedpress.me/sospechososhabituales
- https://cuonda.com/binarios/feed
- https://boluda.com/feed/
- https://podcast.mixx.io/index.rss
- https://fitnessrevolucionario.com/feed/podcast

They are well-known podcasts and have many listeners

**Comment by uGeek** [comment]
I'm testing the latest update dev. All the audios that I am playing work perfectly. Spectacular work you are doing.


I keep trying...
