### ISSUE TITLE
Podcast updates don't work

### ISSUE THREAD

**Issue by uGeek** [SamTV12345/PodFetch#137]
### Describe the bug

With the option  POLLING_INTERVAL=60 Podcasts are not updated.

You could also add in the CLI option a command to update with cron. 

### Reproduction

-

### System Info

```Shell
Linux, Android, Firefox, brave
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Sorry. The documentation deviated from the configuration in the app. It has always been 300 but I never updated POLLING_INTERVAL in the docs from 60 minutes.

**Comment by SamTV12345** [comment]
The other error is also fixed. The RSS feed is incorrectly configured. You have to tell the server which client you are. Otherwise it returns html with a bad request 400.
