### ISSUE TITLE
Without downloaded episodes rss link broken

### ISSUE THREAD

**Issue by APraxx** [SamTV12345/PodFetch#146]
### Describe the bug

Hi,

i noticed that if by some means there are no downloaded episodes in the podcast the rss link is broken.
it's working again if there is at least one episode

this happened after adding the podcast and the download got interrupted 

ps.: is there a possibility to show and stream not downloaded episodes via rss?

### Reproduction

have a podcast without downloaded episodes - click rss link

### System Info

```Shell
ubuntu linux - docker compose with postgres
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
How did you manage to have no downloaded podcast episodes in a podcast?

**Comment by APraxx** [comment]
as said before the download got somehow interrupted. i did an opml import of a few podcasts and the last one got borked. reason not clear.

after i clicked "download to server" in the dialog everything was like the other ones
