### ISSUE TITLE
RSS: No Image for Channel

### ISSUE THREAD

**Issue by APraxx** [SamTV12345/PodFetch#148]
### Describe the bug

Hello,

not really a Bug but it seems the RSS feed misses the Image for the Podcast/Channel ([\<itunes:image\>](https://help.apple.com/itc/podcasts_connect/#/itcb54353390) ?) which is present in the Web-interface.

ps.: i really like how promptly you handle things. cheers

### Reproduction

rss feed inside \<channel\> before the \<items\>

### System Info

```Shell
docker dev postgres
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Good idea. I'll add this tomorrow.

**Comment by SamTV12345** [comment]
You're welcome. Enjoy the fixed RSS feed.
