### ISSUE TITLE
Delete podcast with files not working

### ISSUE THREAD

**Issue by APraxx** [SamTV12345/PodFetch#157]
### Describe the bug

It seems this doesn't work currently

Here is a rather uneventful log output
```
 Debug file located at /home/rust/src/target/x86_64-unknown-linux-musl/release/build/podfetch-c0dcee25b680277c/out/built.rs
 Connecting to postgresql://podfetchuser:pwd@postgres-pf/podfetch
 
   ____           _ _____    _       _
  |  _ \ ___   __| |  ___|__| |_ ___| |__
  | |_) / _ \ / _` | |_ / _ \ __/ __| '_ \
  |  __/ (_) | (_| |  _|  __/ || (__| | | |
  |_|   \___/ \__,_|_|  \___|\__\___|_| |_|
 
         
 Connecting to postgresql://podfetchuser:pwd@postgres-pf/podfetch
 Public server url: https://podfetch.mysite.com/
 Polling interval for new episodes: 3600 minutes
 GPodder integration enabled: true
 Database url is set to: postgresql://podfetchuser:pwd@postgres-pf/podfetch
 Podindex API key&secret configured: true
 2023-05-28T19:29:27 [INFO] - Settings already present
 2023-05-28T19:29:27 [INFO] - Starting with the following environment variables:
 2023-05-28T19:29:27 [INFO] - starting 4 workers
 2023-05-28T19:29:27 [INFO] - Actix runtime found; starting in Actix runtime
 Connecting to postgresql://podfetchuser:pwd@postgres-pf/podfetch
 thread 'actix-rt|system:0|arbiter:2' panicked at 'Error deleting podcast directory: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/service/file_service.rs:119:70
 stack backtrace:
    0:     0x7fc4777d80de - <unknown>
    1:     0x7fc47709ecde - <unknown>
    2:     0x7fc4777d46c5 - <unknown>
    3:     0x7fc4777d7eb5 - <unknown>
    4:     0x7fc4777d961f - <unknown>
    5:     0x7fc4777d9394 - <unknown>
    6:     0x7fc4777d9b4f - <unknown>
    7:     0x7fc4777d9a56 - <unknown>
    8:     0x7fc4777d85d6 - <unknown>
    9:     0x7fc4777d9792 - <unknown>
   10:     0x7fc476f4eeb3 - <unknown>
   11:     0x7fc476f4f363 - <unknown>
   12:     0x7fc477388a83 - <unknown>
   13:     0x7fc4772058e7 - <unknown>
   14:     0x7fc477200a18 - <unknown>
   15:     0x7fc4773ea33e - <unknown>
   16:     0x7fc4771fdd96 - <unknown>
   17:     0x7fc4771fda58 - <unknown>
   18:     0x7fc4771fda58 - <unknown>
   19:     0x7fc477315c0d - <unknown>
   20:     0x7fc4773a63eb - <unknown>
   21:     0x7fc47754f38e - <unknown>
   22:     0x7fc4775573e6 - <unknown>
   23:     0x7fc4772b9b94 - <unknown>
   24:     0x7fc4773cc692 - <unknown>
   25:     0x7fc477465380 - <unknown>
   26:     0x7fc4771e78ea - <unknown>
   27:     0x7fc477824d31 - <unknown>
   28:     0x7fc476ffe3ec - <unknown>
   29:     0x7fc47700b6b2 - <unknown>
   30:     0x7fc476fe64f1 - <unknown>
   31:     0x7fc477003adc - <unknown>
   32:     0x7fc476ff994f - <unknown>
   33:     0x7fc4777dd455 - <unknown>
```

if i can provide any additional stuff please say so.
i'll look into debugging it directly without docker involved

### Reproduction

Add a Podcast like "This Podcast Will Kill You" and try deleting it with files

### System Info

```Shell
Version v3.5.0-e428db50 (HEAD) Commit v3.5.0-e428db50 (HEAD)
Build date Sun, 28 May 2023 14:37:51 +0000
Branch e428db50
OS linux
ENV docker: dev-postgres with bindmount
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Did #164  solve the problem?

**Comment by APraxx** [comment]
i'm currently not sure on which branch the docker image samuel19982/podfetch:dev-postgres is.
because i've got ui changes and this would be the wrong branch.

so in my test with this current samuel19982/podfetch:dev-postgres image it doesn't work.

info says this:
Version Info v3.5.0-e0d3fbbb (HEAD) Commit v3.5.0-e0d3fbbb (HEAD)
Build date Mon, 29 May 2023 14:23:15 +0000

ps: info is not available in the new ui ;) only via url
pps: will try to setup a dev environment so that i don't mix in docker bugs

**Comment by SamTV12345** [comment]
Oh sorry. It should be on the Postgres tag. The ui branch is behind the main branch that is why it doesn't have the working fix in it. Thanks for testing PodFetch.

**Comment by APraxx** [comment]
Np, this seems to be fixed on the postges tag
