### ISSUE TITLE
Request: Fetch password protected podcasts

### ISSUE THREAD

**Issue by d3545t3r** [SamTV12345/PodFetch#166]
### Describe the bug

I host a few podcast episodes, which are accessible through their own subdomain and are accessible through

BasicAuthorization via [Nginx HTTP Basic Authentication](https://nginx.org/en/docs/http/ngx_http_auth_basic_module.html) 

With various podcast apps (AntennaPod, PodcastAddict, etc.) it is possible to pass username and password and include these episodes.

I have already tried to do this through

```
https://<USERNAME>:<PASSWORD>@<URL TO THE RSS FEED>
``` 
but it doesn't seem to work in Podfetch.

It would be nice if this could be implemented, even though I think it is a very special niche case.

### Reproduction

https://<USERNAME>:<PASSWORD>@<URL TO THE RSS FEED>

### System Info

```Shell
System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) arm ARMv7 Processor rev 5 (v7l)
    Memory: 156.01 MB / 999.02 MB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 19.9.0 - /usr/local/bin/node
    npm: 9.6.3 - /usr/local/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
I added it to the main branch. Could you try again?

**Comment by SamTV12345** [comment]
Could you give me  a guide on how to get started with a proxy with basic auth? I think I need to reproduce this locally to get a chance to implement this succesfully.

**Comment by d3545t3r** [comment]
Unfortunately I don't have time right now, but I'll set you up with a test setup this weekend so you can try out your changes.

I hope this will help you.

**Comment by d3545t3r** [comment]
Seems to work now. 
Thanks a lot. 
I can add my self hosted podcasts with

```
https://<USERNAME>:<PASSWORD>@<URL TO THE RSS FEED>
```

**Comment by SamTV12345** [comment]
Nice. Seems like I got every occasion where the podcast server reaches out to the RSS feed.
