### ISSUE TITLE
Images and podcast episodes missing

### ISSUE THREAD

**Issue by uGeek** [SamTV12345/PodFetch#168]
### Describe the bug

Since yesterday when the last update arrived, using the dev-postgres version, I can't see the images in the All subcriptions and Favorites sections. I can't enter the podcast to access the audios by clicking on them either, as the image doesn't appear. It is not possible to access the audios

### Reproduction

-

### System Info

```Shell
linux
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by uGeek** [comment]
I started from scratch with the podfetch:postgres version. I'm importing all the podcasts again and it does import the images.

**Comment by SamTV12345** [comment]
That's really weird. You didn't apply this line in your code  user: ${UID:-1000}:${GID:-1000}?

**Comment by SamTV12345** [comment]
Is this still the case or can we close this issue?

**Comment by uGeek** [comment]
> ¿Sigue siendo así o podemos cerrar este problema?

I have reinstalled again and so far everything is fine. Wait a few more versions, see how everything works.

**Comment by SamTV12345** [comment]
It is better to track postgres. The latest version also fixes that sorting problem.

**Comment by uGeek** [comment]
I know why the images are deleted.... Actually I was deleting them without realising it. 

As podcast downloading is enabled by default, when I import my opml file it takes extremely long. That's because as soon as you import a podcast, it downloads the image creating a folder with the podcast name and some episodes. If you import few podcasts nothing happens, but if it's like me that I'm importing 260, the import is very very slow, because it imports the episode and starts downloading image and audios. 

I think it's a mistake. By default it should not download the audios, at least in the import. I think it should be optional. As you can imagine it takes a long time and gives the feeling that something is wrong, as there are podcasts that have very large audios and the import stops until it is completely downloaded and then continues with the next one. 

Also think that in this first import you are downloading episodes that you have already listened to because they are old and in total, it takes up a lot of space.

After importing all the episodes, I deleted all the folders with the podcasts and inside were the images, when I restarted, the covers no longer appear. That was my mistake...

**Comment by uGeek** [comment]
Once installed, if you set it not to download the audios, the import of the podcast is very fast. I think this is a better option

**Comment by SamTV12345** [comment]
Yeah. Depending on compression level and length of an episode that can take a long time. An insert into the database is very fast.

**Comment by SamTV12345** [comment]
I guess so far there weren't any occurrences where the images would not load.
