### ISSUE TITLE
Auto-delete option

### ISSUE THREAD

**Issue by Thomas-O** [SamTV12345/PodFetch#17]
### Clear and concise description of the problem

If you forget to tidy up behind you, deleting episodes as you go, then PodFetch could soon accumulate GBs of auto-downloaded clutter.

### Suggested solution

What about an option to auto-delete downloaded episodes after a user-defined number of (10 - 100) days?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by SamTV12345** [comment]
Great idea. What would be your preference? Being able to configure this option via UI or as environment variable? If it is an environment variable you need to always login to the host system and edit the docker-compose file.

**Comment by Thomas-O** [comment]
> Great idea. What would be your preference? Being able to configure this option via UI or as environment variable? If it is an environment variable you need to always login to the host system and edit the docker-compose file.

I think the UI would be the better choice. For most users it would be easier and quicker to change or pause the auto-delete via the UI. Or just to quickly remind yourself of your selection.

And it would make the initial installation simpler and less likely to befuddle new users.  Also you might forget that you applied the setting during the install and be wondering why files keep vanishing.

**Comment by SamTV12345** [comment]
If you'd like to you can check out the latest release. It adds a redesign to the podcast page. I'll check out the issue this week. Maybe I can get it to work tomorrow.
