### ISSUE TITLE
Increase The number of episodes in The Timeline section.

### ISSUE THREAD

**Issue by uGeek** [SamTV12345/PodFetch#170]
### Clear and concise description of the problem

I subscribe to over three hundred podcasts and the site is getting too small for me.

### Suggested solution

Enable an option to select the maximum number of episodes to be displayed on the page. 

### Alternative

Currently, as far as I can see, it only allows 20 episodes. It would be nice to select between 20,40,60... Or add more pages of 20 in 20 podcasts if you think it can make the service too heavy.

### Additional context

-

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by SamTV12345** [comment]
There should be a lazy loading when scrolling down the timeline.

**Comment by uGeek** [comment]
That would be great. A very good idea. Scrolling down to infinity and have it go preloading....

**Comment by SamTV12345** [comment]
Did the page reloading work on your end? Do you have the latest image? If not I would need your podcast list so I can find out why infinite scrolling is not working on your end.

**Comment by uGeek** [comment]
> Did the page reloading work on your end? Do you have the latest image? If not I would need your podcast list so I can find out why infinite scrolling is not working on your end.

From the mobile it seemed that the favourites section, the previous version did. I have reinstalled because the images were not seen and it doesn't work.

The order of publication in the podcast section hasn't been working for about 2 weeks either.

**Comment by uGeek** [comment]
> I just reinstalled the postgres version from scratch and it does work with the favourite podcasts, but not with all the podcasts. Could you also apply it to all the podcasts?

He spoke of infinite displacement, when scrolling down the timeline.

**Comment by SamTV12345** [comment]
> I just reinstalled the postgres version from scratch and it does work with the favourite podcasts, but not with all the podcasts. Could you also apply it to all the podcasts?

What exactly do you mean? The timeline can be switched to all podcasts.

**Comment by uGeek** [comment]
I have continued testing. What happens is that when there are many Podcasts, it doesn't allow to load more episodes if you scroll down The page to load The Next old episodes. it previews as it has always done, with The limited number from The Beginning by Default. Enabling The Tab to show All published subscribed episodes, This option has never allowed me to get to The bottom of The page and continue loading episodes. it has Only worked with The favourites option But using a maximum of 2 Podcasts.

**Comment by SamTV12345** [comment]
Ah. I never had more than 2-3. With more there seems to be an issue in the counting. I'm working on a fix.

**Comment by SamTV12345** [comment]
> I have continued testing. What happens is that when there are many Podcasts, it doesn't allow to load more episodes if you scroll down The page to load The Next old episodes. it previews as it has always done, with The limited number from The Beginning by Default. Enabling The Tab to show All published subscribed episodes, This option has never allowed me to get to The bottom of The page and continue loading episodes. it has Only worked with The favourites option But using a maximum of 2 Podcasts.

Could you please try again on any of the :dev-postgres and :dev tags. It should work now with a variable number of podcasts.

**Comment by uGeek** [comment]
I have reinstalled the dev and normal version and both of them hang, even if I am not subscribed to any podcast when I restart.

![image](https://github.com/SamTV12345/PodFetch/assets/27757712/a037fee8-171b-4ef7-8905-74fa8c893594)

**Comment by SamTV12345** [comment]
Found the error. It's fixed now.

**Comment by SamTV12345** [comment]
Fixed the other error too. Now you can safely access the timeline.

**Comment by uGeek** [comment]
Great job!!!!!!! Now it works great and in my opinion, it's an excellent update as it allows you to view all the episodes in a graphical way in reverse publishing order and listen to them. Thank you so much for the effort. I have been updating all day waiting for the update. 

I have not commented, but I have subscribed to 265 podcasts and it works perfectly, no errors.


Thank you very much and great job again

**Comment by SamTV12345** [comment]
You're welcome. Enjoy your podcasts. I haven't ever tested that with 265 podcasts. Hope the app still runs stable.
