### ISSUE TITLE
Tooltips on settings

### ISSUE THREAD

**Issue by revilo951** [SamTV12345/PodFetch#174]
### Clear and concise description of the problem

Some settings functions aren't clear, eg auto-cleanup - what does this do?

### Suggested solution

A small description on hover with more infformation

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by SamTV12345** [comment]
Good idea. I'll do that once the new ui is out.

**Comment by SamTV12345** [comment]
Until then autocleanup means that older episodes than x days are deleted from the filesystem. This prevents the disk being full after some time and potentially crashing the system.

**Comment by revilo951** [comment]
OK, so if I want to use PodFetch as an archiving tool, to keep all my podcasts, I'll need to disable that. Good to know. :)
