### ISSUE TITLE
Track changed Podcast URLs

### ISSUE THREAD

**Issue by alexanderadam** [SamTV12345/PodFetch#175]
### Clear and concise description of the problem

This is just a followup from [this conversation](https://github.com/SamTV12345/PodFetch/discussions/141#discussioncomment-5994660).

Old URLs probably need to be tracked to avoid duplication.

### Suggested solution

So if a Podcast feed sends a `3xx` HTTP status code (i.e. `301` or `308`) the main feed URL might need to be replaced in the metadata.
Also avoid an endless loop while following redirects.

But Podcast clients might still send the old URLs (see also [this AntennaPod issue](https://github.com/AntennaPod/AntennaPod/issues/2214)).
Hence the old URL probably needs to be stored and associated with the new one. So that identification with the old _and_ new URL is possible without creating a duplicated subscription.

[ByteHamster provided some test URLs to reproduce this](https://github.com/SamTV12345/PodFetch/discussions/141#discussioncomment-6118222):

| Update type | Test URL |
|--------|--------|
| HTTP Redirect `308` | [URL](https://tools.bytehamster.com/podcast/redirect.php) |
| Updated URL in feed tag `itunes:new-feed-url` | [URL](https://tools.bytehamster.com/podcast/redirect2.php) | 

where `https://tools.bytehamster.com/podcast/redirect.php` will redirect to `https://tools.bytehamster.com/podcast/redirect.php?timestamp=16864…` (whatever the current timestamp is)

and `https://tools.bytehamster.com/podcast/redirect2.php` contains `itunes:new-feed-url` in markup which contains the new feed URL (see also [[this](https://podcasters.apple.com/support/837-change-the-rss-feed-url)](https://podcasters.apple.com/support/837-change-the-rss-feed-url)).

[From my naïve point of view it should be something like](https://github.com/SamTV12345/PodFetch/discussions/141#discussioncomment-6141526)

```ruby
# in the beginning it's feed_url = "https://tools.bytehamster.com/podcast/redirect.php"

# this is the first check on HTTP level
if [301, 308].include? response.code
  old_feed_urls << feed_url unless old_feed_urls.include? feed_url
  feed_url = response.url # https://tools.bytehamster.com/podcast/redirect.php?timestamp=16864…
end

# later when you do the parsing there could be another type of update by the data that you might find in the feed
if feed_xml.include? "itunes:new-feed-url"
  old_feed_urls << feed_url unless old_feed_urls.include? feed_url
  feed_url = feed_xml["itunes:new-feed-url"] # https://tools.bytehamster.com/podcast/redirect.php?timestamp=16864…
end
```

**PS:** [The item metadata (i.e. updated title) or url probably needs to be updated anyway on sync](https://github.com/SamTV12345/PodFetch/discussions/141#discussioncomment-6141719).

### Additional context

I'm not sure whether the proposed solution handles all the cases so it probably would make sense to check with some folks [at the AntennaPod issue](https://github.com/AntennaPod/AntennaPod/issues/2214) whether this would work?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by SamTV12345** [comment]
I need an example so I can track that and also test that it works in the end. Do you have a podcast that falls under this criteria?

**Comment by alexanderadam** [comment]
Unfortunately I deleted the duplicates manually recently.

But I just found another case that probably needs to be handled separately (if it is possible to handle this at all):

different URLs providing the same feed (i.e. [with www.](https://www.omnycontent.com/d/playlist/e73c998e-6e60-432f-8610-ae210140c5b1/a91018a4-ea4f-4130-bf55-ae270180c327/44710ecc-10bb-48d1-93c7-ae270180c33e/podcast.rss) and [without](https://omnycontent.com/d/playlist/e73c998e-6e60-432f-8610-ae210140c5b1/A91018A4-EA4F-4130-BF55-AE270180C327/44710ECC-10BB-48D1-93C7-AE270180C33E/podcast.rss))

**Comment by SamTV12345** [comment]
But who would add both with www. and without it?

**Comment by SamTV12345** [comment]
Seems like the other two are currently busy.

**Comment by alexanderadam** [comment]
> But who would add both with www. and without it?

I didn't add them manually via URL since I only used the AntennaPod search to add Posdcasts.
I'm not sure how it came to that state that I had both in the subscriptions to be honest.

**Comment by SamTV12345** [comment]
Let's continue here better so we don't annoy Gandalf with emails.

**Comment by SamTV12345** [comment]
I want to cry:  podlove-2019-06-18t22:35:12+00:00-aa1af25f574bbc2 Nice guid. If you update the podcast and reupload the podcast episodes this is presumably a new id.

**Comment by SamTV12345** [comment]
The first case is implemented. I'll handle the second case tomorrow.

**Comment by SamTV12345** [comment]
It now works on my end with the two versions. If you also want to test you can checkout the :dev or :dev-postgres tags.
