### ISSUE TITLE
unable to add user

### ISSUE THREAD

**Issue by d3545t3r** [SamTV12345/PodFetch#181]
### Describe the bug

I'm unable to create/add a user to podfetch (or maybe I'm trying it the wrong way).

How I tried it

```
docker run -it samuel19982/podfetch:dev-postgres ./podfetch users add
``` 

I get the following correct output

```
Debug file located at /home/rust/src/target/armv7-unknown-linux-musleabihf/release/build/podfetch-7807c2de0c7f333a/out/built.rs
Starting from command line
User management
Enter your username:
``` 

but as soon as I enter a username it errors out with

```
Connecting to sqlite://./db/podcast.db
thread 'tokio-runtime-worker' panicked at 'Error connecting to sqlite://./db/podcast.db with error missing "=" after "sqlite://./db/podcast.db" in connection info string
', src/config/dbconfig.rs:48:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtracethread 'main' panicked at 'TODO: panic message: JoinError::Panic(Id(3), ...)', src/main.rs:130:18
``` 

### Reproduction

docker run -it samuel19982/podfetch:dev-postgres ./podfetch users add

### System Info

```Shell
System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) arm ARMv7 Processor rev 5 (v7l)
    Memory: 275.34 MB / 999.02 MB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 19.9.0 - /usr/local/bin/node
    npm: 9.6.3 - /usr/local/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Thanks for the bug report. If you have a Postgres instance running you can execute `docker exec -it <your-container-name/container id> /app/podfetch users add`

You can get the id by executing `docker ps`

**Comment by d3545t3r** [comment]
worked perfectly.

thanks for your Help!

**Comment by SamTV12345** [comment]
You're welcome. I added the command to the docs so that other users won't be confused either. Thanks for pointing that out.
