### ISSUE TITLE
error when subscribing to a podcast

### ISSUE THREAD

**Issue by uGeek** [SamTV12345/PodFetch#203]
### Describe the bug

If you search iTunes for this podcast "El món a RAC1 - L'hora a hora", "El món a RAC1 - El perquè de tot plegat", ... all the podcasts of the RAC1 radio platform.

 it is not possible to subscribe, the message appears: You are not an admin or an uploader. 

It also does not allow importing from another opml client.

### Reproduction

-

### System Info

```Shell
linux, brave, android
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Weird. I can listen to the first one:

![image](https://github.com/SamTV12345/PodFetch/assets/40429738/fee499cf-0237-4cb2-ae19-3e33e6418e78)

**Comment by SamTV12345** [comment]
Do you see any logs in the terminal?

**Comment by uGeek** [comment]
![imagen](https://github.com/SamTV12345/PodFetch/assets/27757712/83104951-a336-4e60-97e0-e0900d27723a)


When I try to subscribe, I get this message in the web interface
It only happens to me with this podcast

**Comment by uGeek** [comment]
It seems to be under a different name: Podcast already exists

```
podfetch-postgres | 2023-07-08T19:52:26.114609553Z 2023-07-08 19:52:26.114 UTC [27] LOG:  checkpoint complete: wrote 23 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=2.215 s, sync=0.006 s, total=2.233 s; sync files=9, longest=0.005 s, average=0.001 s; distance=121 kB, estimate=1935 kB
podfetch    | 2023-07-08T19:53:53.310032949Z thread 'actix-rt|system:0|arbiter:2' panicked at 'Error handling insert of podcast: PodFetchError { name: "Podcast already exists", status_code: 400 }', src/controllers/podcast_controller.rs:264:22
```

**Comment by uGeek** [comment]
Yes, I had a duplicate subscription. 

It could appear that "you are already subscribed to this podcast". I had not realized that it came from the import and had imported the same feed 3 times, that had probocado that if the podcast was, but not the image of the podcast.

When I unsubscribe manually and import from itunes, everything perfect and with image included.

Thank you very much

**Comment by SamTV12345** [comment]
Sure no problem. Nice that this is fixed for now. Feel free to close this issue if everything is resolved 😄

**Comment by uGeek** [comment]
Is it possible to display the duplicate feed?

**Comment by SamTV12345** [comment]
Perform a `docker exec -it <your-container-id> /app/podfetch podcasts list`. This will print a list of all Podcasts stored in the database.

**Comment by uGeek** [comment]
Great command. Now I know the podcast and its feed. Thank you so much


There is another option to be able to update the feeds by the cli command


Is there any documentation where all the available commands are? In the help with the help command this command does not appear

**Comment by SamTV12345** [comment]
I added this page so people can get the latest commands without me constantly updating or forgetting xD to update the CLI commands. https://github.com/SamTV12345/PodFetch/blob/main/docs/CLI.md

**Comment by uGeek** [comment]
Thank you very much

**Comment by SamTV12345** [comment]
No problem. I'm currently reworking the feedback system so you will be able to see that the Podcast already exists.
