### ISSUE TITLE
Percent sign '%' isn't encoded in URLs

### ISSUE THREAD

**Issue by mgoral** [SamTV12345/PodFetch#206]
### Describe the bug

I subscribe to "99% Invisible" podcast (oh boy, this one gives me headaches ;)). Unfortunately, PodFetch doesn't encode "%" character in URLs to its cover image with "%25" which results in failing of displaying the cover. (HTTP 400 - Bad Request).

So for example, the URL to the cover is `<server-url>/podcasts/99%%20Invisible/image.jpg` instead of `<server-url>/podcasts/99%25%20Invisible/image.jpg`

My PodFetch instance is behind nginx reverse proxy. Mentioning this because nginx reports HTTP 400, not the built-in server.

### Reproduction

as above

### System Info

```Shell
Linux, Synology, Firefox, PodFetch in Docker behind nginx reverse proxy
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mgoral** [comment]
This also affects podcast search (Itunes and Podcast Index). With "99% Invisible" spinner just keeps spinning. From the network console, the following request gets HTTP 400:

```
GET /api/v1/podcasts/1/99%%20Invisible/search HTTP/2
Host: <redacted>
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Authorization: Basic <redacted>
Connection: keep-alive
Referer: <redacted>/ui/podcasts
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
DNT: 1
Sec-GPC: 1
Pragma: no-cache
Cache-Control: no-cache
TE: trailers
```

**Comment by SamTV12345** [comment]
Thanks should be fixed now.
