### ISSUE TITLE
Add Podcast Index as search source

### ISSUE THREAD

**Issue by Ethanol6** [SamTV12345/PodFetch#21]
### Clear and concise description of the problem

I don't want to rely entirely on iTunes to supply my podcasts. It would be great to add the Podcast Index as a source. https://podcastindex.org/

### Suggested solution

Provide a toggle or drop down list to choose which source to search and add podcasts from.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Ethanol6** [comment]
Yes, it looks like you need an API key. Wouldn't be too bad to insert your own, like I do with other apps like OpenWeather etc.

**Comment by SamTV12345** [comment]
I'll take a look at the API.

**Comment by Ethanol6** [comment]
Do you want to add this to the roadmap?

**Comment by SamTV12345** [comment]
I added it to the roadmap.

**Comment by SamTV12345** [comment]
You can now use PodcastIndex to search and add podcasts. Please check the docs on how to add PodcastIndex to Podfetch.

**Comment by Ethanol6** [comment]
So fast. Thanks!

**Comment by SamTV12345** [comment]
You're welcome. I just found some time yesterday and the API documentation was very detailled with some php examples. So it was just a matter of porting that to Rust.
