### ISSUE TITLE
Create a Dark Mode

### ISSUE THREAD

**Issue by SamTV12345** [SamTV12345/PodFetch#210]
### Clear and concise description of the problem

I was told on Reddit that we need a [Dark mode](https://www.reddit.com/r/selfhosted/comments/14t9cos/comment/jr58bkx/?utm_source=share&utm_medium=web2x&context=3) xD. So we should add one.

### Suggested solution

Adapt CSS for Dark Mode.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by SamTV12345** [comment]
@jchue Do you have time for this? Your work with the UI before was awesome so it would be great if you could add a Dark Mode. Only if you have time of couse 😃

**Comment by jchue** [comment]
Yes, I can help with this! It might not be as fast as last time though 😅

**Comment by jchue** [comment]
How is it so far? Is it too dark / is there too much contrast?

![home-dark](https://github.com/SamTV12345/PodFetch/assets/5141427/cf0ec97c-967b-474f-b184-3c4768fa3339)

**Comment by SamTV12345** [comment]
For my liking it is a bit too flat. Can you mix another color into the UI color palette? Maybe the sidebar has a different tone than the content panel itself.

**Comment by jchue** [comment]
Like this?

![home-dark](https://github.com/SamTV12345/PodFetch/assets/5141427/fda87d0c-4b90-43aa-8c18-49f4ebf6ba94)

Or more?

**Comment by SamTV12345** [comment]
> Like this?
> 
> ![home-dark](https://user-images.githubusercontent.com/5141427/254101640-fda87d0c-4b90-43aa-8c18-49f4ebf6ba94.png)
> 
> Or more?

That looks good as a baseline color. Do you have a suggestion for the modals?

**Comment by jchue** [comment]
I'm working with the "All subscriptions" page instead, since it has more elements. I've tweaked the colors a little and increased the accents:

![all-subscriptions-dark](https://github.com/SamTV12345/PodFetch/assets/5141427/df248cf4-e788-425b-a086-f4775e793d57)

And here is a modal:

![all-subscriptions-modal-dark](https://github.com/SamTV12345/PodFetch/assets/5141427/17a9186c-e9b0-41ba-a509-c5e33ec8a9ff)

**Comment by SamTV12345** [comment]
The modals look good. I'm happy with the design.

**Comment by SamTV12345** [comment]
I forgot to mention in the redesign that there is also a register screen where a user can accept an invite.

![image](https://github.com/SamTV12345/PodFetch/assets/40429738/794455a3-2730-4fef-bf0d-deef9372567a)

**Comment by jchue** [comment]
Here is the Podcast Detail page:

![podcast-detail-dark](https://github.com/SamTV12345/PodFetch/assets/5141427/84e6695b-2d92-4192-b6ef-d4f3066ca9c1)

Sorry for taking so long. I probably won't create wireframes for every single page, but I want to do a few more where there are unique elements on the page (e.g., some of the settings pages, the system information page, etc.).

**Comment by SamTV12345** [comment]
I think we can close this. Thank you for the contribution.
