### ISSUE TITLE
Downloaded podcasts with correct naming instead of creating folders

### ISSUE THREAD

**Issue by update-freak** [SamTV12345/PodFetch#220]
### Clear and concise description of the problem

It would be great if the downloaded podcast will not placed in a named folder -> better to have the naming in the mp3-file itself. I would prefer a folder for each podcast, e.g. one for Daily Quarks and one for Deutschlandfunk.

### Suggested solution

Naming of the mp3-files as the episode name.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by chiefy** [comment]
I was a bit confused in the UI in settings it still has `standard-episode-format-explanation` placeholder :)

**Comment by SamTV12345** [comment]
> I was a bit confused in the UI in settings it still has `standard-episode-format-explanation` placeholder :)

Oh sorry. Seems like I missed a key to translate 😅.

**Comment by update-freak** [comment]
ok, thanks

**Comment by timosturm** [comment]
I would be very happy to see this implemented. 
Instead of 
```
<podcast-name>
    - <episode-name1>
        - podcast.mp3
        - image.png
 ```
to have
```
<podcast-name>
    - <episode-name1>.mp3
    - <episode-name2>.mp3
```

Also, we could have the episodes to be numbered for sometimes episodes do not have a track set in the ID3.

**Comment by SamTV12345** [comment]
Yeah. I know. I am trying to work on that. Next week could be better. I want to get it right as this part is especially complex with a lot of exceptions.

**Comment by Cyph3r** [comment]
> I would be very happy to see this implemented. (but I have not clue of using rust) Instead of
> 
> ```
> <podcast-name>
>     - <episode-name1>
>         - podcast.mp3
>         - image.png
> ```
> 
> to have
> 
> ```
> <podcast-name>
>     - <episode-name1>.mp3
>     - <episode-name2>.mp3
> ```
> 
> Also, we could have the episodes to be numbered for sometimes episodes do not have a track set in the ID3.

+1
+1
+1

**Comment by SamTV12345** [comment]
Tomorrow is the day. I'm too tired for now to concentrate on the path building mechanism.

**Comment by Cyph3r** [comment]
@SamTV12345 thanks very much!!!
