### ISSUE TITLE
Delete single podcast episodes (not all episodes from a specific podcast)

### ISSUE THREAD

**Issue by update-freak** [SamTV12345/PodFetch#221]
### Clear and concise description of the problem

It would be good to have the option to delete single downloaded episodes (from the server).
For example if a file is downloaded by a mistake.

### Suggested solution

Option to delete single episodes from a podcast.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by SamTV12345** [comment]
Good idea. I'll try to implement that.

**Comment by update-freak** [comment]
thanks :)

**Comment by SamTV12345** [comment]
I'll implement this feature next. How should this deleting work?

Automatic download shouldn't try to redownload a deleted podcast if it is within the number of podcasts to download. Should I download the next older podcast or just let the already downloaded podcasts downloaded and not fetch older podcasts?

**Comment by update-freak** [comment]
Automatic download shouldn't try to redownload a deleted podcast if it is within the number of podcasts to download -> yes
But then it's the question if I can manually download is again then (if the delete was not wished).

**Comment by update-freak** [comment]
> I'll implement this feature next. How should this deleting work?
> 
> Automatic download shouldn't try to redownload a deleted podcast if it is within the number of podcasts to download. Should I download the next older podcast or just let the already downloaded podcasts downloaded and not fetch older podcasts?

I got this error, I added the command in the same command line where I added the user:

![2023-07-25 07_16_05-NAS - Synology DiskStation](https://github.com/SamTV12345/PodFetch/assets/40196995/423e6f60-73aa-4569-9cb5-a1d4bbdd4905)
