### ISSUE TITLE
Invite not deleted after being used

### ISSUE THREAD

**Issue by realmain** [SamTV12345/PodFetch#244]
### Describe the bug

After using an invite, the invite link is still sitting in the Invites section, though the link isn't usable. When using the link, it'll just have an infinite loading screen.

The Invite link should be automatically deleted from the Invites section once it has been used.

### Reproduction

Create an invite, create new user through invite, check Invites section

### System Info

```Shell
Docker
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Good one. I'll need to split the invites between expired/pending invites.

**Comment by SamTV12345** [comment]
Somehow Jenkins was buggy and never released the postgres version to DockerHub. It is now up.
