### ISSUE TITLE
Can't use RSS link of PodFetch

### ISSUE THREAD

**Issue by helmut72** [SamTV12345/PodFetch#254]
### Describe the bug

When I click on the RSS icon, nothing happens in any browser or RSS/Podcast client, but I see following log line:

```
thread 'actix-rt|system:0|arbiter:0' panicked at 'called `Option::unwrap()` on a `None` value', src/service/podcast_episode_service.rs:340:40
```

### Reproduction

Click on any RSS icon in PodFetch

### System Info

```Shell
Your example docker-compose on ARM (Raspberry) with SQLlite: v4.0.2-02d7de0a (HEAD)
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Thanks for creating an issue. I just tried to reproduce it on my local system: 
![image](https://github.com/SamTV12345/PodFetch/assets/40429738/eafbd2d0-23eb-403e-8293-7bdf368dcddf)

As you can see it works without a problem on a Raspberry PI 4. So it could be the podcast itself that fails.

**Comment by SamTV12345** [comment]
The error seems to occur when the url file suffix is parsed. So could be the podcast data.

**Comment by helmut72** [comment]
Thanks! I've tried it with a Podcast from iTunes and it works. I have a special podcast and need to investigate this system. Sorry for the noise.

**Comment by SamTV12345** [comment]
No problem. I'm happy for any feedback. If you can reproduce the issue. Feel free to reopen this. It could very well be that I did oversee an optional field in a podcast that could cause this issue.
