### ISSUE TITLE
Guide to naming in Standard Episode / Standard Podcast format?

### ISSUE THREAD

**Issue by crosbyh** [SamTV12345/PodFetch#260]
### Describe the bug

Hello, thank you for this wonderful application!

I am hoping to use it to give my downloaded episodes a custom name. I believe the feature I want is  the Standard Episode Format under Naming Conventions in Settings, however I cannot find any guide to what keys are available to use in renaming. Essentially, I am just trying to prepend the episode number to the front of my downloaded episode titles.

Here is how it appears in the UI for me:
![settings](https://github.com/SamTV12345/PodFetch/assets/13104810/64f64d15-25df-454a-b74a-34ddcba17afa)
![naming](https://github.com/SamTV12345/PodFetch/assets/13104810/57c0b308-0224-41e9-8369-74195f568cbc)

### Reproduction

Images of what I see in the UI are attached.

### System Info

```Shell
I'm running Podfetch in Docker on the `dev-postgres` tag.
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
The naming conventions are for configuring global prefixes of a podcast. So if you want all your podcasts to have a specific format like MyEpisodes: #Episode 123 you can input that into the format string. {} are where the podcast name/episode name is inserted into.

**Comment by jwynn6** [comment]
I have the same question as the original poster.  What are the keys that are used between the {}.  Is it a variable like %artist% or something like that?

**Comment by SamTV12345** [comment]
There are currently no tags defined. In the curly braces only the titel is inserted.

**Comment by Cyph3r** [comment]
@SamTV12345 Not even that is working for me. The default "{}" results in a folder with the name of the episode in single quotes for some reason, i.e. 'Ready or Not, Driverless Cars Are Here'.
And then the podcast audio inside that folder is a single file of the name podcast.mp3.
The Daily -> 'Ready or Not, Driverless Cars Are Here' -> podcast.mp3

That structure won't work with any other program I have and it even throws Plex's Music indexer into a state of chaos.

Is this a bug, or am I not understanding the syntax. It seems like the default value should only produce a useable result.
Please Help

**Comment by minkshaman** [comment]
> The naming conventions are for configuring global prefixes of a podcast. So if you want all your podcasts to have a specific format like MyEpisodes: #Episode 123 you can input that into the format string. {} are where the podcast name/episode name is inserted into.

Can I ask what you mean by that?
What kind of options can I do?

Do you have an example?

**Comment by crosbyh** [comment]
This support page outlines how it works, for instance, in Sonarr to allow custom naming conventions:

https://wiki.servarr.com/sonarr/settings

here is the convention for yt-dlp custom output naming:
https://github.com/yt-dlp/yt-dlp#output-template

**Comment by minkshaman** [comment]
OK, so the show has this in the feed:
(show details)
```
<rss version="2.0">
<channel>
<atom:link href="https://feeds.simplecast.com/_WI4mhWl" rel="self" title="MP3 Audio" type="application/atom+xml"/>
<atom:link href="https://simplecast.superfeedr.com/" rel="hub"/>
<generator>https://simplecast.com</generator>
<title>Secretly Incredibly Fascinating</title>
```
(Episode details)
```
<title>Baking Soda</title>
<description>
<p>Alex Schmidt and Katie Goldin explore why baking soda is secretly incredibly fascinating.</p><p>Visit <a href="http://sifpod.fun/" target="_blank">http://sifpod.fun/</a> for research sources and for this week's bonus episode.</p><p>Come hang out with us on the new SIF Discord: <a href="https://discord.gg/wbR96nsGg5" target="_blank">https://discord.gg/wbR96nsGg5</a></p>
</description>
<pubDate>Mon, 23 Oct 2023 05:05:00 +0000</pubDate>
<author>
secretlyincrediblyfascinating@gmail.com (Alex Schmidt, Katie Goldin)
</author>
```
I'm guessing that the folder structure is pulled from the feed as:
>Channel title
>>Episode title
>>>Podcast audio file

I'm confused as to how "Standard episode format" and "Standard podcast format" are different.
Do they control the folder naming?
Is it that the episode format controls the way episode folder is named, and that the Podcast format is the way the parent podcast folder is named?
How do I get rid of the ' around the Episode title?

Can I control how the podcast audio file is named?

**Comment by CDeLeon94** [comment]
the `{}` *is* __the__ key, `Standard episode format` seems to be for the audio-file name
I'm assuming based on the part test I just did that `Standard podcast format` must be for new podcasts only. 

`Use direct paths` toggles whether or not the episode files are put in a folder
`Use existing filenames` is probably not something you want, because it seems that most feeds simply name the audio file `podcast.mp3` so you'd basically have nameless files. 

Based on what I read elsewhere, the quotes in the names are intentional, I'll have to tinker with the code because I don't think this should be necessary.

**Comment by SamTV12345** [comment]
> OK, so the show has this in the feed: (show details)
> 
> ```
> <rss version="2.0">
> <channel>
> <atom:link href="https://feeds.simplecast.com/_WI4mhWl" rel="self" title="MP3 Audio" type="application/atom+xml"/>
> <atom:link href="https://simplecast.superfeedr.com/" rel="hub"/>
> <generator>https://simplecast.com</generator>
> <title>Secretly Incredibly Fascinating</title>
> ```
> 
> (Episode details)
> 
> ```
> <title>Baking Soda</title>
> <description>
> <p>Alex Schmidt and Katie Goldin explore why baking soda is secretly incredibly fascinating.</p><p>Visit <a href="http://sifpod.fun/" target="_blank">http://sifpod.fun/</a> for research sources and for this week's bonus episode.</p><p>Come hang out with us on the new SIF Discord: <a href="https://discord.gg/wbR96nsGg5" target="_blank">https://discord.gg/wbR96nsGg5</a></p>
> </description>
> <pubDate>Mon, 23 Oct 2023 05:05:00 +0000</pubDate>
> <author>
> secretlyincrediblyfascinating@gmail.com (Alex Schmidt, Katie Goldin)
> </author>
> ```
> 
> I'm guessing that the folder structure is pulled from the feed as:
> 
> > Channel title
> > > Episode title
> > > > Podcast audio file
> 
> I'm confused as to how "Standard episode format" and "Standard podcast format" are different. Do they control the folder naming? Is it that the episode format controls the way episode folder is named, and that the Podcast format is the way the parent podcast folder is named? How do I get rid of the ' around the Episode title?
> 
> Can I control how the podcast audio file is named?

Standard podcast name controls the name of the folder. Standard episode name the name of the subfolder/the name of the mp3 file when direct path is enabled.

**Comment by SamTV12345** [comment]
> the `{}` _is_ **the** key, `Standard episode format` seems to be for the audio-file name I'm assuming based on the part test I just did that `Standard podcast format` must be for new podcasts only.
> 
> `Use direct paths` toggles whether or not the episode files are put in a folder `Use existing filenames` is probably not something you want, because it seems that most feeds simply name the audio file `podcast.mp3` so you'd basically have nameless files.
> 
> Based on what I read elsewhere, the quotes in the names are intentional, I'll have to tinker with the code because I don't think this should be necessary.

If you find a better solution sure. I can only remember that especially on Windows some podcasts with slashes were interpreted as paths in the folder.

**Comment by shooftie** [comment]
Forgive me, I feel that I might be missing something.

@crosbyh, the [links](https://github.com/SamTV12345/PodFetch/issues/260#issuecomment-1783496793) that you posted are to a separate project, right? Is this because PodFetch is following the same principles/leveraging that project or because this is what you feel it should aspire to?

@SamTV12345 (great work btw, I'll throw you some cash once I am up and running), when [you said](https://github.com/SamTV12345/PodFetch/issues/260#issuecomment-1693963052),

> There are currently no tags defined

Do you mean that you have not yet enabled any tags other than `title` (`Episode CleanTitle`) i.e. all that is possible at the moment is to augment the title with hardcoded strings?

e.g. given an episode title of "Foo" and a "Standard episode format" pattern of `Bar - {}` the outcome would be:

```
/
┗ MyPodcast
   ┣ 'Bar - Foo'.mp3
   ┗ 'Bar - Foo'.jpg
```
(btw, those single quotes are super annoying!)

I am trying to achieve something along the lines of `{Air-Date} - {episode:00} - {Episode CleanTitle}`. I appreciate that this would not be possible for every feed as it relies on some non-standard fields.

**Comment by shooftie** [comment]
[MP3Tag](https://www.mp3tag.de) (a fantastic bit of software), has a tool which allows you to infer fields from a string by means of a given pattern e.g. 'filename ⇒ tags', given a title of "Hamish & Andy 2023 Ep 236" and a pattern of `%title% %year% Ep %track%` would extract the tags:
- **title**: Hamish & Andy
- **year**: 2023
- **episode**: 236

I realise that this is likely a great deal of work to implement but I am throwing it out there...
