### ISSUE TITLE
support gpodder integration with basic-auth on reverse proxy only

### ISSUE THREAD

**Issue by Artox** [SamTV12345/PodFetch#281]
### Clear and concise description of the problem

Currently to enable gpodder.net integration users are guided to enable `BASIC_AUTH=true` or OIDC.
However the [auth documentation](https://github.com/SamTV12345/PodFetch/blob/main/docs/AUTH.md) even suggests not using it: "Basic Auth is not required. If you use a reverse proxy like nginx you can use a better form ..."

I suggest to make it possible on a single-user podfetch installation to rely on the reverse proxy basic-auth, and yet enable gpodder.net integration.

`GPODDER_INTEGRATION_ENABLED activated but no BASIC_AUTH or OIDC_AUTH set. Please set BASIC_AUTH or OIDC_AUTH in the .env file.`

### Suggested solution

I do not know how to implement a solution. Perhaps reverse proxy could forward some useful headers?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by SamTV12345** [comment]
Good issue.  Rather than needing another service I could also limit basic auth to the AntennaPod API. So when you open the browser you don't have to login, only on AntennaPod which is unfortunately mandatory.

**Comment by SamTV12345** [comment]
This is finally resolved. Sorry for the long break.
