### ISSUE TITLE
Failed to unwrap RSS feed

### ISSUE THREAD

**Issue by mrhackcz** [SamTV12345/PodFetch#297]
### Describe the bug

Hi!
Sadly I'm not able to add one of my podcasts. I can't post the URL of RSS here because it's behind the paywall. If you write down your email or something other than mastodon I can send the URL to you.

backtrace=full :
```
2023-08-31T17:18:50 ℹ️ - Actix runtime found; starting in Actix runtime
thread 'actix-rt|system:0|arbiter:2' panicked at 'called `Result::unwrap()` on an `Err` value: Eof', src/controllers/podcast_controller.rs:306:47
stack backtrace:
  stack backtrace:
   0:     0x7f690ea22253 - <unknown>
   1:     0x7f690e26dbdf - <unknown>
   2:     0x7f690ea1e917 - <unknown>
   3:     0x7f690ea22025 - <unknown>
   4:     0x7f690ea238a0 - <unknown>
   5:     0x7f690ea23664 - <unknown>
   6:     0x7f690ea23d89 - <unknown>
   7:     0x7f690ea23c94 - <unknown>
   7:     0x7f690ea23c94 - <unknown>
   8:     0x7f690ea22896 - <unknown>
   9:     0x7f690ea23a32 - <unknown>
  10:     0x7f690e123983 - <unknown>
  11:     0x7f690e123e23 - <unknown>
  12:     0x7f690e46d419 - <unknown>
  13:     0x7f690e4481ea - <unknown>
  14:     0x7f690e41cb4b - <unknown>
  15:     0x7f690e5472e8 - <unknown>
  16:     0x7f690e41c39b - <unknown>
  17:     0x7f690e41c6db - <unknown>
  18:     0x7f690e41c6db - <unknown>
  19:     0x7f690e4a60e0 - <unknown>
  20:     0x7f690e38d07f - <unknown>
  21:     0x7f690e5070a3 - <unknown>
  22:     0x7f690e515acd - <unknown>
  23:     0x7f690e777597 - <unknown>
  24:     0x7f690e4099d4 - <unknown>
  25:     0x7f690e785207 - <unknown>
  26:     0x7f690ea6a9b8 - <unknown>
  27:     0x7f690e1e8efe - <unknown>
  28:     0x7f690e1b8e08 - <unknown>
  29:     0x7f690e1e0643 - <unknown>
  30:     0x7f690e1d3748 - <unknown>
  31:     0x7f690e1b924d - <unknown>
  32:     0x7f690e1cae9f - <unknown>
  33:     0x7f690e1e0c63 - <unknown>
  34:     0x7f690e1c0d53 - <unknown>
  35:     0x7f690e1c70fc - <unknown>
  36:     0x7f690ea277f5 - <unknown>
  ```

### Reproduction

With RSS URL

### System Info

```Shell
Latest docker image, sqlite database
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Thanks for the issue. Seems like the rss feed causes an issue while being parsed. Could you please send the rss feed to samelus1998@outlook.de? I'd be glad to take a look at it.

**Comment by SamTV12345** [comment]
Thanks got the link. 👍
