### ISSUE TITLE
Page listing the episodes not yet listened

### ISSUE THREAD

**Issue by bastgau** [SamTV12345/PodFetch#298]
### Clear and concise description of the problem

I would like to see all episodes not yet listened in the same page.

### Suggested solution

We could add a new page listing the episodes not yet listened.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by SamTV12345** [comment]
So from every podcast every episode that you haven't listened to? Should that be ordered by release date?

**Comment by bastgau** [comment]
In fact, it could be placed in the same page as: /ui/timeline but it should be possible to filter to keep only the episodes not yet listened.

**Comment by SamTV12345** [comment]
> In fact, it could be placed in the same page as: /ui/timeline but it should be possible to filter to keep only the episodes not yet listened.

Should be possible to do. I'll implement that that tomorrow.
