### ISSUE TITLE
RSS link is incorrect with a docker container

### ISSUE THREAD

**Issue by bastgau** [SamTV12345/PodFetch#299]
### Describe the bug

On the page /ui/info, the RSS link is incorrect when we launch the application in a docker container.

The port displayed is the internal port not the exposed port.

### Reproduction

...

### System Info

```Shell
My docker-compose file :

version: '3.3'
services:
  podfetch:
    container_name: podfetch
    image: samuel19982/podfetch:latest
    restart: unless-stopped
    # user: ${UID:-1000}:${GID:-1000}
    ports:
      - "8087:8000"
    dns:
      - "1.1.1.1"
      - "8.8.8.8"
      - "9.9.9.9"
    volumes:
      - "./data/podcasts:/app/podcasts"
      - "./data/db:/app/db"
    environment:
      - POLLING_INTERVAL=60
      - PODINDEX_API_KEY=$PODINDEX_API_KEY
      - PODINDEX_API_SECRET=$PODINDEX_API_SECRET
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Hmm. You didn't set the SERVER_URL variable. Could that be the issue?

**Comment by bastgau** [comment]
You're right. It works if I add the variable SERVER_URL.

The documentation is maybe not complete.

"Set the SERVER_URL environment variable to the url of the proxy."

Btw, I don't use a proxy :)

You can close this ticket.

**Comment by SamTV12345** [comment]
> You're right. It works if I add the variable SERVER_URL.
> 
> The documentation is maybe not complete.
> 
> "Set the SERVER_URL environment variable to the url of the proxy."
> 
> Btw, I don't use a proxy :)

Did I wrote that somewhere? Big oopsie time I guess :D. I'll correct.
