### ISSUE TITLE
Incorrect message displayed when an episode is already listened.

### ISSUE THREAD

**Issue by bastgau** [SamTV12345/PodFetch#302]
### Describe the bug

When an episode contains double quote, the message displayed when the episode has already been listened is incorrect.

The episode name is : > "Des mille et des cents" : mais où vont les S ? du 02 septembre 2023

The message displayed is :

"You already listened to the episode **\&quot;** Des mille et des cents **\&quot;** : mais où vont les S ? du 02 septembre 2023. Do you want to restart playing?"

<img width="1043" alt="image" src="https://github.com/SamTV12345/PodFetch/assets/4788354/829a7572-db41-4808-a4c3-dfed3e821f21">

### Reproduction

...

### System Info

```Shell
...
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Can you send the link? Seems like iTunes is the wrong place to search for that podcast https://podcasts.apple.com/ch/podcast/des-mille-et-des-cents/id1658314629

**Comment by bastgau** [comment]
This one : https://feeds.audiomeans.fr/feed/0d62e828-09e4-4ea4-a8c4-c5d9b62c2fec.xml
