### ISSUE TITLE
Issue regarding the themes

### ISSUE THREAD

**Issue by bastgau** [SamTV12345/PodFetch#332]
### Describe the bug

Hello.

There is an issue with a white text on a white background.

Everything works well with the dark theme.

Screenshots in example :)

Thanks.

<img width="770" alt="Capture d’écran 2023-09-20 à 16 57 14" src="https://github.com/SamTV12345/PodFetch/assets/4788354/ffcea34c-8cd6-45f1-b8e6-7b2e1c795264">
<img width="746" alt="Capture d’écran 2023-09-20 à 16 57 22" src="https://github.com/SamTV12345/PodFetch/assets/4788354/e45262cf-421d-4db1-bb2a-71e893eb54d0">
<img width="747" alt="Capture d’écran 2023-09-20 à 17 01 14" src="https://github.com/SamTV12345/PodFetch/assets/4788354/90bb91d0-f26f-4fde-b267-82c3825cabbb">

### Reproduction

...

### System Info

```Shell
...
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Oh no. I missed a class name on there. I'll fix this ASAP.

**Comment by bastgau** [comment]
Thanks. I have just updated my container and the issue seems to be resolved.
