### ISSUE TITLE
Directory name with duplicated single/double quotes

### ISSUE THREAD

**Issue by bastgau** [SamTV12345/PodFetch#335]
### Describe the bug

Hello.

Sorry, I found three new bugs related to the episode downloads.

1/ For the following feed : https://feeds.libsyn.com/126127/rss, the directory name containing the episodes contain additional single quote. It seems that the issue is existing for some other podcasts when the episode title containing one or somes space characters.

The name seems to be correct for the podcasts.

**Example :**

```bash
$ ls -la
drwxr-xr-x  2 root root 4096 Sep 21 21:34 "'Gaijinsan - Episode 35'"
drwxr-xr-x  2 root root 4096 Sep 21 21:33 "'Gaijinsan - Episode 36'"
drwxr-xr-x  2 root root 4096 Sep 21 21:33 "'Gaijinsan - Episode 37'"
```

2/ When an episode is deleted, then download again, the initial directory is not removed and the second directory related to the second download is suffixed with a number.

```bash
$ ls -la
drwxr-xr-x  2 root root 4096 Sep 21 21:45 "'Gaijinsan - Episode 28'"
drwxr-xr-x  2 root root 4096 Sep 21 21:45 "'Gaijinsan - Episode 28'-0"
drwxr-xr-x  2 root root 4096 Sep 21 21:41 "'Gaijinsan - Episode 29'"
drwxr-xr-x  2 root root 4096 Sep 21 21:41 "'Gaijinsan - Episode 29'-0"
```

The file is not listenable because the GUI do a reference on the initial directory.

3/ On the RSS feed, the audio files are referenced with this tag :

```html
<enclosure length="122217012" type="audio/mpeg" url="https://traffic.libsyn.com/secure/gaijinsan/Gaijinsan_-_Episode_44.mp3?dest-id=753038" />
```

When the file is downloaded, the episode file name is "podcast.mpeg". It should be : podcast.mp3

"**audio/mpeg**" should be considered as "**audio/mp3**"

Best.

### Reproduction

...

### System Info

```Shell
...
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Regarding the first issue: 
![image](https://github.com/SamTV12345/PodFetch/assets/40429738/7f41ef31-e701-4642-9cc3-a32276c05037)
I get this on a Windows machine. It is important to put quotation marks on the file as otherwise things can get messy on the file system. A / can be interpreted as a separator and there were also issues with whitespaces on Windows. So there must be a single quotation mark for that. 
Regading the second issue: I can't really reproduce this. This only happens if an episode is present, it is not yet registered in the database and there is another episode that is downloaded. So the use case would be that a podcaster releases two episodes with two identical names. Otherwise they would overwrite each other.

**Comment by bastgau** [comment]
For the point 2/ I only used the GUI to delete and download an episode again on an instance running on Linux with Docker.

**Comment by u175** [comment]
I have also noticed that podcasts are now being downloaded in the .MPEG format.

Is there a way to specify the format for podcast downloads? I would like to download my podcasts in .MP3 only.

Thanks

**Comment by bastgau** [comment]
Sorry but I persist.
There is an issue with the episode names and file names.

```
bastien@srv:~/podfetch/data/podcasts$ ls -l
total 20
drwxr-xr-x 7 root root 4096 Nov  4 17:14 '20 minutes avant la fin du monde'
drwxr-xr-x 7 root root 4096 Nov  4 14:02 "C'est votre argent"
drwxr-xr-x 7 root root 4096 Nov  4 17:35 'Gaijin San'
drwxr-xr-x 7 root root 4096 Nov  4 14:01 'La Revue de Presse'
drwxr-xr-x 7 root root 4096 Nov  4 14:02 'Un bonbon sur la langue'
```

**Everything is ok with the podcast names.**

```
bastien@srv-nipogi:~/docker-containers/podfetch/data/podcasts$ cd Gaijin\ San/
bastien@srv-nipogi:~/docker-containers/podfetch/data/podcasts/Gaijin San$ ls -l
total 940
drwxr-xr-x 2 root root   4096 Nov  4 15:01 "'Gaijinsan - Episode 44'"
drwxr-xr-x 2 root root   4096 Nov  4 15:00 "'Gaijinsan - Episode 45'"
-rw-r--r-- 1 root root 939658 Nov  4 14:02  image.jpeg
```

**For me in this example, at the episode level directory, there is additional single quote.**

```
bastien@srv-nipogi:~/docker-containers/podfetch/data/podcasts/Gaijin San$ sudo touch "'Gaijinsan - Episode 48_test'"
bastien@srv-nipogi:~/docker-containers/podfetch/data/podcasts/Gaijin San$ sudo touch "Gaijinsan - Episode 48_test"
```

**I can reproduce the error creating file in the file system.**

```
bastien@srv-nipogi:~/docker-containers/podfetch/data/podcasts/Gaijin San$ ls -l
total 940
drwxr-xr-x 2 root root   4096 Nov  4 15:01 "'Gaijinsan - Episode 44'"
drwxr-xr-x 2 root root   4096 Nov  4 15:00 "'Gaijinsan - Episode 45'"
-rw-r--r-- 1 root root      0 Nov  4 17:38 "'Gaijinsan - Episode 48_test'"
-rw-r--r-- 1 root root      0 Nov  4 17:38 'Gaijinsan - Episode 48_test'
-rw-r--r-- 1 root root 939658 Nov  4 14:02  image.jpeg
```

**The first command has generated the 3rd file. The second has generated the 4th line with the correct quotes.**

It seems that now the episode title is not mentionned in the mp3 file.

**Comment by SamTV12345** [comment]
This is fixed. I removed the single double quotes requirement. I just replace all illegal characters
