### ISSUE TITLE
Issue when Podfetch attempts to download the episodes

### ISSUE THREAD

**Issue by holazit** [SamTV12345/PodFetch#339]
### Describe the bug

Hi,

I have a problem with Podfetch: I've added all the podcasts I want to listen to, but they never get downloaded automatically. The download starts the first time at the top of the hour but then stops and never resumes until I restart the container. The log says:

```09/29/2023
7:47:14 AM
Debug file located at /home/rust/src/target/x86_64-unknown-linux-musl/release/build/podfetch-16a4ba946d3145fb/out/built.rs
09/29/2023
7:47:14 AM
09/29/2023
7:47:14 AM
  ____           _ _____    _       _
09/29/2023
7:47:14 AM
 |  _ \ ___   __| |  ___|__| |_ ___| |__
09/29/2023
7:47:14 AM
 | |_) / _ \ / _` | |_ / _ \ __/ __| '_ \
09/29/2023
7:47:14 AM
 |  __/ (_) | (_| |  _|  __/ || (__| | | |
09/29/2023
7:47:14 AM
 |_|   \___/ \__,_|_|  \___|\__\___|_| |_|
09/29/2023
7:47:14 AM
09/29/2023
7:47:14 AM
        
09/29/2023
7:47:14 AM
2023-09-29T05:47:14 ℹ️ - Settings already present
09/29/2023
7:47:14 AM
2023-09-29T05:47:14 ℹ️ - Starting with the following environment variables:
09/29/2023
7:47:14 AM
2023-09-29T05:47:14 ℹ️ - Public server url: http://10.0.0.6:11512/
09/29/2023
7:47:14 AM
2023-09-29T05:47:14 ℹ️ - Polling interval for new episodes: 60 minutes
09/29/2023
7:47:14 AM
2023-09-29T05:47:14 ℹ️ - Developer specifications available at http://10.0.0.6:11512/swagger-ui/index.html#/
09/29/2023
7:47:14 AM
2023-09-29T05:47:14 ℹ️ - GPodder integration enabled: false
09/29/2023
7:47:14 AM
2023-09-29T05:47:14 ℹ️ - Database url is set to: sqlite:///app/db/podcast.db
09/29/2023
7:47:14 AM
2023-09-29T05:47:14 ℹ️ - Podindex API key&secret configured: false
09/29/2023
7:47:14 AM
09/29/2023
7:47:14 AM
09/29/2023
7:47:14 AM
09/29/2023
7:47:14 AM
09/29/2023
7:47:14 AM
2023-09-29T05:47:14 ℹ️ - starting 4 workers
09/29/2023
7:47:14 AM
2023-09-29T05:47:14 ℹ️ - Actix runtime found; starting in Actix runtime
09/29/2023
8:00:00 AM
2023-09-29T06:00:00 ℹ️ - Polling for new episodes
09/29/2023
8:00:02 AM
2023-09-29T06:00:02 ℹ️ - Downloading podcast episode: Ep.49 - Yakuza
09/29/2023
8:00:06 AM
2023-09-29T06:00:06 ℹ️ - Downloading podcast episode: S05E33 - La strada è in salita
09/29/2023
8:00:19 AM
2023-09-29T06:00:19 ℹ️ - Downloading podcast episode: Che cosa sta succedendo nel Nagorno-Karabakh
09/29/2023
8:00:20 AM
2023-09-29T06:00:20 ℹ️ - Downloading podcast episode: La mafia, ma anche la camorra e la ’ndrangheta, dopo Matteo Messina Denaro
09/29/2023
8:00:31 AM
2023-09-29T06:00:31 ℹ️ - Downloading podcast episode: 1240 - Perché li chiamano indiani (se sono americani)
09/29/2023
8:00:33 AM
2023-09-29T06:00:33 ℹ️ - Downloading podcast episode: 1239 - Cos'è la curiosità
09/29/2023
8:00:40 AM
2023-09-29T06:00:40 ℹ️ - Downloading podcast episode: DK8x03 - Stavolta è diverso
09/29/2023
8:00:45 AM
2023-09-29T06:00:45 ℹ️ - Downloading podcast episode: 40 - Se precipita l'ascensore che faccio?
09/29/2023
8:00:47 AM
2023-09-29T06:00:47 ℹ️ - Downloading podcast episode: Gli armeni scompariranno dal Nagorno Karabakh? 🇦🇲
09/29/2023
8:00:51 AM
2023-09-29T06:00:51 ℹ️ - Downloading podcast episode: 211 - Davvero non ci sarai a Bologna?
09/29/2023
8:00:52 AM
2023-09-29T06:00:52 ℹ️ - Downloading podcast episode: 210 - Fai milioni con le idee noiose (DAILY)
09/29/2023
8:01:09 AM
2023-09-29T06:01:09 ℹ️ - Downloading podcast episode: Spotify: podcast tradotti vocalmente con OpenAI
09/29/2023
8:01:13 AM
2023-09-29T06:01:13 ℹ️ - Downloading podcast episode: Amazon Prime video: al via gli annunci pubblicitari nel 2024
09/29/2023
8:01:18 AM
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Eof', src/service/podcast_episode_service.rs:141:14
09/29/2023
8:01:18 AM
stack backtrace:
09/29/2023
8:01:18 AM
   0:     0x7f193e476313 - <unknown>
09/29/2023
8:01:18 AM
   1:     0x7f193dca49bf - <unknown>
09/29/2023
8:01:18 AM
   2:     0x7f193e4729d7 - <unknown>
09/29/2023
8:01:18 AM
   3:     0x7f193e4760e5 - <unknown>
09/29/2023
8:01:18 AM
   4:     0x7f193e477960 - <unknown>
09/29/2023
8:01:18 AM
   5:     0x7f193e477724 - <unknown>
09/29/2023
8:01:18 AM
   6:     0x7f193e477e49 - <unknown>
09/29/2023
8:01:18 AM
   7:     0x7f193e477d54 - <unknown>
09/29/2023
8:01:18 AM
   8:     0x7f193e476956 - <unknown>
09/29/2023
8:01:18 AM
   9:     0x7f193e477af2 - <unknown>
09/29/2023
8:01:18 AM
  10:     0x7f193db57b53 - <unknown>
09/29/2023
8:01:18 AM
  11:     0x7f193db57ff3 - <unknown>
09/29/2023
8:01:18 AM
  12:     0x7f193df7d15c - <unknown>
09/29/2023
8:01:18 AM
  13:     0x7f193dfdb52b - <unknown>
09/29/2023
8:01:18 AM
  14:     0x7f193e0966b2 - <unknown>
09/29/2023
8:01:18 AM
  15:     0x7f193dffb483 - <unknown>
09/29/2023
8:01:18 AM
  16:     0x7f193e12e45e - <unknown>
09/29/2023
8:01:18 AM
  17:     0x7f193e47b8b5 - <unknown>
```
Then it does nothing more until I restart the container. Is there a problem with a specific podcast? How can I find out which one?

### Reproduction

I start the container and wait for Podfetch to download episodes automatically

### System Info

```Shell
I'm using Podfetch with this docker-compose:

  podfetch:
    container_name: podfetch
    image: samuel19982/podfetch:latest
    ports:
      - 11512:8000
    volumes:
      - $PERSIST/podfetch:/app/db
      - /volume1/media/Music/Podcast2:/app/podcasts
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - POLLING_INTERVAL=60
      - SERVER_URL=http://10.0.0.6:11512
      - DATABASE_URL=sqlite:///app/db/podcast.db
      - RUST_BACKTRACE=full
    restart: unless-stopped
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Thanks for the bug report. Do you mind if you could send me the podcast where the download fails?

**Comment by SamTV12345** [comment]
> I don't know which podcast is failing. Here is the list of my podcasts:
> 
> ```
> https://anchor.fm/s/d11c510c/podcast/rss
> https://feeds.megaphone.fm/BCS4111321912
> https://www.spreaker.com/show/3250113/episodes/feed
> https://d172q3toj7w1md.cloudfront.net/rss-xml-files/8fb9b8f2-590b-48f9-a566-a95b7950af68.xml
> https://feeds.megaphone.fm/IPS8073667277
> https://www.spreaker.com/show/4487282/episodes/feed
> https://feeds.megaphone.fm/cosemoltoumane
> https://feeds.megaphone.fm/cosemoltoamericane
> https://feeds.megaphone.fm/crimeandcomedy
> https://www.spreaker.com/show/5824072/episodes/feed
> https://www.spreaker.com/show/1977562/episodes/feed
> https://digitalia.fm/feeds/digitalia.xml
> https://feeds.easypodcast.it/EasyApple
> https://www.spreaker.com/show/4484414/episodes/feed
> https://feeds.megaphone.fm/BCS7597999447
> https://feeds.megaphone.fm/CPS2408869581
> https://feeds.megaphone.fm/ISM5684255413
> https://www.spreaker.com/show/4070003/episodes/feed
> https://anchor.fm/s/dde6124c/podcast/rss
> https://www.spreaker.com/show/5773405/episodes/feed
> https://feeds.megaphone.fm/BCS9670277241
> https://www.spreaker.com/show/5500652/episodes/feed
> https://www.omnycontent.com/d/playlist/60311b15-274a-4e3f-8ba9-ac3000834f37/3fbddd6a-ef2f-494d-bdc7-af8f00f3c16f/73175d2f-b9a3-4deb-ba0d-af8f00f3c178/podcast.rss
> https://anchor.fm/s/13d94c8/podcast/rss
> https://www.spreaker.com/show/5675731/episodes/feed
> https://feeds.megaphone.fm/mistergadgetdaily
> https://anchor.fm/s/8a73ebc0/podcast/rss
> https://www.spreaker.com/show/5536949/episodes/feed
> https://www.omnycontent.com/d/playlist/60311b15-274a-4e3f-8ba9-ac3000834f37/d8592cfd-9da3-4512-8eca-ae3d00a78e44/903f1cf5-20c2-40e1-931b-ae3d00a78e52/podcast.rss
> https://feeds.megaphone.fm/BSMT6291075949
> https://www.rsi.ch/rsi/web/podcast/il-disinformatico/?f=podcast-xml&amp;type=itunes
> https://www.spreaker.com/show/3181144/episodes/feed
> https://feeds.megaphone.fm/GLT7160542006
> https://www.pilloledib.it/feed/podcast/
> https://feeds.megaphone.fm/ISM1360448799
> https://feeds.buzzsprout.com/2110415.rss
> https://anchor.fm/s/724a46c0/podcast/rss
> http://10.0.0.6:12786/transcodize_rss?url=https://www.youtube.com/@breakingitaly
> ```
> 
> I looked at the podcast folder and I realized that the only podcasts that have never been downloaded are these:
> 
> ```
> https://www.rsi.ch/rsi/web/podcast/il-disinformatico/?f=podcast-xml&amp;type=itunes
> https://www.spreaker.com/show/5773405/episodes/feed
> https://www.omnycontent.com/d/playlist/60311b15-274a-4e3f-8ba9-ac3000834f37/3fbddd6a-ef2f-494d-bdc7-af8f00f3c16f/73175d2f-b9a3-4deb-ba0d-af8f00f3c178/podcast.rss
> https://anchor.fm/s/13d94c8/podcast/rss
> https://feeds.megaphone.fm/GLT7160542006
> ```
> 
> Could one of these podcasts be the issue?

Yes. It is most likely one of them. Do you know from which podcast the episode  "Amazon Prime video: al via gli annunci pubblicitari nel 2024" is from?

**Comment by SamTV12345** [comment]
I get a 404 error code when visiting  https://www.rsi.ch/rsi/web/podcast/il-disinformatico/?f=podcast-xml&amp;type=itunes in the browser.

**Comment by holazit** [comment]
> > Could one of these podcasts be the issue?
> 
> Yes. It is most likely one of them. Do you know from which podcast the episode "Amazon Prime video: al via gli annunci pubblicitari nel 2024" is from?

No, sorry.

**Comment by SamTV12345** [comment]
> > > Could one of these podcasts be the issue?
> > 
> > 
> > Yes. It is most likely one of them. Do you know from which podcast the episode "Amazon Prime video: al via gli annunci pubblicitari nel 2024" is from?
> 
> No, sorry.

That seems to work. It must be another one.

**Comment by SamTV12345** [comment]
@holazit 
This podcast is invalid: https://www.rsi.ch/rsi/web/podcast/il-disinformatico/?f=podcast-xml&amp;type=itunes

**Comment by SamTV12345** [comment]
The other worked so I'll close this one for now.
