### ISSUE TITLE
Tag docker image with version

### ISSUE THREAD

**Issue by TheBlusky** [SamTV12345/PodFetch#342]
### Clear and concise description of the problem

Docker registry only have 4 tagged version au PodFetch :

- dev
- latest
- postgres
- dev-postgres

Which is fine for people using Watchtower for example.

But it would also be good to tag Docker images with the version tagged (ex: `samuel19982/podfetch:4.2.2`).

(The reason for this, is "latest" will do things behind the scene that might be irreverisble, when, for example, restoring a backup, or duplicating servers).

### Suggested solution

In addition to already existing tags, taggin Docker images with the version tagged (ex: `samuel19982/podfetch:4.2.2`).

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by SamTV12345** [comment]
Hi thanks for creating the issue with this extensive documentation. Do you have experience with implementing that in Jenkins?

**Comment by TheBlusky** [comment]
Hello, I never used Jenkins, but first result in a search engine provided an example for how to do it (you might want to replace `${env.BUILD_NUMBER}` with something like `$tag_name`) :

```
stage('Push image') {
    docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
        app.push("${env.BUILD_NUMBER}")
        app.push("latest")
    }
}
```
(source : https://stackoverflow.com/a/53858257/4380515)

**Comment by SamTV12345** [comment]
> Hello, I never used Jenkins, but first result in a search engine provided an example for how to do it (you might want to replace `${env.BUILD_NUMBER}` with something like `$tag_name`) :
> 
> ```
> stage('Push image') {
>     docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
>         app.push("${env.BUILD_NUMBER}")
>         app.push("latest")
>     }
> }
> ```
> 
> (source : https://stackoverflow.com/a/53858257/4380515)

Thanks. I found an even better way with git tag and git commit id.
