### ISSUE TITLE
Single-Sign-On with OpenID Connect

### ISSUE THREAD

**Issue by alexanderadam** [SamTV12345/PodFetch#35]
### Clear and concise description of the problem

It would be nice to have different user accounts that can be handled with OIDC.
Popular selfhosted OIDC solutions are Authelia, Authentik, Keycloak or Nextcloud.
It would surely be nice if PodFetch would support that.

### Suggested solution

I don't know. Maybe via [this](https://docs.rs/openidconnect/latest/openidconnect/) or [this](https://docs.rs/openid/latest/openid/) crate?

It would be nice if the parameters could be provided via ENV variables.
For instance

```bash
    PODFETCH_OPENID_CONNECT_AUTHORIZATION_ENDPOINT
    PODFETCH_OPENID_CONNECT_TOKEN_ENDPOINT
    PODFETCH_OPENID_CONNECT_USERINFO_ENDPOINT
    PODFETCH_OPENID_CONNECT_SEND_NONCE
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by SamTV12345** [comment]
Great idea. This is definitely on my bucket list as I have a keycloak instance at home. Do all these services have a jwks endpoint?

**Comment by SamTV12345** [comment]
So far this enhancement is included. You can now login via Keycloak/Authelia etc. Please find the description in the docs.

**Comment by alexanderadam** [comment]
You're amazingly fast!
Thank you so much!
