### ISSUE TITLE
Episode show-notes overlay appears over wrong podcast

### ISSUE THREAD

**Issue by Ethanol6** [SamTV12345/PodFetch#350]
### Describe the bug

If I click on an an episode from any podcast the show-notes overlay for that episode appears. If I click "back" in the browser, without closing the show-notes, and then select another podcast the previous show-notes overlay appears.

### Reproduction

Select a podcast from the "All Subscriptions" menu and click on any episode. When the show notes appear, click "back" on the browser. Click on any other podcast from your "All Subscriptions" page. The show notes from the first podcast appear.

### System Info

```Shell
System:
    OS: Linux 5.4 Linux Mint 20.3 (Una)
    CPU: (8) x64 AMD FX(tm)-8350 Eight-Core Processor
    Memory: 5.76 GB / 23.42 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    npm: 6.14.4 - /usr/bin/npm

Browsers tested:
    Brave
    Firefox
    Vanadium (Chromium fork)

Podfetch version:
    v4.2.2-267fdf7e (HEAD)
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Hi @Ethanol6. Good to see you and thank you for the extensive testing and description of the problem.
