### ISSUE TITLE
New invite - Create invite button dead

### ISSUE THREAD

**Issue by peterpepo** [SamTV12345/PodFetch#352]
### Describe the bug

I cannot create a new invite, "Create invite" button in Add new modal (User Administration -> Invites -> Add new) doesn't work. It does nothing in all of my browsers: Firefox (v118.0.2), Chrome (118.0.5993.70), Edge (118.0.2088.46).

### Reproduction

1. Run docker postgres-docker samuel19982/podfetch:postgres
2. BASIC_AUTH=true, USERNAME=aaa, PASSWORD=bbb
3. log in as aaa/bbb
4. User Administration -> Invites -> Add new
5. Modal opens up
6. Button is dead

### System Info

```Shell
Host:
- docker image samuel19982/podfetch:postgres
- Raspberry pi 3B
- Operating System: Debian GNU/Linux 11 (bullseye)
- Kernel: Linux 6.1.21-v8+
- Architecture: arm64

Client:
- Firefox (v118.0.2), Chrome (118.0.5993.70), Edge (118.0.2088.46)
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
This is also fixed now.
