### ISSUE TITLE
Docker - CLI doesn't work, cannot open console

### ISSUE THREAD

**Issue by peterpepo** [SamTV12345/PodFetch#353]
### Describe the bug

Whenever I try to run a command for CLI, from here https://github.com/SamTV12345/PodFetch/blob/main/docs/CLI.md, for example:
`docker exec -it 989d8377f1ac /app/podfetch users --help`

I always get:

> Debug file located at /home/rust/src/target/aarch64-unknown-linux-musl/release/build/podfetch-53f96701188bebd4/out/built.rs

Then I tried opening a console (/bin/sh, /bin/bash, /bin/ash) from portainer to read a log file, or invoke a CLI directly from there - neither of them works. Same when trying to open from ssh
`docker exec -it 989d8377f1ac /bin/sh`

> OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown

### Reproduction

1. Run docker postgres-docker samuel19982/podfetch:postgres 2. BASIC_AUTH=true, USERNAME=aaa, PASSWORD=bbb 3. log in as aaa/bbb 4. User Administration -> Invites -> Add new 5. Modal opens up 6. Button is dead

### System Info

```Shell
Host:
- docker image samuel19982/podfetch:postgres
- Raspberry pi 3B
- Operating System: Debian GNU/Linux 11 (bullseye)
- Kernel: Linux 6.1.21-v8+
- Architecture: arm64
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Thanks for the issue and sorry for the inconvenience. It is fixed and you can now use it with the latest image.

**Comment by peterpepo** [comment]
Thank you, please could you also add support for bash/console in your docker image?
Should I create separate - feature request for this? I think it's always useful / defacto standard for docker images to be able to log in and read log files etc..

**Comment by SamTV12345** [comment]
> Thank you, please could you also add support for bash/console in your docker image? Should I create separate - feature request for this? I think it's always useful / defacto standard for docker images to be able to log in and read log files etc..

You're welcome. I don't know why bash would be necessary. You can always check the files in the volumes.
