### ISSUE TITLE
RSS feeds with multiple podcasts don't load

### ISSUE THREAD

**Issue by minkshaman** [SamTV12345/PodFetch#369]
### Describe the bug

My partner has a MaximumFun network membership and they've sent her an RSS feed with all the episodes and such.

Problem is, it's got dozens or more of episodes from multiple authors loaded into it, and it appears that PodFetch doesn't know how to deal with it.

Happy to send an email with the podcast link to samelus1998@outlook.de if you'd like?

### Reproduction

Try to load MaxFun network RSS feed

### System Info

```Shell
Unraid/Docker
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
@minkshaman Thanks for the bug report. Please send me the link to the podcast via email. I am happy to take a look at it.

**Comment by minkshaman** [comment]
Sent. Thanks!

**Comment by minkshaman** [comment]
OK, Apologies!

It DID load, it just took over a day to display.

**Comment by SamTV12345** [comment]
> OK, Apologies!
> 
> It DID load, it just took over a day to display.

I'll check it out now.

**Comment by SamTV12345** [comment]
It did work without a problem. Was this maybe a temporary failure?

**Comment by minkshaman** [comment]
Seems so, worked after 24 hours.
I did try multiple times and restarted the container a few times too.

All good though, working now though!

Is there any chance I could get you to take a look at my enhancement suggestion?
https://github.com/SamTV12345/PodFetch/issues/370

Closing issue.
