### ISSUE TITLE
User defined filetype

### ISSUE THREAD

**Issue by minkshaman** [SamTV12345/PodFetch#370]
### Clear and concise description of the problem

I've been trying to get the podcasts to show up in Emby, in order to make them work in Apple CarPlay.
The only way Emby will play them through Apple CarPlay is if they're "music" files (MP3, AAC etc.)

The podcasts download as .mpeg files, which Emby only recognises as video files.

I'd just rename them, but I'm concerned that if I do, the system will just download them again, resulting in doubleups

### Suggested solution

Is there a way to force them to be mp3s?
Or if not, is there a way to tell the system "Download them once only", which would allow me to have a script running to rename them automatically?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by SamTV12345** [comment]
Oh good to know that there is really a system that makes this deviation. The MPEGs are really MP3s. Do your RSS feed contain the links with a file extension?

**Comment by minkshaman** [comment]
Yeah, it's the same feed I sent you before.

The weird thing is this:

- The feed has it as mp3.
- The feed also says type="audio/mpeg"
- The file system says it's .mpeg
- If I click download in PodFetch, it downloads as .mp3

This is maximum messed up haha

**Comment by SamTV12345** [comment]
> Yeah, it's the same feed I sent you before.
> 
> The weird thing is this:
> 
> * The feed has it as mp3.
> * The feed also says type="audio/mpeg"
> * The file system says it's .mpeg
> * If I click download in PodFetch, it downloads as .mp3
> 
> This is maximum messed up haha

True. I checked the source code and I already had it documented that the type from the request is taken as a first source. So as it is audio/mpeg I take that. I swapped the logic. It is now URL first, type second and else as a fallback method .mp3

**Comment by SamTV12345** [comment]
You can checkout the dev tags of PodFetch for that.

**Comment by u175** [comment]
I’m still having the same issue with podcasts downloading as .mpeg instead of .mp3 so I’m having to rename each file as they download. Is there anyway to for the podcasts to download as .mp3? Thanks

**Comment by u175** [comment]
I’m still having the same issue with podcasts downloading as .mpeg instead of .mp3 so I’m having to rename each file as they download. Is there anyway to force the podcasts to download as .mp3? Thanks

**Comment by SamTV12345** [comment]
@u175 I merged the pull request. This is fixed now.

**Comment by u175** [comment]
Amazing thank you so much!
