### ISSUE TITLE
Display error when we add a new podcast

### ISSUE THREAD

**Issue by bastgau** [SamTV12345/PodFetch#379]
### Describe the bug

Hello.

When we add a new podcast using an url, the title displayed in the popup is missing. Same error when an episode is downloaded.

Thanks for your work.

<img width="392" alt="Capture d’écran 2023-11-04 à 18 14 10" src="https://github.com/SamTV12345/PodFetch/assets/4788354/44451b77-5be8-4f70-844b-f578c95cdeb1">

### Reproduction

Add a new podcast using an url.

### System Info

```Shell
Lastest docker version / Language = French
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by bastgau** [comment]
Merci

**Comment by SamTV12345** [comment]
De rien 😄.
