### ISSUE TITLE
gpodder sync is incomplete

### ISSUE THREAD

**Issue by jpjonte** [SamTV12345/PodFetch#382]
### Describe the bug

After setting up gpodder sync using AntennaPod I noticed that episode progress wasn't being synced.

A quick look at the code confirms this part is unfinished:

https://github.com/SamTV12345/PodFetch/blob/3c5fabb5f9f061e9fd61807cf0a728de55c4489f/src/gpodder/episodes/gpodder_episodes.rs#L95-L110

Having this sync would be really great, because then I could seamlessly switch between AntennaPod and PodFetch depending on what device I'm using. (Which is pretty much the reason I set up PodFetch in the first place 😄 )

I *could* have a go at implementing this myself, but no promises, I haven't done much rust development yet 😅 

### Reproduction

Sync with AntennaPod. Check episodes/database. There are no new PodcastHistoryItems.

### System Info

```Shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 94.70 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
    Yarn: 3.6.0 - /opt/homebrew/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
    pnpm: 7.29.1 - /opt/homebrew/bin/pnpm
  Browsers:
    Firefox: 119.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
It is fixed for now. After you deploy the new vrsion you need to run `podfetch migration episodes` in order to show the antennapod episode progress in your web view.
