### ISSUE TITLE
Strange behaviour with the podcast "SWR2 Wissen"

### ISSUE THREAD

**Issue by update-freak** [SamTV12345/PodFetch#385]
### Describe the bug

I added the podcast "SWR2 Wissen".

1. In the settings for podcasts there was added the item "SWR2 Wissen".
2. Then I moved to the overview page, but there was no icon for "SWR2 Wissen".
3. After that I moved back to the settings for podcasts. The entry for "SWR2 Wissen" is not there anymore (like in step 1)

see screenshots:

![2023-11-05 16_18_30-Podfetch](https://github.com/SamTV12345/PodFetch/assets/40196995/7a380818-a2e6-4146-9028-543b6795d95d)
![2023-11-05 16_18_54-Podfetch](https://github.com/SamTV12345/PodFetch/assets/40196995/4e6e4b39-e44f-42b1-bf14-1d6b5d165b51)
![2023-11-05 16_19_20-](https://github.com/SamTV12345/PodFetch/assets/40196995/9c39fb56-ac2c-41cd-8dde-f6421c3fde11)

### Reproduction

1. Add "SWR2 Wissen" 2. Check overview page if the icon of SWR2 Wissen is there

### System Info

```Shell
Chrome: 119
PodFetch: 4.2.2
System: DSM 7.2.1 on Docker on Synology NAS
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Thanks for the issue. This is indeed a bug when handling this podcast. I'll have a look at the RSS feed.

**Comment by SamTV12345** [comment]
Fixed. One of the podcast episodes didn't have a title.
