### ISSUE TITLE
Push container images to GHCR

### ISSUE THREAD

**Issue by onedr0p** [SamTV12345/PodFetch#389]
### Clear and concise description of the problem

Dockerhub has pull rate limits and have also shown in recent history to be pretty hostile to open source developers.

### Suggested solution

Please consider publishing the container image to Github's container registry (GHCR) as well. Publishing the container image to GHCR also is integrated with Github and is shown under the packages section on your repo's landing page.

Thanks!

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by SamTV12345** [comment]
@onedr0p Thanks for the issue. I added ghcr as a target for the docker images and they will appear now for every release also on GitHub.

**Comment by onedr0p** [comment]
Hi @SamTV12345, you might need to change the visibility of the package to public, I don't see anything under https://github.com/SamTV12345?tab=packages or https://github.com/SamTV12345/PodFetch/pkgs/container/podfetch

**Comment by SamTV12345** [comment]
Thanks for the notice. I changed the visibility of the package.

**Comment by onedr0p** [comment]
Perfect, thanks!

<img width="461" alt="image" src="https://github.com/SamTV12345/PodFetch/assets/213795/23968fbc-6c60-405a-8bdd-06d9561a3c4b">

**Comment by SamTV12345** [comment]
Haha nice. You're welcome
