### ISSUE TITLE
Unify container builds for sqlite and postgres images and publish semver tags.

### ISSUE THREAD

**Issue by onedr0p** [SamTV12345/PodFetch#396]
### Clear and concise description of the problem

I am curious what is the reason for splitting these up into two separate containers and if there's any plan to unify these images into one? I am not a rust programmer so pardon me if there's a reason I cannot see. I also selfhost https://github.com/atuinsh/atuin which is also rust and has a single container that work with either postgres or sqlite.

Also, I've been using podfetch but would love it if the container tagging could adhere to semver. What I mean is that if the container tagging could be `v4.3.0` instead of `v4.3.0-postgres-b6d7f1b`. This helps with automation tools like renovate that can scan the container registry and discover new versions.

### Suggested solution

1. Build a single container image for both sqlite and postgres
2. Adhere container tags to [semantic versioning](https://semver.org/)

### Alternative

Thanks for this wonderful app, there are really great design choices you have made that truely kick ass.

### Additional context

Feel free to convert this into a discussion if you think that's a better way to discuss.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by SamTV12345** [comment]
Good idea. It is unfortunately a bit complicated. Rust is statically typed so it needs to know everything at compile time. Vaultwarden solves that with an insane macro rule. Unfortunately when I was asking them for help back then I was reminded that it is a GPL project and if I take any piece of code of vaultwarden I also have to obey to the GPL license which I don't want to.

So I need to come up with my own solution but generally speaking a unified Docker image would save me so much time/complicated pipelines/headaches in general.

**Comment by onedr0p** [comment]
Good to know you're thinking about that, have you looked at how https://github.com/atuinsh/atuin has handled it? That is a MIT licensed.

**Comment by SamTV12345** [comment]
I'll have a closer look tomorrow. There are two different "ORMs" in the Rust world. SQLX and Diesel. Seems like the creator of attain used SQLX and PodFetch is based on Diesel.
