### ISSUE TITLE
Add metadata tags to downloaded mp3 files

### ISSUE THREAD

**Issue by dancs-dev** [SamTV12345/PodFetch#407]
### Clear and concise description of the problem

As someone who is using PodFetch to automatically download podcasts to a directory which I am then syncing to my phone using Syncthing and listening using VLC, I would like to ensure podcasts have an artist/album assigned to them, so they are not in a generic uncatagorised album. 

### Suggested solution

Automatically populate data if it does not already exist and it is available from iTunes, including:

- `Artist`, e.g., 'The WAN Show'
- `Album`, e.g., 'The WAN Show'
- `Genre`, e.g., 'Podcast'
- `Date`, e.g., 2023
- `Track number` (if possible?), 110

### Additional context

I think `Artist` and `Album` would be most useful to populate.

As an example of a podcast on iTunes with metadata correctly set in the mp3 itself: The Homelab Show

As an example of a podcast on iTunes with metadata incorrectly set (absent) in the mp3 itself: The WAN Show

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by SamTV12345** [comment]
Seems to be pretty easy to accomplish with this crate https://crates.io/crates/id3. I'll implement this tomorrow.

**Comment by bastgau** [comment]
Very good idea !

**Comment by bastgau** [comment]
You could add the following tags :

Cover / picture / album art
URL = to add the internal podfech url
Comment = to add more information

**Comment by SamTV12345** [comment]
Closed. I implemented it just like you described it.

**Comment by dancs-dev** [comment]
Thanks very much - working perfectly for me
