### ISSUE TITLE
gPodder compatible API

### ISSUE THREAD

**Issue by alexanderadam** [SamTV12345/PodFetch#41]
### Clear and concise description of the problem

Users who want to use their mobile or desktop clients (like [AntennaPod](https://antennapod.org/) [the Podcast app for Garmin watches](https://github.com/lucasasselli/garmin-podcasts#garmin-podcasts) or the [gPodder desktop application](https://gpodder.github.io/)) often want to have a possibility to sync the listening state across all devices.
gPodder solved exactly this, but it's old Python code and the official instance is often so slow that the devices are running into timeouts.

If PodFetch could replace that bottleneck by providing [a compatible API](https://gpoddernet.readthedocs.io/en/latest/api/index.html), then people would have less to worry about (furthermore gPodder causes faulty behaviour on various clients [like duplicated subscriptions if a subscription URL changed](https://github.com/AntennaPod/AntennaPod/issues/2214)).

**PS:** This one is probably a difficult issue but it will give obvious benefits

### Suggested solution

[A gPodder compatible API interface](https://gpoddernet.readthedocs.io/en/latest/api/index.html).

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by SamTV12345** [comment]
Thanks for the issue. I have a look at a later point of the development or maybe someone else wants to contribute. The API seems to be pretty much work.  My main goal is to get it stable and also include a user management. Currently everyone shares the same favorites and watch logs. This is not very ideal in a multi user setup like Keycloak/Basic Auth.

**Comment by alexanderadam** [comment]
It definitely _is_ a lot of work.

Thank you for your work by the way.
And you're really amazingly fast with your responses.

**Comment by SamTV12345** [comment]
I'm starting to work on this task. I hope I can get this issue done in 2-3 months. Other than that if someone else wants to contribute just choose a topic.

**Comment by SamTV12345** [comment]
@alexanderadam Do you have a spare account for gpodder.net? Seems like gpodder.net is broken since August 2022 and no new users can be created. If so you can message me on Mastodon @samuel@mastodon.schwanzer.online

**Comment by alexanderadam** [comment]
Maybe it would be more reliable to use a local instance (i.e. [this](https://codeberg.org/atomdmac/mygpo-docker) or [this](https://github.com/xthursdayx/gpodder-docker)).

**PS:** the official instance being broken is probably even more an argument to have a nice selfhosted alternative I guess

**Comment by SamTV12345** [comment]
Good to know. I stumbled across multiple posts where users complain about the 500 since August 2022. The first one crashes on my system and the second is the client. I need the server.

**Comment by alexanderadam** [comment]
> The first one crashes on my system

I guess then it would help to [create an issue with the details](https://codeberg.org/atomdmac/mygpo-docker/issues/new).
Since I guess that there's at least some error message, right?

There's also [an open issue for an official Docker container](https://github.com/gpodder/mygpo/issues/818).

**Comment by SamTV12345** [comment]
I am in the process of creating a Codeberg account. Seems like the email server takes up to 3 hours. I'll create an issue once I'm registered. 

How does AntennaPod sync with GPodder. Is this periodic? When I play/pause a downloaded podcast it doesn't send anything to the server. Do I have to press on Sync now for playtime to be updated.

**Comment by SamTV12345** [comment]
Thanks for mentioning my project. I am close to finishing the integration. It already works as a standalone. I only need to connect the ui play/stop positions to the gpodder play actions. I am very optimistic that I should be able to finish this this weekend.

**Comment by keunes** [comment]
Hi @SamTV12345,

From AntennaPod I'm involved in a new initiative to make an open (source) podcast API standard: Open Podcast API. The goal is to enable different clients and servers to sync easily subscriptions, listening progress, etc. The Subscriptions endpoint is currently [taking shape](https://github.com/OpenPodcastAPI/api-specs/pull/26).

As our shared userbase seems to have some interest in linking up Podgrab and AntennaPod, you're warmly invited to join us in co-creating/shaping the specs. We're meeting in the matrix channel mentioned [here](https://github.com/orgs/OpenPodcastAPI/discussions/1#discussioncomment-4231919) and meeting in a video call every 2nd Tuesday of the month.

Hit me up on [my username]@mailbox.org if you have any questions.
