### ISSUE TITLE
Install without docker?

### ISSUE THREAD

**Issue by lgwapnitsky** [SamTV12345/PodFetch#432]
Is it possible to install without docker? Are there instructions on how to do so?

Thank you

**Comment by SamTV12345** [comment]
Hi. You can easily install PodFetch without Docker. You just go to the release tab, select podfetch-<your-desired-os>.zip
1. Unzip the archive
2. Copy it to your server
3. Create a bash script that first sets the documented environment variables and then calls the binary.
