### ISSUE TITLE
Sync through GPodder API using AntennaPod fails

### ISSUE THREAD

**Issue by jgkawell** [SamTV12345/PodFetch#440]
### Describe the bug

I set up AntennaPod to sync with PodFetch (Postgres database) using the GPodder API as described by the docs. The login works just fine but whenever I try to sync through the app it fails. Looking at the logs I see this:

```
podfetch-podfetch-1  | thread 'actix-rt|system:0|arbiter:0' panicked at src/models/subscription.rs:153:26:
podfetch-podfetch-1  | called `Result::unwrap()` on an `Err` value: DatabaseError(Unknown, "column \"deleted\" is of type timestamp without time zone but expression is of type integer")
podfetch-postgres-1  | 2023-11-17 04:49:52.200 UTC [233] ERROR:  column "deleted" is of type timestamp without time zone but expression is of type integer at character 109
podfetch-postgres-1  | 2023-11-17 04:49:52.200 UTC [233] HINT:  You will need to rewrite or cast the expression.
podfetch-postgres-1  | 2023-11-17 04:49:52.200 UTC [233] STATEMENT:  INSERT INTO "subscriptions" ("username", "device", "podcast", "created", "deleted") VALUES ($1, $2, $3, $4, $5)
```

Is this an error in my set up? Is there a migration I should run first? Or is there a bug in the GPodder API implementation? Happy to give more info if needed. Thanks!

### Reproduction

Run PodFetch with Postgres backend. Try to sync using AntennaPod. See error in PodFetch logs.

### System Info

```Shell
Docker (using the provided Docker Compose example), running the `latest` image and the Postgres database.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AFiesselmann** [comment]
Same setup and same problem here.

**Comment by SamTV12345** [comment]
Found the error. Should be working again with the latest image. Thanks for reporting this issue.

**Comment by jgkawell** [comment]
Works now. Thanks for the quick fix!
