### ISSUE TITLE
Speed up OPML import

### ISSUE THREAD

**Issue by Ethanol6** [SamTV12345/PodFetch#443]
### Clear and concise description of the problem

When importing by OPML podcasts are added consecutively AFTER the initial podcast download limit has been reached for each podcast. This can mean several minutes elapse between each podcast addition, or hours for a full OPML import to occur.

### Suggested solution

Perhaps the episode download can happen asynchronously or just after all the podcasts have been added. 

There could be different download schemes on top of this: 
- PodFetch could fill up the episode limit one podcast at a time.
- PodFetch could download 1 (or X number) episode for every podcast, repeating until the episode limit is reached.
    - Having simultaneous downloads would be helpful.
    - This way you'll have at least 1 episode for every podcast downloaded soon after import.

### Alternative

Alternatively, a new option could be added to manually ask PodFetch to download the X most recent episodes of podcasts. So when importing an OPML, you could set the initial episode download limit to 0. Then afterwards, manually have PodFetch download X number of recent episodes for podcasts.

There could be an option to download X number of episodes for ALL podcasts, active podcasts, or a selected list of podcasts.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Ethanol6** [comment]
Possible overlap with #429

**Comment by SamTV12345** [comment]
This is closed. Per OPML import podcast a new thread is spawned. So at max (theoretically) it should now take just the time of the longest podcast download and not the accumulation of all podcasts.
