### ISSUE TITLE
SERVER_URL setting not respecting paths

### ISSUE THREAD

**Issue by frap129** [SamTV12345/PodFetch#45]
### Describe the bug

Setting a path in the SERVER_URL variable doesn't allow access on that path.

**What I did:**
1. Created container with the supplied docker compose file
2. add `container_name: podfetch` to make container reachable by name
3. Setup subdomain reverse proxy with caddy 
```
podfetch.my.tld {
  import global_headers
  import root_tls
  reverse_proxy podfetch:8000
}
```
4. PodFetch is accessible from https://podfetch.my.tld and works
5. Setup subpath reverse proxy in caddy
```
my.tld {
  import global_headers
  import root_tls
  ... # other paths
  reverse_proxy /podfetch* podfetch:8000
}
```
6. Set `SERVER_URL=http://localhost:8000/podfetch` in compose file, recreate container
7. PodFetch is NOT accessible from https://my.tld/podfetch/, but is still accessible from https://podfetch.my.tld/ (without the path)

Expected result is that podfetch is accessible from both URLs, with the subdomain version redirecting with the path in place.

I also tried with SERVER_URL set to
- http://podfetch:8000/podfetch
- http://my.tld/podfetch
- https://my.tld/podfetch
- http://my.tld:8000/podfetch

### Reproduction

See above

### System Info

```Shell
Using latest docker image as of the time this issue was opened
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wtanksleyjr** [comment]
I did this too. You need to add a trailing slash to the SERVER_URL, because
the code blindly appends "ws" to that URL for the websockets.

-Wm

**Comment by frap129** [comment]
> I did this too. You need to add a trailing slash to the SERVER_URL, because the code blindly appends "ws" to that URL for the websockets.

I added the trailing slash, and redeployed the container. Still nothing. The container log says `Public server url: http://localhost:8000/podfetch/` so I know the variable is set correctly, but it is not accessible from that path.

**Comment by SamTV12345** [comment]
The last slash should not matter anymore. It is added automatically if not present. The websocket is only accessible from the SERVER_URL. What do you get when navigating to http://localhost:8000/podfetch?

**Comment by frap129** [comment]
> The last slash should not matter anymore. It is added automatically if not present. The websocket is only accessible from the SERVER_URL. What do you get when navigating to http://localhost:8000/podfetch?

This is running on a headless server, so I cant access localhost directly, but navigating to  http://<server ip>:8000/podfetch brings up a blank page, web console says 404. http://<server ip>:8000 (without the path) brings up podfetch.

**Comment by SamTV12345** [comment]
What happens on http://server-up:8000/podfetch/

**Comment by frap129** [comment]
> What happens on http://server-up:8000/podfetch/
Blank page, same as without the trailing slash. I also tried http://server-ip:8000/podfetch/ui/ just to see if it was the redirect failing, still a blank page.

**Comment by SamTV12345** [comment]
Ok. I guess I need Caddy? Do you have a ready to use docker-compose and could give me your subdirectory routing config? I haven't used caddy before.

**Comment by frap129** [comment]
> Ok. I guess I need Caddy? Do you have a ready to use docker-compose and could give me your subdirectory routing config? I haven't used caddy before.

When accessing it by IP, it was not going through caddy. This seems to be an issue with podfetch, but if you want to test with caddy you can use the following compose setup:
```
version: "3.8"

services:
  caddy:
    image: caddy:2-alpine
    restart: always
    container_name: caddy
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ${CONFIG_DIR:-.}/caddy/config/:/config/
      - ${CONFIG_DIR-.}/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ${CONFIG_DIR-.}/caddy/data:/data
```
and add the following to your Caddyfile:
```
your.tld {
    reverse_proxy /podfetch* podfetch:8000
}
```
Replace `your.tld` with your domain, with dns records pointing it to the ip of your caddy host. Also replace `podfetch:8000` with the network accessible address of your podfetch instance

**Comment by SamTV12345** [comment]
So SERVER_URL should be able to host the api at a given prefix? I guess accessing by /Podfetch and / at the same time is not possible.

**Comment by frap129** [comment]
> So SERVER_URL should be able to host the api at a given prefix? I guess accessing by /Podfetch and / at the same time is not possible. And you also have a problem with the UI part. I use static assets that require the server and the ui to be at a preconfigured route.

My goal was to have all of podfetch be under the subpath in the domain, so all URLs for podfetch would be
 `https:/my.tld/podfetch/*`
Many other selfhostable services refer to this as a "Base URL", is SERVER_URL not intended to work that way?

**Comment by SamTV12345** [comment]
Do you know a project that has it implemented that way? SERVER_URL is currently only to get the correct prefix for accessing the API from the UI.

**Comment by wtanksleyjr** [comment]
```
your.tld {
    reverse_proxy /podfetch* podfetch:8000
}
```

I use Caddy, but always to a subdomain, so I never use those URL filters. But my config looks similar to yours.

```
@podfetch host podfetch.tanksleyjr.us
handle @podfetch {
        basicauth * {   myname i'm-totally-going-to-paste-in-my-password-here     }
        reverse_proxy http://127.0.0.1:8001
}
```

I don't know how Caddy handles websockets, but I know this works.

**Comment by frap129** [comment]
> Do you know a project that has it implemented that way? SERVER_URL is currently only to get the correct prefix for accessing the API from the UI.

All of the *arr projects implement it that way, also navidrome, jellyfin, ombi do. Those are all under subpaths on my domain,  was hoping to add this to the list 

> I don't know how Caddy handles websockets, but I know this works.

Caddy handles websockets automatically. Vaultwarden also uses websockets and I didn't have to do anything special to make that work

**Comment by SamTV12345** [comment]
Found a similar issue on Navidrome: https://github.com/navidrome/navidrome/issues/103

**Comment by SamTV12345** [comment]
@wtanksleyjr @frap129 Could you please change your tag to develop and pull that docker image. After that change the SERVER_URL to your desired subpath and go to the web browser. It is important to reload the page with pressed shift key. Does that solve your issue?

**Comment by SamTV12345** [comment]
Great that this is solved now. In the linked issue the maintainer came to the same conclusion that it wouldn't be possible to change the path of the frontend. After that he linked a pull request where he solved the problem in go by replacing every link in the generated web files with the current base url. That worked without a problem for me. The most difficult task was to port that solution to Rust.
