### ISSUE TITLE
Gpoddersync doesn't sync with AntennaPod

### ISSUE THREAD

**Issue by stephanvierkant** [SamTV12345/PodFetch#453]
### Describe the bug

I'm running PodFetch on a Synology NAS with Docker. I've managed to login on AntennaPod, syncing looks successful but no data from Podfetch is being loaded in AntennaPod.

I've added a podcast in AntennaPod and I can find that entry in the `subscriptions` table, but I don't see it online.

Please let me know how I can provide more debug data.

### Reproduction

Antennapod -> login -> force sync: no error, but no data synced

### System Info

```Shell
## Environment
Android version: 14
OS version: 5.10.157-android13-4-00003-gdfb1120f912b-ab10994928
AntennaPod version: 3.1.2
Model: Pixel 6 Pro
Device: raven
Product: raven

## Crash info
Time: 21-11-2023 12:33:19
AntennaPod version: 3.1.2

## StackTrace

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Throwable.getMessage()' on a null object reference
	at de.danoeh.antennapod.fragment.preferences.synchronization.GpodderAuthenticationFragment.lambda$setupLoginView$4(GpodderAuthenticationFragment.java:143)
	at de.danoeh.antennapod.fragment.preferences.synchronization.GpodderAuthenticationFragment.$r8$lambda$PblfpjkWv1kDOd7pkvsz-m1lYHc(GpodderAuthenticationFragment.java:0)
	at de.danoeh.antennapod.fragment.preferences.synchronization.GpodderAuthenticationFragment$$ExternalSyntheticLambda3.accept(R8$$SyntheticClass:0)
	at io.reactivex.internal.observers.CallbackCompletableObserver.onError(CallbackCompletableObserver.java:64)
	at io.reactivex.internal.operators.completable.CompletableObserveOn$ObserveOnCompletableObserver.run(CompletableObserveOn.java:87)
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```
```


### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
> ### Describe the bug
> I'm running PodFetch on a Synology NAS with Docker. I've managed to login on AntennaPod, syncing looks successful but no data from Podfetch is being loaded in AntennaPod.
> 
> I've added a podcast in AntennaPod and I can find that entry in the `subscriptions` table, but I don't see it online.
> 
> Please let me know how I can provide more debug data.
> 
> ### Reproduction
> Antennapod -> login -> force sync: no error, but no data synced
> 
> ### System Info
> ```shell
> ## Environment
> Android version: 14
> OS version: 5.10.157-android13-4-00003-gdfb1120f912b-ab10994928
> AntennaPod version: 3.1.2
> Model: Pixel 6 Pro
> Device: raven
> Product: raven
> 
> ## Crash info
> Time: 21-11-2023 12:33:19
> AntennaPod version: 3.1.2
> 
> ## StackTrace
> 
> java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Throwable.getMessage()' on a null object reference
> 	at de.danoeh.antennapod.fragment.preferences.synchronization.GpodderAuthenticationFragment.lambda$setupLoginView$4(GpodderAuthenticationFragment.java:143)
> 	at de.danoeh.antennapod.fragment.preferences.synchronization.GpodderAuthenticationFragment.$r8$lambda$PblfpjkWv1kDOd7pkvsz-m1lYHc(GpodderAuthenticationFragment.java:0)
> 	at de.danoeh.antennapod.fragment.preferences.synchronization.GpodderAuthenticationFragment$$ExternalSyntheticLambda3.accept(R8$$SyntheticClass:0)
> 	at io.reactivex.internal.observers.CallbackCompletableObserver.onError(CallbackCompletableObserver.java:64)
> 	at io.reactivex.internal.operators.completable.CompletableObserveOn$ObserveOnCompletableObserver.run(CompletableObserveOn.java:87)
> 	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
> 	at android.os.Handler.handleCallback(Handler.java:958)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loopOnce(Looper.java:205)
> 	at android.os.Looper.loop(Looper.java:294)
> 	at android.app.ActivityThread.main(ActivityThread.java:8177)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
> ```
> 
> ```
> 
> 
> ### Used Package Manager
> 
> n/a
> 
> ### Validations
> 
> - [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
> - [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
> - [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
> - [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
> - [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
> ```

You need to also add it in PodFetch. This is required because not anyone should be able to upload a podcast to the server. Only the administrator should be able to do so.

**Comment by stephanvierkant** [comment]
But the user is an admin. Why doesn't get AntennaPod all podcasts?

Let's explain my use case: I've got 3 Android devices (phone, two tablets), a Synology NAS  and a desktop. I want to sync subscriptions and listening status between the 3 devices (and use the web application to listen on a desktop).

Now I've installed AntennaPod on my tablet, how do I get my subscriptions?

**Comment by SamTV12345** [comment]
Good idea. I could auto download the podcasts if you are an administrator.  

You should be able to add them all to AntennaPod and sync them through PodFetch. That should definetely work. I haven't tried AntennaPod with multiple devices. It should be add everything as one device in AntennaPod and sync through GPodder PodFetch.

**Comment by stephanvierkant** [comment]
Basicly I want to sync subscriptions between devices/apps so I don't need to add/delete subscriptions on a mobile device.

I'm also using Syncthing on those devices, so I can manage files (photos, downloads) on my desktop or NAS. In my opinion I shouldn't need to touch my phone when I'm home, because I've got tablets and a desktop with a giant screen.

**Comment by SamTV12345** [comment]
> Basicly I want to sync subscriptions between devices/apps so I don't need to add/delete subscriptions on a mobile device.
> 
> I'm also using Syncthing on those devices, so I can manage files (photos, downloads) on my desktop or NAS. In my opinion I shouldn't need to touch my phone when I'm home, because I've got tablets and a desktop with a giant screen.

I agree. Can you please try to add the exact podcast via the web UI and add it on one of your Android devices? That way you should simply login into the other two devices and have them synced.

**Comment by update-freak** [comment]
I have exactly the same situation / aim (sync between multiple devices with AntennaPod and see the listen-Status in the Web-UI) Here I described the issue: https://github.com/SamTV12345/PodFetch/issues/384

But I can confirm that the sync between devices (e.g. sync between two android-smartphones with AntennaPod configured with the same device-name will work). Web-UI is also not synced with the Podcasts in AntennaPod

**Comment by SamTV12345** [comment]
Great to hear that. At least that works. I'm currently debugging why it isn't working. Seems to be challenging as the API seems to be working just fine.

**Comment by SamTV12345** [comment]
> I have exactly the same situation / aim (sync between multiple devices with AntennaPod and see the listen-Status in the Web-UI) Here I described the issue: #384
> 
> But I can confirm that the sync between devices (e.g. sync between two android-smartphones with AntennaPod configured with the same device-name will work). Web-UI is also not synced with the Podcasts in AntennaPod

Hopefully it works now flawlessly I hope. I simplified the watch logs. Could you try the latest dev image?

**Comment by update-freak** [comment]
Sure. Where I can find the latest dev image?

**Comment by SamTV12345** [comment]
> Sure. Where I can find the latest dev image?

It is named dev. If you also want to merge in the webview watch logs you need to go over release 4.5.0 and do `docker exec podfetch /app/podfetch migrate watchlog`

**Comment by update-freak** [comment]
I did a clean install with the docker compose below, but I can not add a user with /app/podfetch users add
Normally there was a question about the passwort and the role, but after typing a name nothing happens after confirming with enter:

`version: '3.9'
services:
  podfetch:
    image: samuel19982/podfetch:dev
    container_name: PodFetch
    user: 1026:100
    ports:
      - 4135:8000
    volumes:
      - /volume1/docker/podfetch:/app/podcasts:rw
    environment:
      - POLLING_INTERVAL=300
      - SERVER_URL=https://podfetch.blabla.dynv6.net
      - DATABASE_URL=postgresql://postgres:changeme@postgres/podfetch
      - BASIC_AUTH=true
      - USERNAME=Felix
      - PASSWORD=PASSWORT
      - GPODDER_INTEGRATION_ENABLED=true
    restart: always

  postgres:
    image: postgres
    container_name: PodFetch-DB
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "podfetch", "-U", "postgres"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: podfetch
    volumes:
      - /volume1/docker/podfetch/db:/var/lib/postgresql/data:rw
    restart: always`


![2023-11-26 14_13_24-NAS - Synology DiskStation](https://github.com/SamTV12345/PodFetch/assets/40196995/16fa73fb-a9d6-487a-b375-421a1be55932)

**Comment by SamTV12345** [comment]
Weird. It worked for me at least: 
![image](https://github.com/SamTV12345/PodFetch/assets/40429738/0ed2ad30-d9c8-482a-b3ee-f400da8237a7)

I used your docker-compose.yml

**Comment by update-freak** [comment]
I tried it again -> this time in Portainer directly -> here it works.
In Synology directly (which i did before) it did not work. Strange, but I'm happy that I could add a user.
I also can confirm that the login with the extra created user work.
Let's see if the sync also work :)

**Comment by stephanvierkant** [comment]
> > Sure. Where I can find the latest dev image?
> 
> It is named dev. If you also want to merge in the webview watch logs you need to go over release 4.5.0 and do `docker exec podfetch /app/podfetch migrate watchlog`

Both dev and latest are broken for me. With this command I get 'command not found'. AntennaPod now says '404 not found' when trying to login.

**Comment by SamTV12345** [comment]
I forgot to mention that you need this specific version of the Docker image (https://hub.docker.com/layers/samuel19982/podfetch/v4.5.0-53d2ddd/images/sha256-57de214298c08dd9d08f34518eb3ac42f329c1b129f031858d5cbfd430c3f058?context=explore). Sorry for the confusion.

**Comment by stephanvierkant** [comment]
docker exec podfetch /app/podfetch migrate watchlog
> Debug file located at /home/rust/src/target/x86_64-unknown-linux-musl/release/build/podfetch-87f0020607b2a281/out/built.rs
> Starting from command line
> 2023-11-27T11:13:11 ❌ - Command not found
>

**Comment by stephanvierkant** [comment]
> Debug file located at /home/rust/src/target/x86_64-unknown-linux-musl/release/build/podfetch-87f0020607b2a281/out/built.rs
> Starting from command line
> 2023-11-27T15:27:21 ❌ - Database error: no such table: podcast_history_items
> thread 'tokio-runtime-worker' panicked at src/models/podcast_history_item.rs:247:14:
> called `Result::unwrap()` on an `Err` value: DatabaseError(DatabaseError(Unknown, "no such table: podcast_history_items"))
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> thread 'main' panicked at src/main.rs:160:14:
> TODO: panic message: JoinError::Panic(Id(3), ...)
>

**Comment by SamTV12345** [comment]
You need to add your required config to it. So it is best to replace the docker-compose PodFetch latest image with the version I posted above.

**Comment by stephanvierkant** [comment]
```
services:
  podfetch:
    container_name: podfetch
    image: samuel19982/podfetch:v4.5.0-53d2ddd
    # ....
```
I purged and restarted the container and then `docker exec podfetch /app/podfetch migrate watchlog`:

> Debug file located at /home/rust/src/target/x86_64-unknown-linux-musl/release/build/podfetch-87f0020607b2a281/out/built.rs
> Starting from command line
> 2023-11-27T20:43:41 ❌ - Database error: relation "podcast_history_items" does not exist
> thread 'tokio-runtime-worker' panicked at src/models/podcast_history_item.rs:247:14:
> called `Result::unwrap()` on an `Err` value: DatabaseError(DatabaseError(Unknown, "relation \"podcast_history_items\" does not exist"))
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> thread 'main' panicked at src/main.rs:160:14:
> TODO: panic message: JoinError::Panic(Id(3), ...)

**Comment by SamTV12345** [comment]
> ```
> services:
>   podfetch:
>     container_name: podfetch
>     image: samuel19982/podfetch:v4.5.0-53d2ddd
>     # ....
> ```
> 
> I purged and restarted the container and then `docker exec podfetch /app/podfetch migrate watchlog`:
> 
> > Debug file located at /home/rust/src/target/x86_64-unknown-linux-musl/release/build/podfetch-87f0020607b2a281/out/built.rs
> > Starting from command line
> > 2023-11-27T20:43:41 ❌ - Database error: relation "podcast_history_items" does not exist
> > thread 'tokio-runtime-worker' panicked at src/models/podcast_history_item.rs:247:14:
> > called `Result::unwrap()` on an `Err` value: DatabaseError(DatabaseError(Unknown, "relation "podcast_history_items" does not exist"))
> > note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> > thread 'main' panicked at src/main.rs:160:14:
> > TODO: panic message: JoinError::Panic(Id(3), ...)

Seems like your database is already migrated. So you should be able to use the latest PodFetch version without a problem.

**Comment by update-freak** [comment]
When will you include the fixes from the dev-version in the latest version?

**Comment by SamTV12345** [comment]
@update-freak Wasn't this fixed and merged into the non develop images?

**Comment by update-freak** [comment]
Maybe the Problem was that I changed to latest and not to v4.5.0-53d2ddd?

![Screenshot_20231225_083634_Chrome](https://github.com/SamTV12345/PodFetch/assets/40196995/310cdf45-4302-4734-b425-edc665901fd4)

**Comment by BadCo-NZ** [comment]
No syncing between AntennaPod and PodFetch webUI is working in latest tagged version `4.6.1-b17ec94b`

**Comment by update-freak** [comment]
Can you try the latest version 4.6.1 (cba727cf9ea3, db0ade5ac26c, 67c882dd0d76)?
My Podfetch container was updated automatically via Watchtower at 2024-02-06 04:01:02 and there the sync is working.

**Comment by BadCo-NZ** [comment]
> Can you try the latest version 4.6.1 (cba727cf9ea3, db0ade5ac26c, 67c882dd0d76)? My Podfetch container was updated automatically via Watchtower at 2024-02-06 04:01:02 and there the sync is working.

Thanks, I will give that a try when I get home.

**Comment by BadCo-NZ** [comment]
Doesn't seem like it is syncing from Antennapod to the webGUI on version 4.6.1-cf56f686

I stopped the container and pruned images, containers and volumes but still got the same output:

```
podfetch$ docker exec podfetch /app/podfetch migrate watchlog
Debug file located at /home/rust/src/target/x86_64-unknown-linux-musl/release/build/podfetch-ab6fceef406eb240/out/built.rs
Starting from command line
2024-02-07T06:39:27 ❌ - Command not found
```
