### ISSUE TITLE
Error connecting to sqlite://./db/podcast.db with reason Invalid connection url for multiconnection

### ISSUE THREAD

**Issue by rogorido** [SamTV12345/PodFetch#465]
### Describe the bug

If I use your docker compose yaml file I get the following error:

Debug file located at /home/rust/src/target/aarch64-unknown-linux-musl/release/build/podfetch-b208581373e96388/out/built.rs
2023-12-03T20:08:15 ❌ - Error connecting to sqlite://./db/podcast.db with reason Invalid connection url for multiconnection

### Reproduction

Take the yaml file and do docker-compose up 

### System Info

```Shell
Ubuntu 22.04 on raspberry 4.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Did you set the id and guid correctly? This must match the permissions of the folder on the host system

**Comment by rogorido** [comment]
You're of course right. Sorry for the noise and thanks for the app!
