### ISSUE TITLE
How many podcasts/episodes to download when adding & how many keep on disk.

### ISSUE THREAD

**Issue by LordZeuss** [SamTV12345/PodFetch#508]
I believe a good feature would be, when adding new podcasts, allow the user to select how many previous podcasts/episodes to download, and could even have an alternative option to do it via date. Let the user define how many they want of that particular episode. Don't necessarily need to set it as universal, prefer per podcast, but that just an idea.

Say I add Podcast A. I want to only download the last 5 episodes as well as any new episodes from here on out as long as its active. 

OR

I add Podcast A. I only want this months podcasts, as well as any new episodes from here on out as long as its active.

OR

Just let me download every episode because I want them all.

--------------------

## Second Idea:

How many episodes to keep on disk at once.

Say I add Podcast A, and I wanted the most recent 5 episodes, as well as any going forward. But I set a max of no more than 10 episodes downloaded from this podcast at once. Delete the oldest first, no more than 10. Let the user select the amount of episodes max downloaded for that podcast.

Or simply unlimited and dont enforce a max.

**Comment by SamTV12345** [comment]
I think I have this partially implemented. If you have a look at the settings page I have an initial download threshhold that says: "Download x episodes initially". There is also the possibility to garbage collect old episodes. So if a new episode is downloaded, the oldest gets deleted so that over time the podcast folder doesn't explode. This could be linked to #428 as this introduces podcast level configuration. So podcast B and A can have different settings.

**Comment by LordZeuss** [comment]
> .

Thanks for the details. I do see on the setting page these options. 

This may be an ignorant question, my apologies in advance as I'm getting used to the app.

I can get to the settings page if I use the IP:port/ui/settings by manually typing /settings after /ui.

I do not see a settings button on the main page. I'm assuming I need to login of some sort or there is a tab I am missing. If I do not have any auth setup, and I cannot seem to find such a page (both login, or admin), how do I get to such a page? Am I required to add the /settings manually?

I am using a docker compose setup if it makes any difference.

**Comment by LordZeuss** [comment]
> I think I have this partially implemented. If you have a look at the settings page I have an initial download threshhold that says: "Download x episodes initially". There is also the possibility to garbage collect old episodes. So if a new episode is downloaded, the oldest gets deleted so that over time the podcast folder doesn't explode. This could be linked to #428 as this introduces podcast level configuration. So podcast B and A can have different settings.

> .

Thanks for the details. I do see on the setting page these options. 

This may be an ignorant question, my apologies in advance as I'm getting used to the app.

I can get to the settings page if I use the IP:port/ui/settings by manually typing /settings after /ui.

I do not see a settings button on the main page. I'm assuming I need to login of some sort or there is a tab I am missing. If I do not have any auth setup, and I cannot seem to find such a page (both login, or admin), how do I get to such a page? Am I required to add the /settings manually?

I am using a docker compose setup if it makes any difference.

**Comment by SamTV12345** [comment]
You need to click on the profile icon and then hit settings. Other than that. This is also implemented on a podcast level
