### ISSUE TITLE
Unable to connect to AntennaPod (code 403: Forbidden)

### ISSUE THREAD

**Issue by update-freak** [SamTV12345/PodFetch#509]
### Describe the bug

I created a new podfetch docker (deleted the old files) with this docker compose:
[docker-compose.txt](https://github.com/SamTV12345/PodFetch/files/13800680/docker-compose.txt)

In Portainer I created a new user "gpodder" with /app/podfetch users add with admin role
Then I logged in with this new user "gpodder" and added the podcasts from AntennaPod.

When I tried to use this account in AntennaPod I got this error
![Screenshot_20231231_092720_AntennaPod](https://github.com/SamTV12345/PodFetch/assets/40196995/b625447f-f587-4c3f-bc13-3660e000e0e1)

Podfetch version: 4.6.0

### Reproduction

add an user with " /app/podfetch users add" and try to login in AntennaPod

### System Info

```Shell
NA
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Thanks for the issue @update-freak 😀. That should be fixed.
