### ISSUE TITLE
401 error in AntennaPod when using local URLS

### ISSUE THREAD

**Issue by arcoast** [SamTV12345/PodFetch#520]
### Describe the bug

Since upgrading my docker image to one which incorporates this PR https://github.com/SamTV12345/PodFetch/pull/506 referencing this issue https://github.com/SamTV12345/PodFetch/issues/503 I'm getting a 401 when trying to update my subscriptions in AntennaPod which are using local URLs.

The full message displayed in AntennaPod is
```
Authentication error.  Make sure that username and password are correct.

Technical reason: 401

File URL:
https://podfetch.SERVER.COM/rss/52
```

I've generated an API key  as mentioned in the release note as shown below.

```bash
#:~# docker exec podfetch /app/podfetch users generate apiKey
Debug file located at /home/rust/src/target/x86_64-unknown-linux-musl/release/build/podfetch-01d9170df1a1162e/out/built.rs
Starting from command line
User management
2024-01-01T16:09:03 ℹ - Updating api key of user arcoast
```

but I can't see the mechanism of how this helps when using an external player like antennapod.

Personally I was fine with exporting the `/rss` URLs but understand why some might not be, but is it possible to toggle it.

For now I've rolled back my image to `v4.5.0-ecf1eed` which is working without issues for me.

Thanks

### Reproduction

See above

### System Info

```Shell
Not relevant
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
> ### Describe the bug
> Since upgrading my docker image to one which incorporates this PR #506 referencing this issue #503 I'm getting a 401 when trying to update my subscriptions in AntennaPod which are using local URLs.
> 
> The full message displayed in AntennaPod is
> 
> ```
> Authentication error.  Make sure that username and password are correct.
> 
> Technical reason: 401
> 
> File URL:
> https://podfetch.SERVER.COM/rss/52
> ```
> 
> I've generated an API key as mentioned in the release note as shown below.
> 
> ```shell
> #:~# docker exec podfetch /app/podfetch users generate apiKey
> Debug file located at /home/rust/src/target/x86_64-unknown-linux-musl/release/build/podfetch-01d9170df1a1162e/out/built.rs
> Starting from command line
> User management
> 2024-01-01T16:09:03 ℹ - Updating api key of user arcoast
> ```
> 
> but I can't see the mechanism of how this helps when using an external player like antennapod.
> 
> Personally I was fine with exporting the `/rss` URLs but understand why some might not be, but is it possible to toggle it.
> 
> For now I've rolled back my image to `v4.5.0-ecf1eed` which is working without issues for me.
> 
> Thanks
> 
> ### Reproduction
> See above
> 
> ### System Info
> ```shell
> Not relevant
> ```
> 
> ### Used Package Manager
> npm
> 
> ### Validations
> * [x]  Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
> * [x]  Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
> * [x]  Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
> * [x]  Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
> * [x]  The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

You should be able to access your files by appending ?apiKey=<my-api-key> to the rss feed url.

**Comment by arcoast** [comment]
That's quite a big ask when I export an OPML file with 60 different feeds.  Could that not be incorporated into the export process in Podfetch so it becomes seamless to the end user?

**Comment by SamTV12345** [comment]
Oh. So you want the OPML file to have the apiKey appended to it?

**Comment by arcoast** [comment]
Yeah, I think that makes sense, so this is a snippet from my OPML export using local URLS

```xml
		<outline text="An open show powered by community LINUX Unplugged takes the best attributes of open collaboration and turns it into a weekly show about Linux." title="LINUX Unplugged" type="rss" xmlUrl="https://podfetch.SERVER.COM/rss/1" />
```
I think either making the `/rss/~` endpoint optionally unprotected or exporting the local URLS with the API key inserted makes sense.  Otherwise in many ways the exported OPML file becomes a bit useless.

**Comment by SamTV12345** [comment]
> Yeah, I think that makes sense, so this is a snippet from my OPML export using local URLS
> 
> ```
> <outline text="An open show powered by community LINUX Unplugged takes the best attributes of open collaboration and turns it into a weekly show about Linux." title="LINUX Unplugged" type="rss" xmlUrl="https://podfetch.SERVER.COM/rss/1" />
> ```
> 
> I think either making the `/rss/~` endpoint optionally unprotected or exporting the local URLS with the API key inserted makes sense. Otherwise in many ways the exported OPML file becomes a bit useless.
> 
> So making that URL natively
> 
> ```
> <outline text="An open show powered by community LINUX Unplugged takes the best attributes of open collaboration and turns it into a weekly show about Linux." title="LINUX Unplugged" type="rss" xmlUrl="https://podfetch.SERVER.COM/rss/1?apiKey=xxxxxxxxxxxxx" />
> ```
> 
> would check the box of keeping the URLs secure but also preserve the functionality of local URL OPML exporting.

Should be fixed. Now all OPML feeds contain the API key of the currently logged in user.
