### ISSUE TITLE
Date format differs from example

### ISSUE THREAD

**Issue by chrisgalloway1** [SamTV12345/PodFetch#526]
### Describe the bug

Thanks for the work on this project - just discovered PodFetch and love that it's under active development and you seem very receptive to feedback!

A bug I encountered, though: When using the {date} replacer for episode naming, the sample episode format shows a format of '2023-12-24', but when the episode is saved, the actual format is different (at least in my testing of one podcast). The format of the episode on disk is (for example): '2023-12-24T01:00:00-08:00'.mp3.

I think either providing a {shortDate} option (that matches the sample episode format) or for the {date} replacer to be consistent with the example (I prefer the shorter date format in the example) would be potential fixes for this.

(Extra: I would love an option to not have single quotes/apostrophes in the folder/filenames, but maybe I'm just not seeing that option if it exists)

### Reproduction

Podcasts in this feed: https://www.podcastone.com/podcast?categoryID2=2336

### System Info

```Shell
Running this in Docker
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Thanks should be fixed for now.

**Comment by chrisgalloway1** [comment]
I appreciate the effort, but looks like it may still be an issue (not totally sure that I'm running the most up-to-date version, but I did update my docker container). I may not have been as descriptive - the issue is on the episode itself, and not the podcast - I think the fix might need to go in the perform_episode_variable_replacement function? (sorry, not that familiar with rust or I'd try to open a PR myself)

**Comment by SamTV12345** [comment]
Thanks for testing. Sorry I forgot that spot in the code 😄 .

**Comment by chrisgalloway1** [comment]
Works great, thanks!
