### ISSUE TITLE
Podcast not downloading

### ISSUE THREAD

**Issue by allthesebugsv2** [SamTV12345/PodFetch#539]
### Describe the bug

Alright, here is a new one: some podcasts throw an error when trying to download/refresh them. 
They were added fine initially. 

Unfortunately, that also means that auto-refresh/download of new episodes is broken for me. When one podcast breaks, the whole download task seems to abort.

Here is the error:
```
2024-01-10T12:38:02 ℹ️ - Refreshing podcast: Computer und Kommunikation - Sendung
2024-01-10T12:38:03 ℹ️ - Downloading podcast episode: Computer und Kommunikation 06.01.2023, komplette Sendung
thread '<unnamed>' panicked at src/service/download_service.rs:71:22:
called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Builder, source: RelativeUrlWithoutBase }     
```

Podcast URL: https://www.deutschlandfunk.de/computer-und-kommunikation-102.xml

### Reproduction

Add the above podcast and refresh it in podfetch

### System Info

```Shell
Docker build v4.6.0-80cf2407
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Thanks for the bug report. I found the error in the code and could resolve it. The podcast now downloads and redownloads without a problem. Sorry if this caused any inconvinience.
