### ISSUE TITLE
Listen to podcasts via Stream (not download) does not work

### ISSUE THREAD

**Issue by update-freak** [SamTV12345/PodFetch#544]
### Describe the bug

I'm logged in podfetch with my extra Account for gpodder (user role), but can not stream podcasts (podcast ist not downloaded) --> I click on the play-Button and have the bottom overview of the episode but nothing happens (I hear nothing).
![2024-01-13](https://github.com/SamTV12345/PodFetch/assets/40196995/10e22572-d4da-40b5-ae5a-31c80393b4b9)
As you can see from the screenshot that there is als a "test" remark in every episode (on the bottom) -> maybe this is a indication for the problem.
This problem happens also for the "normal" (not gpodder-User).

I imported the podcasts in the "normal" (not gpodder-User) and these podcasts are also listed in the gpodder-User.
(Synchronisation of open/finished episodes works with AntennaPod Sync with the gpodder-User).

docker compose attached:
[docker compose.txt](https://github.com/SamTV12345/PodFetch/files/13927491/docker.compose.txt)

Device:
Docker in Synology NAS (DSM)

### Reproduction

1. Create podfetch docker 2. create gpodder user with "/app/podfetch users add" 3. Login  in the normal user and add podcasts 4. Try to listen to these podcasts with the gpodder user

### System Info

```Shell
NA
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Can you please go to profile, generate an API key and then try again?

**Comment by update-freak** [comment]
Thank you very much. This solved the problem
