### ISSUE TITLE
Can't build on alpine 3.17 on an aarch64 server

### ISSUE THREAD

**Issue by jenningsloy318** [SamTV12345/PodFetch#554]
### Describe the bug

when build, it show error 
```
error: cannot produce proc-macro for `actix-macros v0.2.4` as the target `aarch64-unknown-linux-musl` does not support these crate types
````

### Reproduction

rebuilt it on an aarch64 alpline server

### System Info

```Shell
just run cargo build on aarch64 alpine server
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Maybe try `RUSTFLAGS="-C target-feature=+crt-static" cargo build`

**Comment by jenningsloy318** [comment]
tried this flag,same error,configured it in .cargo/config

**Comment by jenningsloy318** [comment]
I already tried, error still occurs 
```
builder:~/PodFetch$ RUSTFLAGS="-C target-feature=+crt-static" cargo build
error: cannot produce proc-macro for `actix-macros v0.2.4` as the target `aarch64-unknown-linux-musl` does not support these crate types
```

**Comment by SamTV12345** [comment]
I forgot that I also have a RPI4 with Alpine Linux. I was able to build it by installing
- apk add libgcc g++
- RUSTFLAGS="-C target-feature=-crt-static" cargo build

This has unfortunately the disadvantage that you need the libraries on the PodFetch host. I currently compile PodFetch on an x86 host for all platforms.

**Comment by jenningsloy318** [comment]
I can build the latest commit now, and start it normally, but seems there is something wrong
```
builder:~/PodFetch$ ./target/debug/podfetch 
Debug file located at /home/jenningsl/PodFetch/target/debug/build/podfetch-9f12e50cb96722df/out/built.rs

  ____           _ _____    _       _
 |  _ \ ___   __| |  ___|__| |_ ___| |__
 | |_) / _ \ / _` | |_ / _ \ __/ __| '_ \
 |  __/ (_) | (_| |  _|  __/ || (__| | | |
 |_|   \___/ \__,_|_|  \___|\__\___|_| |_|

        
2024-01-25T12:47:59 ℹ️ - Settings already present


2024-01-25T12:47:59 ℹ️ - starting 4 workers
2024-01-25T12:47:59 ℹ️ - Starting with the following environment variables:
2024-01-25T12:47:59 ℹ️ - Actix runtime found; starting in Actix runtime
2024-01-25T12:47:59 ℹ️ - Public server url: http://localhost:80/
2024-01-25T12:47:59 ℹ️ - Polling interval for new episodes: 300 minutes
2024-01-25T12:47:59 ℹ️ - Developer specifications available at http://localhost:80/swagger-ui/index.html#/
2024-01-25T12:47:59 ℹ️ - GPodder integration enabled: true
2024-01-25T12:47:59 ℹ️ - Podindex API key&secret configured: false
```

when I access via `http://localhost:80/`, it show error that can't connect
```
curl http://192.168.122.48
curl: (7) Failed to connect to 192.168.122.48 port 80 after 1 ms: Couldn't connect to server
```
and there is no other error occurs in the console.

**Comment by SamTV12345** [comment]
Hmm. Can you try localhost:8000? Keep in mind that you started only the backend.

**Comment by jenningsloy318** [comment]
I tried it as well. but no luck.
I gave up as running with docker.
