### ISSUE TITLE
add the podfetch rss to antennaPod  always show autentication error

### ISSUE THREAD

**Issue by jenningsloy318** [SamTV12345/PodFetch#570]
### Describe the bug

I set up podfetch, and sync it with two devices running antennaPod, they synchronized perfectly. but I want to listen from podftech rss on antennaPod, I add it with same user name, but always failed showing authtication error
![Screenshot_20240125_173117_de danoeh antennapod](https://github.com/SamTV12345/PodFetch/assets/10169236/dc2c71b4-f222-47d1-9a6e-92ecc3892379)
the synchronization is also working 
![Screenshot_20240126_125642_de danoeh antennapod](https://github.com/SamTV12345/PodFetch/assets/10169236/2cb70eb1-12cf-497e-a864-51076c864070)

but  logging on web ui has no problems also 
![image](https://github.com/SamTV12345/PodFetch/assets/10169236/3ae3c189-fd06-4965-bd4f-707eb1623cc1)

I am not if it relevant, the console has following log
```
2024-01-25T11:56:38 ❌ - stream error: request parse error: invalid Header provided
2024-01-25T11:57:22 ❌ - stream error: request parse error: invalid Header provided

``` 
### Reproduction

create user in and add the rss into antennaPod

### System Info

```Shell
1. running samuel19982/podfetch:latest  with postgresql 15.1  using docker-compose 
2. antennaPod 3.2
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Hm interesting. This is an error from the webserver framework itself, not from PodFetch. I'll investigate that.
So you added a podcast in PodFetch and you try to add that rss feed into AntennaPod so you can stream the PodFetch audio files?

**Comment by jenningsloy318** [comment]
Yes, that's what I am willing to do

**Comment by Ke1i** [comment]
Same here.
This is the quadlet file I'm using for running Podfetch:

```
[Unit]
Description=PodFetch Container

[Container]
Image=docker.io/samuel19982/podfetch:latest
AutoUpdate=registry
Volume=/containers/podfetch/config:/app/db:rw
Volume=/media/Podcasts:/app/podcasts:rw
Environment=POLLING_INTERVAL=60
Environment=SERVER_URL=http://192.168.0.103:8000
Environment=DATABASE_URL=sqlite:///app/db/podcast.db
Environment=BASIC_AUTH=true
Environment=USERNAME=admin
Environment=PASSWORD=password
Environment=GPODDER_INTEGRATION_ENABLED=true
ContainerName=podfetch
PublishPort=8000:8000/tcp

[Install]
WantedBy=multi-user.target
```
Importing Podcasts to Antennapod through OMPL import works but then I can't refresh the podcasts. I get an authentication error.
Syncing appeared to connect and work from Antennapod.

![Screenshot_20240413-143929_AntennaPod](https://github.com/SamTV12345/PodFetch/assets/20503185/8463d39e-588a-42a8-bb8e-bd5638276e0b)

**Comment by Ke1i** [comment]
So..
I've commented out the basic authentication and gpodder integration bits and I'm able to refresh the podcasts in Antennapod.
Also, the URL I mentioned earlier returns a valid XML.

![Screenshot_20240413-150155_DuckDuckGo](https://github.com/SamTV12345/PodFetch/assets/20503185/60c0caa2-0062-43c5-8396-e65d7f20c55f)

![Screenshot_20240413-150251_AntennaPod](https://github.com/SamTV12345/PodFetch/assets/20503185/ba55b854-54a8-4dbd-853a-f4bc8de31497)

**Comment by Ke1i** [comment]
So re enable basic authentication and gpodder integration, restart the container and generate another user from the webUI?
I generated one earlier and I could sync (gpodder integration on Antennapod) with the server just fine.
I think this will probably work if I use 'Online URLs' when exporting podcasts to import into Antennapod.
But my main issue here like the OP, is not having to download podcast episodes twice - on the phone and on the server! Hence the 'Export with local URLs' route.
I just want to stream/download the same file that's already on the server. Bandwidth is expensive here.
Currently it's working but once I enable gpodder integration to sync playback states then things break.
I hope I've explained correctly.

**Comment by Ke1i** [comment]
I can confirm playback state sync via gpodder integration working but only if you're using the same online sources for the feeds - so downloading episodes twice, on the server and on the phone.
It would be nice if one could download the episodes once on the server and then stream/download these to their device(s) and sync playback states of the same back to the server in a local manner - like in a home LAN for example.
Anyway thanks for making this. I was using a Subsonic clone for podcasts but this is definitely better.

**Comment by Ke1i** [comment]
> Try to generate an api key through the ui and try again with that.

I think I was getting the unauthorized error because I exported the feeds while logged in as the admin user and not the user I had created via invite.
So they were like http://192.168.0.103:8000/rss/1 instead of something like http://192.168.0.103:8000/rss/1?apiKey=5ae6145ea06d49529b61538ba23f0a54
My bad.
