### ISSUE TITLE
Cannot generate API key via UI

### ISSUE THREAD

**Issue by matthewkdies** [SamTV12345/PodFetch#584]
### Describe the bug

When trying to generate an API key through the UI, I get an error toast that displays as "Unknown". The underlying log generated is `2024-02-01T00:57:41 ❌ - Database error: Record not found`.

Alternatively, I also cannot get the invite links from the "Copy URL" button when generating an admin user. Upon inspecting the button I also wasn't able to find any relevant link from it.

For what it's worth, I have basic authentication enabled.

### Reproduction

Use SQLite docker-compose example, add basic auth, log in through web UI, and try to generate API key for logged in user.

### System Info

```Shell
Synology NAS running via Docker. My relevant compose file is below:

version: '3'
services:
  podfetch:
    image: samuel19982/podfetch:latest
    container_name: podfetch
    user: <my_uid>:<my_gid>
    ports:
      - <external_port>:8000
    volumes:
      - ./podcasts:/app/podcasts
      - ./db:/app/db
    environment:
      - POLLING_INTERVAL=60
      - SERVER_URL=http://localhost:8000
      - BASIC_AUTH=true
      - USERNAME=<my_username>
      - PASSWORD=<my_password>
    network_mode: <my_custom_network>
    restart: unless-stopped
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
I added a better exception message. The admin user should be used mostly for administration purposes.

**Comment by matthewkdies** [comment]
I see, thank you -- the fix works great and I'm already off and running. I appreciate the help!
