### ISSUE TITLE
Broken Links on GitHub page

### ISSUE THREAD

**Issue by MrSiO** [SamTV12345/PodFetch#586]
### Additional context

Hi.
There are a few broken links on your project page, including the following (CLI User Creation and UI Documentation)

https://github.com/SamTV12345/PodFetch/blob/main/docs/CLI.md
and 
https://github.com/SamTV12345/PodFetch/blob/main/docs/UIWalkthrough.md

Thx for considering!

**Comment by SamTV12345** [comment]
Hi,

thanks for reporting that issue. I should you have deleted the entries. They are all now part of the website which offers a better readability and also allows searching things.

**Comment by MrSiO** [comment]
> Hi,
> 
> thanks for reporting that issue. I should you have deleted the entries. They are all now part of the website which offers a better readability and also allows searching things.

Can you share your website link?

**Comment by SamTV12345** [comment]
Sure. It is now linked in the README and on the github link tab: https://samtv12345.github.io/PodFetch
