### ISSUE TITLE
Translation issuer after new feature

### ISSUE THREAD

**Issue by bastgau** [SamTV12345/PodFetch#590]
### Describe the bug

Hello.

There is a regression since the new feature : https://github.com/SamTV12345/PodFetch/issues/572

The special characters are encoded.

In the screenshot, the titles should be :

**- Episode Orthographe : faut-il écrire "pense à moi" ou "penses à moi" ? du 03 février 2024 now available**

**- Episode Le top / flop de la semaine : les révisions haussières de la croissance aux États-Unis – 02/02 now available**

<img width="412" alt="Capture d’écran 2024-02-04 à 00 28 15" src="https://github.com/SamTV12345/PodFetch/assets/4788354/ff5179dd-eab0-46e1-8e48-47090def5e7e">

### Reproduction

n/a

### System Info

```Shell
n/a
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Thanks for the issue. I reworked the notification code and forgot that a podcast episode name could also be html.

**Comment by bastgau** [comment]
Thanks. I will check that asap.
