### ISSUE TITLE
overriding data retention policy at subscription level

### ISSUE THREAD

**Issue by nherbaut** [SamTV12345/PodFetch#614]
### Clear and concise description of the problem

I'm scrapping podcasts from my public radio station (franceinter), since they stop being available after a month and I'd like to keep listening to them through my podcast app
For some other podcasts, i don't have this problem (e.g. 99PI) and the whole archive is available all the time.

I want to be able to specify that for a given podcast, the retention policy should be infinite (since they won't be available in the future) and for other only temporary (since i will be able to download the episode whenever I want).

### Suggested solution

allow user to override the default data retention policy at subscription level

### Alternative

now, I don't use podfetcher for podcasts for which I know they will be available forever

### Additional context

this feature is implemented in my pockercast android podcast player, It would be nice to have it implemented also in podfetcher

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by nherbaut** [comment]
thanks @SamTV12345  for the great work!

**Comment by SamTV12345** [comment]
This is also implemented. Just turn off auto cleanup for a podcast and you are good to go :)
