### ISSUE TITLE
User Administration - can't copy invite Link

### ISSUE THREAD

**Issue by Tommy-01** [SamTV12345/PodFetch#636]
### Describe the bug

In the UI, i did create a new User Invitation. But i can't copy the invitation Link. The copy Link Button seems to have no function.
I tried it with various Browsers.

### Reproduction

Creat a new Invitation Link, try to copy this Link.

### System Info

```Shell
- PodFetch runs as Container, latest Image from Docker Hub
- Brwoser: Firefox, Vanadium
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
> ### Describe the bug
> In the UI, i did create a new User Invitation. But i can't copy the invitation Link. The copy Link Button seems to have no function. I tried it with various Browsers.
> 
> ### Reproduction
> Creat a new Invitation Link, try to copy this Link.
> 
> ### System Info
> ```shell
> - PodFetch runs as Container, latest Image from Docker Hub
> - Brwoser: Firefox, Vanadium
> ```
> 
> ### Used Package Manager
> npm
> 
> ### Validations
> * [x]  Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
> * [x]  Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
> * [x]  Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
> * [x]  Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
> * [x]  The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

Do you use ssl for accessing the user administration area. But I agree that it should always work even with no SSL.

**Comment by Tommy-01** [comment]
Thank you for answering!
No i don't use ssl.
