### ISSUE TITLE
Database error: invalid utf-8 sequence of 1 bytes from index 288 after docker compose down/up

### ISSUE THREAD

**Issue by stelle007** [SamTV12345/PodFetch#679]
### Describe the bug

Hi.

I am getting the below error on the app container after I did docker compose down/up, when ever I click "All Sucscriptions".
I still see newest podcasts, under "Home"

2024-03-28T13:06:12.467634045Z 2024-03-28T13:06:12 ❌ - Database error: invalid utf-8 sequence of 1 bytes from index 288

Do anyone have any Idears?

Thank you.

### Reproduction

Click All Sucscriptions

### System Info

```Shell
Running Docker container on unraid behind NgienX proxy manager. And postgres DB
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Hi. Thanks for the issue. I just setup podfetch with the docker-compose in the root directory and it worked with the latest podfetch and postgres image. Is your database volume still working?
