### ISSUE TITLE
Single quotes in episode title not removed as illegal character

### ISSUE THREAD

**Issue by dantodev** [SamTV12345/PodFetch#692]
### Describe the bug

Single quotes do not get removed/replaced as illegal characters which messes with the single quotes around the filename despite the "Replace illegal characters in filenames with a dash" setting.

See this feed: https://drei90.de/feed/mp3/ there is an episode called `Nr. 234: Wenn's sein muss dann Bochum`. When downloaded it results in the following folder name:
```
'Nr. 234 -  Wenn's sein muss dann Bochum'
```

I'm importing my podcast library into other applications like audiobookshelf which is not able to import these episodes due to the reason it has three quotes (including the quotes at start and end of the folder name)

### Reproduction

https://drei90.de/feed/mp3/

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (8) x64 AMD Ryzen 5 PRO 3500U w/ Radeon Vega Mobile Gfx
    Memory: 2.42 GB / 5.71 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.12.1 - ~/.nvm/versions/node/v20.12.1/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.1/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Krispkiwi** [comment]
Getting this too, everything has quotation marks

**Comment by SamTV12345** [comment]
This is fixed now. I removed the quotation and instead rely on replacing any invalid character
