### ISSUE TITLE
is there a way to notify/webhook another container/system after episodes have been downloaded

### ISSUE THREAD

**Issue by johnnychicago** [SamTV12345/PodFetch#702]
### Clear and concise description of the problem

Hey --

Enjoy podfetch, but I mostly use it to download episodes which I consume in other applications (navidrome and slimserver) - I am also creating playlists programmatically. I am missing some sort of signal that podfetch could send to kick off playlist recreation and rescan for the other systems. I've seen that there's Telegram support and notifications on the UI, so I'd hope for this to be a trivial kind of addition.

Thanks

### Suggested solution

not really. I am just a user :)

### Alternative

I am currently tail'ing the logfile and kicking off scripts from that. Works, but feels dirty :)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by SamTV12345** [comment]
You can connect via Websocket. It always returns a response when a new podcast episode is available locally.
