### ISSUE TITLE
Issue With Downloaded Files from Podbean

### ISSUE THREAD

**Issue by kvedder** [SamTV12345/PodFetch#708]
### Describe the bug

When adding a podcast from podbean, the auto downloader downloads a file, but it is corrupt/empty, or otherwise not playable.

The podbean URL example:
https://mcdn.podbean.com/mf/web/nrxdbb/filename.mp3

### Reproduction

Add any podbean podcast from RSS and attempt to download and then play.

Let me know if you need more info, or some sort of debug output. Happy to help!

### System Info

```Shell
Debian 12, Version 4.6.1 running as a systemd service, with nginx as the front end. Other podcasts are downloading without issue.


```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Ke1i** [comment]
I've noticed this as well.. The feed URL is `https://feed.podbean.com/realsgtreport/feed.xml`
Downloaded episodes are way too small. The latest episode downloaded being 94.

**Comment by kvedder** [comment]
Exact symptom I had as well.

**Comment by SamTV12345** [comment]
It's fixed. The podcast creator seems to be really worried and also got a check for the user agent when downloading a podcast episode. Works now flawlessly
