### ISSUE TITLE
Mobile Friendly UI / Fast Forward 15 or 30 Seconds

### ISSUE THREAD

**Issue by saddle-gaudier-06** [SamTV12345/PodFetch#71]
### Clear and concise description of the problem

I mostly listen to podcasts via my cell phone, and the current UI isn't mobile friendly. Also, it would be helpful to be able to fast forward by 15 or 30 seconds to skip podcast commercials.

### Suggested solution

Implement a mobile friendly UI. Add a feature to fast forward by 15 or 30 seconds.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by SamTV12345** [comment]
Thanks for creating an issue. Could you please add the paths where you found a problem with the mobile view?

**Comment by saddle-gaudier-06** [comment]
Below are the main issues that I've come across. Listed by importance.
* UI: When you click on play for a podcast and then click on the podcast image, at the bottom, in the play section, it opens up a player that doesn't fit a mobile screen.
* Timeline: this section isn't sized properly and you need to scroll to the left and right to see everything that is displayed.
* Info: the font is so large that that graphs are compressed to the point that not everything is readable.
* Settings: this is minor but the "Days to keep" box doesn't appear to resize based on the phone screen size.
