### ISSUE TITLE
Message/progress bar for podcasts imported with .opml

### ISSUE THREAD

**Issue by quartzbear** [SamTV12345/PodFetch#76]
### Clear and concise description of the problem

When adding podcasts, there is no feedback when uploading an OPML file. 

![image](https://user-images.githubusercontent.com/33700415/233804223-732c2ed7-bcb7-4975-88cb-6a169d7a51fb.png)

In my case, there is some strange bug that only the first podcast in the file is being added.

### Suggested solution

 A "successfully added" and/or "importing 35 podcast out of 45" message.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by SamTV12345** [comment]
Good idea. I will work on it once I have the GPodder integration merged. Will start to work on it next week.
