### ISSUE TITLE
Add support for proxy when behind a firewall

### ISSUE THREAD

**Issue by jenningsloy318** [SamTV12345/PodFetch#771]
### Clear and concise description of the problem

we are behind a firewall, thus we need to proxy to access the internet, so require podfetch to support get podcasts via proxy

### Suggested solution

 - add config to make podfetch to get podcast via proxy 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by SamTV12345** [comment]
Hmm. How would this work? So PodFetch asks the proxy server how? And what format would this be?

**Comment by jenningsloy318** [comment]
like we use socks_proxy or http_proxy or https_proxy to make podfetch internet aceess through theese proxies
