### ISSUE TITLE
Can't get service started

### ISSUE THREAD

**Issue by JakeB-OnGithub** [SamTV12345/PodFetch#780]
### Describe the bug

I can't seem to get the most basic server running, and I feel like I must be missing some step. I have a larger docker-compose file where I run all of my services, but for this example I have simply created a new docker-compose.yml file and pasted in the setup from here: [https://samtv12345.github.io/PodFetch/Installation.html](https://samtv12345.github.io/PodFetch/Installation.html).

```version: '3'
services:
  podfetch:
    image: samuel19982/podfetch:latest
    user: ${UID:-1000}:${GID:-1000}
    ports:
      - "80:8000"
    volumes:
      - podfetch-podcasts:/app/podcasts
      - podfetch-db:/app/db
    environment:
      - POLLING_INTERVAL=60
      - SERVER_URL=http://localhost:80
      - DATABASE_URL=sqlite:///app/db/podcast.db

volumes:
    podfetch-podcasts:
    podfetch-db:
```

I then run `docker-compose up`, and it appears to work, but going to the IP address of the server (192.168.2.11 in this case) does not work, even though it appears that it should be listening on port 80. I get a connection refused error.

Running `sudo docker logs jake_podfetch_1` (the auto-generated name), I see this error:
`❌ - Error connecting to sqlite:///app/db/podcast.db with reason Invalid connection url for multiconnection`

Running `sudo docker volume ls`, I see the two volumes that I would expect:
```
DRIVER    VOLUME NAME
local     jake_podfetch-db
local     jake_podfetch-podcasts
```

The instructions mention that it is important to change the UID and GID to my own. I have changed this, but I wouldn't mind in this case if things are owned by root. I ran `sudo useradd temp`, then `id -u temp` and `id -g temp`, both of which returned 1001. I therefore changed that line in the config to:
```
podfetch:
    ...
    user: 1001:1001
```
Nothing changed, though.

Did I skip some major step in the documentation, or is this a real bug?

### Reproduction

Create a fresh Ubuntu Server 22.04.4 LTS VM, install docker, copy the docker compose configs directly from the website, run sudo docker-compose up

### System Info

```Shell
Server: Ubuntu Server 22.04.4 LTS
Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aloneguid** [comment]
Same here. This is the third podcast project i've tried today so far, none seem to work out of the box :)

**Comment by SamTV12345** [comment]
> JakeB

Try to replace 1000 by 0. That will work always and is probably sufficient for your use cases @aloneguid @JakeB-OnGithub

**Comment by Lukas-Heiligenbrunner** [comment]
> > JakeB
> 
> Try to replace 1000 by 0. That will work always and is probably sufficient for your use cases @aloneguid @JakeB-OnGithub

For me just deleting user: `${UID:-1000}:${GID:-1000}` fixed it. Maybe delete it from your example compose or mention it somewhere? :)
