### ISSUE TITLE
Failed to construct 'WebSocket': The URL 'ws://xxx.xxx.xxx.xxx:xxxx/ws' is invalid.

### ISSUE THREAD

**Issue by tgkarthur** [SamTV12345/PodFetch#806]
### Describe the bug

I'm attempting a fresh install using the docker compose example, (I have set the user to root as I wanted to verify I wasn't running into any perms issues):

version: '3'
services:
  podfetch:
    image: samuel19982/podfetch:latest
    user: ${UID:-0}:${GID:-0}
    ports:
      - "8057:8000"
    volumes:
      - /Vol1/Plex/Podcasts:/app/podcasts
      - /Vol1/Podfetch:/app/db
    environment:
      - POLLING_INTERVAL=60
      - SERVER_URL=http://192.168.1.256:8057
      - DATABASE_URL=sqlite:///app/db/podcast.db
     
The container spins up correctly as far as I can tell. Logs below:

2024-06-24T10:11:36 ℹ️ - Settings already present

2024-06-24T10:11:36 ℹ️ - Starting with the following environment variables:

2024-06-24T10:11:36 ℹ️ - Public server url: http://192.168.1.256:8057/

2024-06-24T10:11:36 ℹ️ - Polling interval for new episodes: 60 minutes

2024-06-24T10:11:36 ℹ️ - Developer specifications available at http://192.168.1.256:8057/swagger-ui/index.html#/

2024-06-24T10:11:36 ℹ️ - GPodder integration enabled: false

2024-06-24T10:11:36 ℹ️ - Podindex API key&secret configured: false

2024-06-24T10:11:36 ℹ️ - starting 4 workers

2024-06-24T10:11:36 ℹ️ - Actix runtime found; starting in Actix runtime

2024-06-24T11:00:00 ℹ️ - Polling for new episodes

2024-06-24T11:00:00 ℹ️ - Polling for new episodes successful

But when I navigate to http://192.168.1.236:8057 I get redirected to http://192.168.1.236:8057/ui/home/view which is as below in Firefox:

Unexpected Application Error!
An invalid or illegal string was specified

jQ/<@http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:225:8274
kf@http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:46:24272
Eo@http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:46:42384
_b@http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:46:36604
Mi@http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:44:3274
zR@http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:46:41260
Ki@http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:46:40254
dE@http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:46:35397
_@http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:31:1568
A@http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:31:1934

And as below in Edge:

Unexpected Application Error!
Failed to construct 'WebSocket': The URL 'ws://192.168.1.256:8057/ws' is invalid.
Error: Failed to construct 'WebSocket': The URL 'ws://192.168.1.256:8057/ws' is invalid.
    at http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:225:8274
    at kf (http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:46:24272)
    at Eo (http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:46:42382)
    at zR (http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:46:41205)
    at Ki (http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:46:40254)
    at _b (http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:46:36864)
    at Mi (http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:44:3274)
    at http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:46:34246

I looked through the closed issues as I thought it would be an obvious config error on my end, and while it no doubt still is, I can't find anyone with the same issue.

Any help would be much appreciated!

### Reproduction

Run the compose file as described and attempt to connect to the UI.

### System Info

```Shell
Server: OMV 6.0.24-1 (Shaitan)
Docker version 26.1.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Thanks for the report. I'll take a look at it. I guess because it's an IP address you don't use SSL. So it must be something else not working.

**Comment by SamTV12345** [comment]
> ### Describe the bug
> 
> I'm attempting a fresh install using the docker compose example, (I have set the user to root as I wanted to verify I wasn't running into any perms issues):
> 
> 
> 
> version: '3'
> 
> services:
> 
>   podfetch:
> 
>     image: samuel19982/podfetch:latest
> 
>     user: ${UID:-0}:${GID:-0}
> 
>     ports:
> 
>       - "8057:8000"
> 
>     volumes:
> 
>       - /Vol1/Plex/Podcasts:/app/podcasts
> 
>       - /Vol1/Podfetch:/app/db
> 
>     environment:
> 
>       - POLLING_INTERVAL=60
> 
>       - SERVER_URL=http://192.168.1.256:8057
> 
>       - DATABASE_URL=sqlite:///app/db/podcast.db
> 
>      
> 
> The container spins up correctly as far as I can tell. Logs below:
> 
> 
> 
> 2024-06-24T10:11:36 ℹ️ - Settings already present
> 
> 
> 
> 2024-06-24T10:11:36 ℹ️ - Starting with the following environment variables:
> 
> 
> 
> 2024-06-24T10:11:36 ℹ️ - Public server url: http://192.168.1.256:8057/
> 
> 
> 
> 2024-06-24T10:11:36 ℹ️ - Polling interval for new episodes: 60 minutes
> 
> 
> 
> 2024-06-24T10:11:36 ℹ️ - Developer specifications available at http://192.168.1.256:8057/swagger-ui/index.html#/
> 
> 
> 
> 2024-06-24T10:11:36 ℹ️ - GPodder integration enabled: false
> 
> 
> 
> 2024-06-24T10:11:36 ℹ️ - Podindex API key&secret configured: false
> 
> 
> 
> 2024-06-24T10:11:36 ℹ️ - starting 4 workers
> 
> 
> 
> 2024-06-24T10:11:36 ℹ️ - Actix runtime found; starting in Actix runtime
> 
> 
> 
> 2024-06-24T11:00:00 ℹ️ - Polling for new episodes
> 
> 
> 
> 2024-06-24T11:00:00 ℹ️ - Polling for new episodes successful
> 
> 
> 
> But when I navigate to http://192.168.1.236:8057 I get redirected to http://192.168.1.236:8057/ui/home/view which is as below in Firefox:
> 
> 
> 
> Unexpected Application Error!
> 
> An invalid or illegal string was specified
> 
> 
> 
> jQ/<@http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:225:8274
> 
> kf@http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:46:24272
> 
> Eo@http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:46:42384
> 
> _b@http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:46:36604
> 
> Mi@http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:44:3274
> 
> zR@http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:46:41260
> 
> Ki@http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:46:40254
> 
> dE@http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:46:35397
> 
> _@http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:31:1568
> 
> A@http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:31:1934
> 
> 
> 
> And as below in Edge:
> 
> 
> 
> Unexpected Application Error!
> 
> Failed to construct 'WebSocket': The URL 'ws://192.168.1.256:8057/ws' is invalid.
> 
> Error: Failed to construct 'WebSocket': The URL 'ws://192.168.1.256:8057/ws' is invalid.
> 
>     at http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:225:8274
> 
>     at kf (http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:46:24272)
> 
>     at Eo (http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:46:42382)
> 
>     at zR (http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:46:41205)
> 
>     at Ki (http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:46:40254)
> 
>     at _b (http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:46:36864)
> 
>     at Mi (http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:44:3274)
> 
>     at http://192.168.1.236:8057/ui/assets/index-C1ZOoWw8.js:46:34246
> 
> 
> 
> I looked through the closed issues as I thought it would be an obvious config error on my end, and while it no doubt still is, I can't find anyone with the same issue.
> 
> 
> 
> Any help would be much appreciated!
> 
> ### Reproduction
> 
> Run the compose file as described and attempt to connect to the UI.
> 
> ### System Info
> 
> ```Shell
> Server: OMV 6.0.24-1 (Shaitan)
> 
> Docker version 26.1.1
> ```
> 
> 
> ### Used Package Manager
> 
> npm
> 
> ### Validations
> 
> - [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
> - [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
> - [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
> - [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
> - [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

Couldn't really replicate the issue. Can you try it locally with http://localhost:80 and check if the error still occurs?

**Comment by tgkarthur** [comment]
Sorry, I ended up removing everything and redeploying from scratch (which I had done before), but it works now. Thanks for the amazing tool! 
Just in case there's anything of use, this is the compose I ran just now which worked.

version: '3'
services:
  podfetch:
    image: samuel19982/podfetch:latest
    user: ${UID:-0}:${GID:-0}
    ports:
      - "8057:8000"
    volumes:
      - /Vol1/Plex/Podcasts/:/app/podcasts
      - /Vol1/Podfetch/:/app/db
    environment:
      - POLLING_INTERVAL=60
      - SERVER_URL=http://localhost:8057
      - DATABASE_URL=sqlite:///app/db/podcast.db
