### ISSUE TITLE
Feature Request - Download All

### ISSUE THREAD

**Issue by cirdanlunae** [SamTV12345/PodFetch#836]
### Clear and concise description of the problem

Some users like archiving podcasts, and this would entail downloading the entirety of a podcast locally to PodFetch. An option to Download All on a pre-existing podcast would help with that. Currently, the only option is to manually click each episode. For podcasts with hundreds of episodes, this is tedious.

### Suggested solution

A simple "Download All" button on each podcast, which would queue all episodes for download

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by SamTV12345** [comment]
Added. Just open the podcast settings and add a high number like 999 for the last episodes to download. Then hit refresh and it will download all podcasts.
