### ISSUE TITLE
Ability to Manually Refresh All Podcast Subscriptions

### ISSUE THREAD

**Issue by saddle-gaudier-06** [SamTV12345/PodFetch#84]
### Clear and concise description of the problem

To get the latest podcast releases, a setting can be set in the docker-compose.yml, which specifies how frequently to check for new releases. That said, I don't know why, but my podcast subscriptions don't always update and show the latest releases. 

### Suggested solution

Currently, when you click on a specific podcast, there is a refresh button that manually forces the system to look for new releases for that particular podcast. Would it be possible to add a refresh button on the Podcast page (ui/podcasts) to allow users to manually request Podfetch to look for new podcasts across all your subscriptions?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by SamTV12345** [comment]
Great idea. I hope to get started with your issue next week. I'm currently working on the GPodder integration which requires some manual testing. If you'd like to test the next version of PodFetch. Change the latest tag to dev.

**Comment by saddle-gaudier-06** [comment]
I've transitioned to the Dev docker tag, but I'm still having issues with the refresh function of Podfetch. When I hit the Refresh All button on the Podcast page, no new podcast episodes show up, and I see the below output in the logs. I wonder if the refresh process stops once it comes to a podcast that doesn't have any new episodes, instead of updating all the subscribed podcasts.

2023-05-01T10:00:00 [INFO] - Polling for new episodes

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/db.rs:205:49

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

2023-05-01T18:08:08 [INFO] - Refreshing podcast: The Common Man Progrum

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/db.rs:205:49

**Comment by saddle-gaudier-06** [comment]
Thanks for the quick work on this! I was able to update a few of the podcasts that I subscribe to, but then I ran into another issue that stopped the refresh process.

2023-05-01T19:17:31 [INFO] - Refreshing podcast: Security In Five

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/service/podcast_episode_service.rs:153:80

**Comment by SamTV12345** [comment]
Thanks for the podcast name. This one has episodes that don't have a download url. Didn't encounter that yet because I thought if you host a podcast you need urls people can enter and media they can listen to.

**Comment by SamTV12345** [comment]
Dev build is updated for arm

**Comment by saddle-gaudier-06** [comment]
I'm not seeing errors anymore. Thanks for the help!

**Comment by SamTV12345** [comment]
Awesome.
