### ISSUE TITLE
Adding Basic Auth makes PodFetch unreachable

### ISSUE THREAD

**Issue by Ethanol6** [SamTV12345/PodFetch#86]
### Describe the bug

If I add the basic auth variables to the docker-compose.yml file I can no longer reach the PodFetch webpage. Understandable since I am not authorized but how do I pass my authentication credentials?

### Reproduction

Add Basic Auth variables to the environment section of the docker-compose file

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Memory: 13.73 GB / 19.40 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 12.22.9 - /usr/bin/node
    npm: 8.5.1 - /usr/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Can you access the server via $SERVER_URL/ui/login?

**Comment by SamTV12345** [comment]
If you write the username and password env variables small it should work. Neithertheless I fixed it. They should now be all caps.

**Comment by Ethanol6** [comment]
Here's what I have:
```
- BASIC_AUTH=TRUE
- USERNAME=USER
- PASSWORD=PASS
```
`$URL/ui/login` is still unreachable. I thought it might auto-redirect to that url if AUTH was enabled.
I have tried using " around the username and password as well.

**Comment by SamTV12345** [comment]
Did that work?

**Comment by Ethanol6** [comment]
> Did that work?

It's working here now. It redirects properly and authentication works. Thanks!

**Comment by SamTV12345** [comment]
Great.
