### ISSUE TITLE
Option to mark episode as finished

### ISSUE THREAD

**Issue by SirBogner** [SamTV12345/PodFetch#900]
### Clear and concise description of the problem

Add an option to mark an episode as finished.

### Suggested solution

The button could be placed next to "download podcast" on the podcast overview page. 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by SamTV12345** [comment]
Added. There is now a button that marks an episode as already listened to.
