### ISSUE TITLE
UI contrib

### ISSUE THREAD

**Issue by ThisisErm** [SamTV12345/PodFetch#92]
Hi,

Saw in your readme that you were looking for a UI contributor. I just graduated a coding bootcamp and would love the extra practice.

**Comment by SamTV12345** [comment]
Hi, thank you for your help. I don't know much about design or better ui/accessibility creation. Most of the design is inspired by Flowbite Tailwindcss. So if you could give the ui a less generic look it would be very much appreciated. Do you know how to use figma? Other than that feel free to change the look and feel of the React UI. I am happy to review your design :D

**Comment by ThisisErm** [comment]
Awesome. And yes, I know how to use Figma. I play around with it and submit a PR this week.

**Comment by deranjer** [comment]
FYI, I'm a software engineer, if additional help is needed with React, let me know.  I primarily work in Mantine.

**Comment by SamTV12345** [comment]
Hi Erm. Did you find the time to create some Sigma designs?

**Comment by ThisisErm** [comment]
Hi Sam, I'm working on some generic designs but unfortunately I have not been able to get the app running on my machine. I'm not too familiar with Rust. I did install Rust and Cargo on the machine but the build keeps failing. Do you mind walking me through that?

**Comment by SamTV12345** [comment]
Sure here is how to get started with PodFetch

cargo.exe run --color=always --package podfetch --bin podfetch
# File just needs to be there
touch static/index.html
# Enable CORS headers
export DEV=true
cd ui
<npm/yarn/pnpm> install
<npm/yarn/pnpm> run dev

If you are on Windows touch static/index.html is simply creating a file in the static directory named index.html. It does not need to contain content.

**Comment by ThisisErm** [comment]
Awesome. I'm up and running and working on the UI

**Comment by SamTV12345** [comment]
Could you find the time to create some figma templates?

**Comment by ThisisErm** [comment]
Hi Sam,

I'm really sorry but I just started a new job and don't really have the time to work on this. My most sincere apologies.
