### ISSUE TITLE
Release tag in docker isn't actually the tagged code

### ISSUE THREAD

**Issue by halkeye** [SamTV12345/PodFetch#923]
> Every time a new commit is pushed to the main branch, a new docker image is built and pushed to docker hub. So it is best to use something like [watchtower](https://github.com/containrrr/watchtower) to automatically update the docker image.

I saw this line in the readme, and got super nervous, I liked pinned dependencies so i can control everything via git repo and roll back as needed.

I saw you have releases 🎉, and I saw you have tags 🎉 , so got excited, but when i went to look at the docker images. 
https://github.com/SamTV12345/PodFetch/pkgs/container/podfetch/268352362?tag=v4.7.1 was built 15 hours ago
https://github.com/SamTV12345/PodFetch/commits/v4.7.1/ was committed 5 days ago

So it seems that every commit to master is updating the last docker tag, not just the master/latest literal tag.

I can't find the github actions that pushes a docker image. Is the tag being updated by hand?

Is there a consistent tag I can use to try out specific versions?

**Comment by SamTV12345** [comment]
> > Every time a new commit is pushed to the main branch, a new docker image is built and pushed to docker hub. So it is best to use something like [watchtower](https://github.com/containrrr/watchtower) to automatically update the docker image.
> 
> I saw this line in the readme, and got super nervous, I liked pinned dependencies so i can control everything via git repo and roll back as needed.
> 
> I saw you have releases 🎉, and I saw you have tags 🎉 , so got excited, but when i went to look at the docker images. https://github.com/SamTV12345/PodFetch/pkgs/container/podfetch/268352362?tag=v4.7.1 was built 15 hours ago https://github.com/SamTV12345/PodFetch/commits/v4.7.1/ was committed 5 days ago
> 
> So it seems that every commit to master is updating the last docker tag, not just the master/latest literal tag.
> 
> I can't find the github actions that pushes a docker image. Is the tag being updated by hand?
> 
> Is there a consistent tag I can use to try out specific versions?

Yes you can. It was a wish from someone that updates should be released immediately not after a release every month or so. I release frequently new versions in the release tabs. Additionally every commit also generates a new image and updates latest etc. to get feedback if something does not work. Additionally there are these tagged releases. It is also updated when on the current tag a new commit is added to main. But you can rely on the  v4.7.1-c3a4310 .  c3a4310 is the commit that generated the image. So if you want to stay on the tag just check the commit id and append it to the released version.

**Comment by halkeye** [comment]
>  But you can rely on the v4.7.1-c3a4310

but why is it `v4.7.1-c3a4310` and not `main-c3a4310` or just `c3a4310`. c3a4310 isn't 4.7.1 anymore, its something newer.

I think i'm going to have to close this and try to find another tool, with https://docs.renovatebot.com/modules/versioning/regex/ I might be able to match the shas in the version, but it would end up triggering renovate every commit anyways since there's no way to tell it it also has to match the github release (default behavior so you get changelogs)
