### ISSUE TITLE
Querying Podcast Index no longer fetches results

### ISSUE THREAD

**Issue by Ethanol6** [SamTV12345/PodFetch#934]
### Describe the bug

When adding a new podcast via Podcast Index no results are shown, just the spinner spinning indefinitely.

I am using the docker image if that matters.

I created a new API key and secret to make sure that wasn't the issue. 
I checked the Podcast Index website itself and I can search for the same podcast there and get results.

### Reproduction

Add Podcast Index API key and secret to docker-compose file. Then try searching for a podcast using the "add new" button on the subscriptions page.

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Memory: 17.27 GB / 19.39 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 12.22.9 - /usr/bin/node
    npm: 8.5.1 - /usr/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Ethanol6** [comment]
I have two environment variables. `PODINDEX_API_Key` and `PODINDEX_API_SECRET`

I made a new API key and secret just to be sure. The system information page gives me the green checkmark to confirm podindex is configured. Searching iTunes shows results, searching Podcast Index shows no results.

**Comment by SamTV12345** [comment]
> I have two environment variables. `PODINDEX_API_Key` and `PODINDEX_API_SECRET`
> 
> I made a new API key and secret just to be sure. The system information page gives me the green checkmark to confirm podindex is configured. Searching iTunes shows results, searching Podcast Index shows no results.

Oh it's the podindex_api_key my env keys are all capslock. So should be PODINDEX_API_KEY

**Comment by Ethanol6** [comment]
That was a type-o. It is all caps in my docker-compose file.

**Comment by SamTV12345** [comment]
Do you have your key correctly configured? If it contains a $ you need to escape it with another $ sign or put " around them.

**Comment by Ethanol6** [comment]
The key and secret are alphanumeric. No special characters.

**Comment by N0cky** [comment]
Same issue for me in the logs I get the following error:
2024-10-14T06:54:27 ℹ️ - Found podcast: https://api.podcastindex.org/api/1.0/search/byterm?q=test
2024-10-14T06:54:27 ❌ - Error during reqwest: error decoding response body

**Comment by SamTV12345** [comment]
Hi @N0cky and @Ethanol6 I added better debugging. So please try to upgrade to the latest version of PodFetch. It now shows this helpful tip if your api key is wrong or any other error coming from Podindex.
![image](https://github.com/user-attachments/assets/a980a5d6-cf55-4293-907e-65140a036cbd)

**Comment by SamTV12345** [comment]
Did you have the chance to checkout the latest version of PodFetch?

**Comment by Ethanol6** [comment]
Is accessing the logs documented somewhere?

**Comment by SamTV12345** [comment]
You can access the logs via docker-compose logs or docker compose logs. If it is bare metal you need to check how to get them. They are simply written to stdout

**Comment by Ethanol6** [comment]
> You can access the logs via docker-compose logs or docker compose logs. If it is bare metal you need to check how to get them. They are simply written to stdout

Thanks, that's what I thought. There is almost nothing of value being printed in the logs so I thought I was doing it wrong.

```
Attaching to podfetch-docker-files_podfetch_1
podfetch_1  | Debug file located at /home/rust/src/target/x86_64-unknown-linux-musl/release/build/podfetch-5299120925e79a33/out/built.rs
podfetch_1  | 2024-11-15T06:33:05 ❌ - database is locked
podfetch_1  | 2024-11-15T06:33:05 ❌ - database is locked
podfetch_1  | 
podfetch_1  |   ____           _ _____    _       _
podfetch_1  |  |  _ \ ___   __| |  ___|__| |_ ___| |__
podfetch_1  |  | |_) / _ \ / _` | |_ / _ \ __/ __| '_ \
podfetch_1  |  |  __/ (_) | (_| |  _|  __/ || (__| | | |
podfetch_1  |  |_|   \___/ \__,_|_|  \___|\__\___|_| |_|
podfetch_1  | 
podfetch_1  |         
podfetch_1  | 2024-11-15T06:33:06 ℹ️ - Settings already present
podfetch_1  | 
podfetch_1  | 
podfetch_1  | 
podfetch_1  | 
podfetch_1  | 2024-11-15T06:33:06 ℹ️ - Starting with the following environment variables:
podfetch_1  | 2024-11-15T06:33:06 ℹ️ - Public server url: http://breakfast2.lan:9002/
podfetch_1  | 2024-11-15T06:33:06 ℹ️ - Polling interval for new episodes: 60 minutes
podfetch_1  | 2024-11-15T06:33:06 ℹ️ - Developer specifications available at http://breakfast2.lan:9002/swagger-ui/index.html#/
podfetch_1  | 2024-11-15T06:33:06 ℹ️ - GPodder integration enabled: false
podfetch_1  | 2024-11-15T06:33:06 ℹ️ - Podindex API key&secret configured: true
podfetch_1  | 2024-11-15T06:33:06 ℹ️ - starting 4 workers
podfetch_1  | 2024-11-15T06:33:06 ℹ️ - Actix runtime found; starting in Actix runtime
podfetch_1  | 2024-11-15T06:33:06 ℹ️ - starting service: "actix-web-service-0.0.0.0:8000", workers: 4, listening on: 0.0.0.0:8000
podfetch_1  | 2024-11-15T06:35:53 ℹ️ - connected
podfetch_1  | 2024-11-15T06:35:53 ℹ️ - Someone joined
podfetch_1  | 2024-11-15T06:35:53 ℹ️ - Joined main room
podfetch_1  | Someone disconnected
podfetch_1  | 2024-11-15T06:38:03 ℹ️ - connected
podfetch_1  | 2024-11-15T06:38:03 ℹ️ - Someone joined
podfetch_1  | 2024-11-15T06:38:03 ℹ️ - Joined main room
podfetch_1  | Someone disconnected
podfetch_1  | 2024-11-15T06:46:15 ℹ️ - connected
podfetch_1  | 2024-11-15T06:46:15 ℹ️ - Someone joined
podfetch_1  | 2024-11-15T06:46:15 ℹ️ - Joined main room
podfetch_1  | 2024-11-15T06:50:50 ℹ️ - connected
podfetch_1  | 2024-11-15T06:50:50 ℹ️ - Someone joined
podfetch_1  | 2024-11-15T06:50:50 ℹ️ - Joined main room
podfetch_1  | Someone disconnected
podfetch_1  | 2024-11-15T07:00:00 ℹ️ - Polling for new episodes
podfetch_1  | 2024-11-15T07:00:02 ℹ️ - Downloading podcast episode: Someone Has Blown Up Their Ryzen 7 9800X3D
podfetch_1  | thread '<unnamed>' panicked at src/service/download_service.rs:56:14:
podfetch_1  | called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: "https://sphinx.acast.com/p/open/s/64db275277fd79001173cfd5/e/6736878ccb2eb55da6411dd6/media.mp3", source: hyper_util::client::legacy::Error(Connect, ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup address information: Try again" })) }
podfetch_1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
podfetch_1  | 2024-11-15T07:08:32 ℹ️ - connected
podfetch_1  | 2024-11-15T07:08:32 ℹ️ - Someone joined
podfetch_1  | 2024-11-15T07:08:32 ℹ️ - Joined main room
podfetch_1  | Someone disconnected
podfetch_1  | Someone disconnected
podfetch_1  | 2024-11-16T00:22:51 ℹ️ - connected
podfetch_1  | 2024-11-16T00:22:51 ℹ️ - Someone joined
podfetch_1  | 2024-11-16T00:22:51 ℹ️ - Joined main room
```

**Comment by SamTV12345** [comment]
> 00

That is indeed weird. I can only see the error when downloading a podcast episode. This should only happen when the hoster is not available

**Comment by SamTV12345** [comment]
Do you have any news? The newer images should show an error if you have Podindex configured incorrectly.

**Comment by Ethanol6** [comment]
> Do you have any news? The newer images should show an error if you have Podindex configured incorrectly.

I pulled the latest image and Podcast Index searches are now working!

**Comment by SamTV12345** [comment]
Awesome. Great that it works now :)
