### ISSUE TITLE
'Upload OPML'-button grayed out

### ISSUE THREAD

**Issue by d3545t3r** [SamTV12345/PodFetch#95]
### Describe the bug

Hello,

tried to import my podcasts from my Android app "Podcast Addict".

Podfetch shows 

"The following file will be uploaded:
PodcastAddict_OPML_export_20230501_055429.opml",

but the "Upload OPML"-button is grayed out, so I can't do it as nothing happens.

Same issue with OPML-files from other sources.

Am I doing Something wrong?

### Reproduction

happens with every version of podfetch

### System Info

```Shell
System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) arm ARMv7 Processor rev 5 (v7l)
    Memory: 394.19 MB / 999.02 MB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Thanks for the issue. Glad you solved the issue. May I ask which steps you took to make the opml upload work?

**Comment by tehniemer** [comment]
@d3545t3r I'm having the same issue, what did you do to solve it? 

@SamTV12345 mind reopening this until a solution is found?

**Comment by tehniemer** [comment]
@SamTV12345 Here's some more info, every time I try to click the button this shows up in the logs.

`2023-05-01T12:00:15.160813992Z thread 'tokio-runtime-worker' panicked at 'Error parsing feed: InvalidStartTag', src/controllers/podcast_controller.rs:450:52`

**Comment by SamTV12345** [comment]
Could you please post your opml file?

**Comment by d3545t3r** [comment]
Unfortunately, the problem appears with **every** OPML file, regardless of which source I exported it from (Podgrab, PodcastAddict, etc.).

The problem also seems to be (from my point of view) in a different place:

I have the following error messages in my logs.

```
Debug file located at /app/src/target/release/build/podfetch-38d8cf719dfadbe7/out/built.rs
  ____           _ _____    _       _
 |  _ \ ___   __| |  ___|__| |_ ___| |__
 | |_) / _ \ / _` | |_ / _ \ __/ __| '_ \
 |  __/ (_) | (_| |  _|  __/ || (__| | | |
 |_|   \___/ \__,_|_|  \___|\__\___|_| |_|

2023-05-01T15:43:44 [INFO] - No settings found, inserting default settings
2023-05-01T15:43:44 [INFO] - Starting with the following environment variables:
Public server url: http://localhost:86/
Polling interval for new episodes: 60 minutes
GPodder integration enabled: false
Database url is set to: sqlite:///app/db/podcast.db
Podindex API key&secret configured: false
2023-05-01T15:43:44 [INFO] - starting 4 workers
2023-05-01T15:43:44 [INFO] - Actix runtime found; starting in Actix runtime
thread 'tokio-runtime-worker' panicked at 'Error creating directory: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/service/file_service.rs:54:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtracethread 'tokio-runtime-worker' panicked at 'Error creating directory: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/service/file_service.rs:54:18
thread 'tokio-runtime-worker' panicked at 'Error creating directory: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/service/file_service.rs:54:18
thread 'tokio-runtime-worker' panicked at 'Error creating directory: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/service/file_service.rs:54:18
```

**Comment by SamTV12345** [comment]
Could you please checkout samuel19982/podfetch:develop and pull the image? Does that solve the import of your opml file? Otherwise I need to do some local testing. The feature works but there were some bad file names that were not replaced.

**Comment by d3545t3r** [comment]
Would like to do it, but pulling 

samuel19982/podfetch:develop

only gives me a linux/amd64 image, which I can't test on my arm machine.

Maybe someone else can test it?

**Comment by SamTV12345** [comment]
Sorry the dev tag is better suitable in that case. The latest dev image should contain the changes.

**Comment by d3545t3r** [comment]
the build from

```
Mon, 01 May 2023 20:53:33 +0000
``` 

seems to work (at least for ARM).

Now I have problems with importing some podcasts, but this seems to be a different problem from my point of view and I will open a new ticket for that.
